### ISSUE TITLE
Rename `pymmmc` directory to ... ?

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#101]
... just `marketing`

**Comment by twiecki** [comment]
I'd say `pymc-marketing`, it's pretty standard to have it match the package name, no?

**Comment by ricardoV94** [comment]
Wind an under score right?

**Comment by twiecki** [comment]
Ugh, I guess? `marketing` should be fine too. What would the import be?

**Comment by ricardoV94** [comment]
Will do after #115

**Comment by OriolAbril** [comment]
conf.py and index.md in the docs folder also need to be updated with the change
