### ISSUE TITLE
parameter behavior during `Prior.constrain`

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#1015]
Seems to be upstream from the `preliz.maxent`. Is there a version restriction required?

```python
# Works
Prior("Normal").constrain(lower=-2, upper=2)
Prior("Normal", mu=0).constrain(lower=-2, upper=2)
# Doesn't work
Prior("Normal", mu=0, sigma=1).constrain(lower=-2, upper=2)
````

Think there was a change of behavior, the previous parameters acted as the initial points

**Comment by juanitorduz** [comment]
We should add a test :)

**Comment by wd60622** [comment]
> We should add a test :)

Not documented anywhere either. Do you have any thoughts on behavior? We can go with whatever is most intuitive

**Comment by aloctavodia** [comment]
PreliZ's maxent does not need the user to specify an initial guess. 
The parameters that you pass to Prior are considered fixed parameters, not initial guesses. In the last example both parameters mu and sigma are fixed, with nothing left there to optimize.

This behaviour is documented in the docstring for `constrain` and in this notebook https://github.com/pymc-labs/pymc-marketing/blob/main/docs/source/notebooks/general/model_configuration.ipynb

**Comment by aloctavodia** [comment]
It is already in the docsring https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/prior.py#L772-L780. 

Thanks for the kind comment about  `prior explorer`, it still needs some polishing, but I already find it useful.

**Comment by aloctavodia** [comment]
PreliZ 0.9.1 has been released. Thanks for offering feedback about PreliZ.

**Comment by wd60622** [comment]
Oh, nice. Thank you for quick adjustments. Will close this for now then
