### ISSUE TITLE
Allow user to specify list of HDI's in `plot_posterior_predictive`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#1041]
At the moment `plot_posterior_predictive` has hard-wired HDI's. Plots look like this (taken from MMM docs page):

![Screenshot 2024-09-16 at 16 17 10](https://github.com/user-attachments/assets/a6741351-b858-4227-8c97-03a21bc19489)

This is the relevant line:

https://github.com/pymc-labs/pymc-marketing/blob/aa5fa1d280eae270a7a992dbc82f77586a02f237/pymc_marketing/mmm/base.py#L414

Can we provide a kwarg, called something like `hdi` where the user provides a scalar (or list or scalars). That way, we can decide if we just want one or multiple HDI's and what values they are.

Maybe also expose the `alpha`s, or maybe automatically compute them from the provided `hdi` value(s).

**Comment by Ishaanjolly** [comment]
I saw in #1072  the plotting options are specified but the list/scalar or hdi and alphas is missing. Are you still keen to add this on. Feels like couple of revisions made already to `plot_posterior_predictive`

**Comment by drbenvincent** [comment]
> I saw in #1072 the plotting options are specified but the list/scalar or hdi and alphas is missing. Are you still keen to add this on. Feels like couple of revisions made already to `plot_posterior_predictive`

I think I'll just try to do this now. Good Monday morning warm-up exercise :)

**Comment by Ishaanjolly** [comment]
Yep! easy enough to add!
