### ISSUE TITLE
`MMM.plot_direct_contribution_curves` errors when using `MichaelisMentenSaturation`

### ISSUE THREAD

**Issue by PabloRoque** [pymc-labs/pymc-marketing#1050]
Model initialized as `model = MMM( ..., saturation=MichaelisMentenSaturation(), ...)`

Then, after calling `model.fit(X=X, y=y, ...)`, `model.sample_posterior_predictive(X)`, we try to plot the direct contributions by channel with  `model.plot_direct_contribution_curves(show_fit=True, ...)`:

`AttributeError: 'numpy.ndarray' object has no attribute 'eval'` 

The issue arises from the call to `_plot_response_curve_fit` trying to evaluate a `pytensor.tensor.TensorVariable` in [L1671](https://github.com/pymc-labs/pymc-marketing/blob/bc4b248b8da508c1e5aa03bbcfdf487de0aaeabb/pymc_marketing/mmm/mmm.py#L1671), [L1675](https://github.com/pymc-labs/pymc-marketing/blob/bc4b248b8da508c1e5aa03bbcfdf487de0aaeabb/pymc_marketing/mmm/mmm.py#L1675), and [L1678](https://github.com/pymc-labs/pymc-marketing/blob/bc4b248b8da508c1e5aa03bbcfdf487de0aaeabb/pymc_marketing/mmm/mmm.py#L1678).

Note that `MichaelisMentenSaturation.function` currently returns `float | Any`, contrary to other transformations

1. Hacky fix: comment `.eval()`. 
2. Better fix: modify `michaelis_menten` to return `pytensor.tensor.TensorVariable`

I'll try to open a PR with solution (2) soon

**Comment by wd60622** [comment]
2 seems like best option. Can wrap with as_tensor _variable

**Comment by wd60622** [comment]
Think many of the type hints are wrong or not fully correct anyway. Would be good to consolidate
