### ISSUE TITLE
How to plot the hill saturation curve for each channel with values from posterior

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#1100]
Hello,

How can I get the plots for the hill saturation function after applying it to the data from the posterior.
Is there a sample_posterior for the hill curves?

**Comment by wd60622** [comment]
Hey @shuvayan, there are the methods of the MMM class that will plot the saturation curves.

If you want access to the data, you can use the `SaturationTransformation` workflow:

```python
saturation = mmm.saturation
curve = saturation.sample_curve(mmm.idata.posterior)
```
