### ISSUE TITLE
Test for expected exception

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#1109]
Make use of pytest.raises instead of using pytest.mark.xfail

https://github.com/pymc-labs/pymc-marketing/blob/8a284dc65515e2900d7b63d0d94be8f4a02611b2/tests/test_model_builder.py#L260-L265

**Comment by nhan295** [comment]
can you assign me?

**Comment by wd60622** [comment]
> can you assign me?
> 
> 

Thanks! Go ahead. Just write the "Closes #"
