### ISSUE TITLE
Link sBG notebook in the README

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#1150]
The sBG notebook is not listed in the README. Might also not be linked in the index as well...

https://github.com/pymc-labs/pymc-marketing/blob/ae729bf5942bd4a91e8ab4703ecc0dd9f758d721/README.md#L144-L147

CC: @ColtAllen

**Comment by ColtAllen** [comment]
This notebook is accessible via the documentation, however it's not linked in the index.

**Comment by wd60622** [comment]
Index meaning the home page of pymc marketing docs which looks like README
