### ISSUE TITLE
`ParetoNBDModel` Maintenance Tasks

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#1224]
- [x] Suppress `pytensor` Hyp2F1 Opt warning
- [x] Add `DEMetropolisZ` fitting option
- [x] Fix `thin_fit_result` (`DEMetropolisZ` support may fix this)

**Comment by wd60622** [comment]
> - [ ] Add `DEMetropolisZ` fitting option

What does this look like? Passing a string instead of the `step` directly into `fit`?

**Comment by wd60622** [comment]
>  - [ ] Fix `thin_fit_result` (`DEMetropolisZ` support may fix this)

Is there a traceback that you are trying to fix?

**Comment by ColtAllen** [comment]
> > * [ ]  Add `DEMetropolisZ` fitting option
> 
> What does this look like? Passing a string instead of the `step` directly into `fit`?

Default `tune` and `draw` params should also be increased.

> Is there a traceback that you are trying to fix?

Yes - the way `DEMetropolisZ` is currently being called in the notebook isn't saving the trace in the correct format. Best to make it a fit option rather than adding more workaround code.
