### ISSUE TITLE
Change in error message from latest pydantic version

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#1239]
The latest pydantic version has new validation error message which includes the class name. We should reflect this in the tests

This shows up in currently open PRs. Tests are in test_prior and test_adstock

Lets push up a quick fix for all of the PRs.

CC @juanitorduz

**Comment by juanitorduz** [comment]
Thanks @wd60622 here is a fix https://github.com/pymc-labs/pymc-marketing/pull/1240 🙏
