### ISSUE TITLE
Add `clv_summary` Utility Function

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#126]
When modeling entire customer populations, the `clv` models require `recency`, `frequency`, and `T` summary variables for each customer. For the Gamma-Gamma model, average spend beyond the first transaction is also required. Formatting input data in this fashion is non-trivial, so a utility function would be highly convenient for end users.

The `summary_data_from_transaction_data()` function from Lifetimes can be brought over for this, but will likely require revision because it currently ignores `SettingwithCopyWarning` in Pandas. The name of the Lifetimes function also seems verbose to me, but if `clv_summary()` is not descriptive enough, we can discuss alternatives.

**Comment by ricardoV94** [comment]
`clv_summary` sounds fine
