### ISSUE TITLE
Check for arbitrary VariableFactory in `MMM` and `CLV`

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#1300]
If I would like to use arbitrary PyMC code to define priors for the parameters of either MMM or CLV model. Where do I run into issues?

I would like to check that this functionality works

```python
import pymc as pm
from pymc_marketing.mmm import MMM

class GoodEnough: 
    dims: tuple[str, ...]

    def __init__(self, dims: tuple[str, ...]):
        self.dims = dims

    def create_variable(self, name: str) -> TensorVariable: 
        return pm.Normal(name, mu=0, sigma=1, dims=self.dims)

model_config = {
    "saturation_beta": GoodEnough(dims=("channel", )),
}

# Where does this fail?
mmm = MMM(model_config=model_config, ...)
```

Related to #1292

**Comment by ColtAllen** [comment]
I know the `Prior` class doesn't support `pymc.Deterministic`.

**Comment by wd60622** [comment]
> I know the `Prior` class doesn't support `pymc.Deterministic`.

Prior parameters can be deterministics after recently merged PR. Just needs to match VariableFactory API

**Comment by ColtAllen** [comment]
> > I know the `Prior` class doesn't support `pymc.Deterministic`.
> 
> Prior parameters can be deterministics after recently merged PR. Just needs to match VariableFactory API

Nice, which PR? This may help clean up the `build_model` logic in some of the CLV models.

**Comment by wd60622** [comment]
> > > I know the `Prior` class doesn't support `pymc.Deterministic`.
> 
> > 
> 
> > Prior parameters can be deterministics after recently merged PR. Just needs to match VariableFactory API
> 
> 
> 
> Nice, which PR? This may help clean up the `build_model` logic in some of the CLV models.

This PR relaxes for Prior and media transformations
https://github.com/pymc-labs/pymc-marketing/pull/1292

However, parse model config will block this relaxing for CLV and MMM I believe
