### ISSUE TITLE
Incorrect implementation of tanh saturation in TanhSaturation component

### ISSUE THREAD

**Issue by aseyboldt** [pymc-labs/pymc-marketing#1302]
The definition of the TanhSaturation component introudces an extra scaling factor `beta`, ever though the transformation function contains this scaling factor already:
https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/components/saturation.py#L275

**Comment by wd60622** [comment]
Wanna make a PR?
