### ISSUE TITLE
Minor MMM Example Notebook issues

### ISSUE THREAD

**Issue by cluhmann** [pymc-labs/pymc-marketing#137]
In the [MMM Example Notebook](https://github.com/pymc-labs/pymc-marketing/blob/main/docs/source/notebooks/mmm/mmm_example.ipynb) created by @juanitorduz , there is a plot that refers to `z0` and `z1` and `z0 adstocked & saturated`. But I think the notation at the top of the notebook implies that `z` refers to the "control" variables (i.e., "events" such as product launches, etc.).  But I didn't think these are adstocked or saturated?  I think there may be some labels that are mixed up.

This is the plot that confuses me, though there may be other instances that are similar:

```python
for i, x in enumerate(["x1", "x2"]):
    sns.scatterplot(
        x=df[x],
        y=amplitude * beta_1 * df[f"{x}_adstock_saturated"],
        color=f"C{i}",
        ax=ax[i],
    )
    ax[i].set(
        title=f"$z_{i}$ contribution",
        ylabel=f"$\\beta_1 \cdot z_{i}$ adstocked & saturated",
    )
```

In addition, there is a section called Target Variable under which is the specification how all the components come together to generate the observed time series of sales. It looks like this:

```python
df["intercept"] = 2.0
df["epsilon"] = rng.normal(loc=0.0, scale=0.25, size=n)

amplitude = 1_000
beta_1 = 3.0
beta_2 = 2.0


df["y"] = 1_000 * (
    df["intercept"]
    + df["trend"]
    + df["seasonality"]
    + 1.5 * df["event_1"]
    + 2.5 * df["event_2"]
    + beta_1 * df["x1_adstock_saturated"]
    + beta_2 * df["x2_adstock_saturated"]
    + df["epsilon"]
)
```

Is the `1_000` that begins the linear combination

```
df["y"] = 1_000 * (
```

supposed to instead be `amplitude`?

```
df["y"] = amplitude * (
```

Code later in the notebook seems to suggest it is, but I wasn't 100%.

**Comment by juanitorduz** [comment]
Thanks for the feedback! I'll fix this within the next days 🙂
