### ISSUE TITLE
Allow JAX samplers when available.

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#144]
In my experience, the JAX samplers are a game changer since `pymc` 4. It would be nice to have the option to use them when possible (i.e. they exist in the environment). Related to https://github.com/pymc-labs/pymc-marketing/pull/143

**Comment by ricardoV94** [comment]
As long as kwargs can be passed to `pm.sample` nothing else should be needed after https://github.com/pymc-devs/pymc/pull/6422

**Comment by juanitorduz** [comment]
Awesome 🚀 !
