### ISSUE TITLE
Allow to save/load model?

### ISSUE THREAD

**Issue by ItsJamesMurray** [pymc-labs/pymc-marketing#150]
Is there a plan to add the option to save or load the model? In lifetimes, there is an [option to do so](https://lifetimes.readthedocs.io/en/latest/lifetimes.fitters.html?highlight=save_model#lifetimes.fitters.BaseFitter.save_model).

**Comment by zwelitunyiswa** [comment]
You could just save the inference data with Arviz:

https://python.arviz.org/en/0.14.0/api/generated/arviz.to_netcdf.html

The inference data is just the result of your .fit method (or the result after you run a posterior predictive as well).

**Comment by ricardoV94** [comment]
We may need a method to load fits back into the specific models created here, so I'll add this as a feature request. Thanks for asking

**Comment by twiecki** [comment]
We could inherit from ModelBuilder: https://github.com/pymc-devs/pymc-experimental/pull/104

**Comment by ColtAllen** [comment]
In my fork of lifetimes I added support for saving/loading the model `InferenceData` object as a JSON:

https://github.com/ColtAllen/btyd/blob/main/btyd/models/__init__.py#L157

The model name gets appended to posterior variable names when the model is fit. `load_json()` checks the variable names in the JSON to ensure it's being loaded into the correct model type.

However, ModelBuilder may offer more functionality. Users will probably want options for things like including the observation data.
