### ISSUE TITLE
Rename argument `data_df` to `data`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#162]
`data_df` stands for data dataframe I assume, I think we can just call it `data`?

https://github.com/pymc-labs/pymc-marketing/blob/f264c21e27dfe273494bde29ed6fa0bd6e27266e/pymc_marketing/mmm/base.py#L35

**Comment by ricardoV94** [comment]
What do you think @juanitorduz?

**Comment by juanitorduz** [comment]
No blocker from my side... we just need to be consistent :)

**Comment by michaelraczycki** [comment]
I'd like to do this

**Comment by juanitorduz** [comment]
Go for it 😀
