### ISSUE TITLE
Control coordinate name inconsistent in `DelayedSaturatedMMM`

### ISSUE THREAD

**Issue by xalelax** [pymc-labs/pymc-marketing#166]
In `DelayedSaturatedMMM`, the axis for control variables is named `"control_names"` (see [here](https://github.com/pymc-labs/pymc-marketing/blob/99a1c2c672a2e85c423a90a9d399fd58417d7802/pymc_marketing/mmm/delayed_saturated_mmm.py#L60)). However, in the `dims` argument it is just referenced as `"control"` ([here](https://github.com/pymc-labs/pymc-marketing/blob/99a1c2c672a2e85c423a90a9d399fd58417d7802/pymc_marketing/mmm/delayed_saturated_mmm.py#L108), [here](https://github.com/pymc-labs/pymc-marketing/blob/99a1c2c672a2e85c423a90a9d399fd58417d7802/pymc_marketing/mmm/delayed_saturated_mmm.py#L112), and [here](https://github.com/pymc-labs/pymc-marketing/blob/99a1c2c672a2e85c423a90a9d399fd58417d7802/pymc_marketing/mmm/delayed_saturated_mmm.py#L118)).

Is this a bug?

**Comment by ricardoV94** [comment]
Yes I think, it is!

**Comment by xalelax** [comment]
Took the liberty to create a PR if you don't mind 😄

**Comment by ricardoV94** [comment]
> Took the liberty to create a PR if you don't mind smile

Not at all
