### ISSUE TITLE
Input validation in MMM transformers?

### ISSUE THREAD

**Issue by cluhmann** [pymc-labs/pymc-marketing#170]
Right now there appears to be no checking on the inputs to transformers such as `logistic_saturation()`, `delayed_adstock()`, and `geometric_adstock()`.  So it is currently possible to call these functions with arguments (e.g., `x` contains negative values) that are fine _in general_, but don't seem to make a lot of sense given the application.  For example, the `x` argument is documented as "Input tensor.", but I assume that it's intended to be channel spend (and thus positive).  Do we want to throw warnings or just leave it up to users to not send garbage values in?  Or are there other uses of these tranformers that I'm not seeing that might accept things like negative `x` values?

**Comment by ricardoV94** [comment]
I imagine the inputs may be TensorVariables so you can't check them without adding a possibly costly Pytensor Assert?

**Comment by cluhmann** [comment]
Looks like this is done during initial object construction ([here](https://github.com/pymc-labs/pymc-marketing/blob/a59a89c41e7a1166c61ed2ca4293ff792d726622/pymc_marketing/mmm/validating.py#L56)). So I think this is good for now.
