### ISSUE TITLE
Add black pre-commit hook for notebooks

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#171]

**Comment by wd60622** [comment]
Seems stale now? maybe the ruff toggle for jupyter isn't on

**Comment by ricardoV94** [comment]
I don't remember a PR changing a bunch of NBs, so I think it's still unsolved

**Comment by wd60622** [comment]
I'm guessing we want to use ruff for this then. Might need a rename

**Comment by wd60622** [comment]
Is this done @juanitorduz with your PR for notebook formatting?

**Comment by juanitorduz** [comment]
Yes! Closed by https://github.com/pymc-labs/pymc-marketing/pull/561
