### ISSUE TITLE
Add `BetaGeoBetaBinomModel`

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#176]
The BG/BB model is to my knowledge the only one out there for Discrete Time, Non-Contractual modeling. However, a lot of people don't realize this model is for a different use case than the others in `lifetimes` (myself included when I first started using the library). Maybe rename the model class to `DiscreteNonContractModel` for clarity instead?

https://www.brucehardie.com/papers/020/fader_et_al_mksc_10.pdf

Equation (14) on page 6 of the research paper is an expression for discounted present value of all expected future transactions, which is an interesting alternative to the current `customer_lifetime_value` implementation.

**Comment by juanitorduz** [comment]
Great idea!

**Comment by alexwilde01** [comment]
@ColtAllen thanks for surfacing this one! Do you have a sense of prioritization on BG/BB & extensions against other enhancements?

**Comment by ColtAllen** [comment]
@alexwilde01 I'm currently working on https://github.com/pymc-labs/pymc-marketing/pull/177 and targeting to have it done by 11-Mar. It has some changes which are relevant to BG/BB, so once that's done I'll start on this next.

**Comment by ColtAllen** [comment]
https://github.com/pymc-labs/pymc-marketing/pull/177 has some additional complexities to work out, and [the aspects impacting BG/BB](https://github.com/pymc-labs/pymc-marketing/issues/182) can be done in a separate PR. I'll start on this tomorrow.

**Comment by ColtAllen** [comment]
Expressions 15, 16 & 17 on pages 6-7 of the paper provide marginal posterior distributions for the transaction and churn rates, and product moment (ie, correlation), respectively. The correlation expression is certainly worth adding, but what about the marginal posteriors?

**Comment by wd60622** [comment]
@ColtAllen is this good to close?

**Comment by ColtAllen** [comment]
Yes (sorry, I thought this would auto-close when the PR was merged).
