### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#178]
I created some UML diagrams while working on https://github.com/pymc-labs/pymc-marketing/pull/177, which are shown below. Is it worth adding these to the new-release CI so they are auto-generated each time? Furthermore, are they worth adding to the documentation despite being rather developer-specific?

## MMM
![mmm_uml](https://user-images.githubusercontent.com/10178857/221728588-0075c886-6cf6-48d9-b5f5-fe6008136be6.png)
## CLV
![clv_uml](https://user-images.githubusercontent.com/10178857/221728612-6db908ac-7b17-4276-baf3-1a12a91acd76.png)

## MMM Tests
![tests_mmm_uml](https://user-images.githubusercontent.com/10178857/221728718-75da4053-052e-4c35-8009-62fe8b3901f4.png)

## CLV Tests
![tests_clv_uml](https://user-images.githubusercontent.com/10178857/221728595-3a6e2b64-bbae-4f6b-a1ad-4426c21d8ea2.png)

Note these diagrams only illustrate internal class methods/attributes and inheritance, and will not display imported function calls like `clv.utils.to_xarray()` and `clv.utils.customer_lifetime_value()`.

To recreate these diagrams, install `graphviz` and `pylint` and run this CLI command:
```!bash
$ pyreverse directory/path -f 'ALL' -o png
``` 
This will also create an additional _packages.png_ file which should be deleted.

**Comment by juanitorduz** [comment]
From a developer's perspective, these diagrams look very useful! So +1 to add them in the docs in such a way that is not immediately visible to the average user (might look scary) :)

**Comment by drbenvincent** [comment]
I use this in CausalPy and have these saved and displayed. Do you propose to save and display the images similarly, or just to document that it is possible to create these images? Either way, I propose that this should happen in the new `CONTRIBUTING.md` which will appear when #203 is merged.

I don't have a strong opinion about which of the options we go with :)

**Comment by ColtAllen** [comment]
> I use this in CausalPy and have these saved and displayed. Do you propose to save and display the images similarly, or just to document that it is possible to create these images? Either way, I propose that this should happen in the new `CONTRIBUTING.md` which will appear when #203 is merged.
> 
> I don't have a strong opinion about which of the options we go with :)

I think it would be a good addition to https://github.com/pymc-labs/pymc-marketing/issues/203. The [lifetimes documentation](https://lifetimes.readthedocs.io/en/latest/High%20Level%20Overview.html) has something similar.

**Comment by drbenvincent** [comment]
Did you want to take that on, or do you mind if I give it a go?

**Comment by ColtAllen** [comment]
@drbenvincent I'm busy with a few other PRs right now, so feel free to work on this one.
