### ISSUE TITLE
PyMC test helper function missing

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#189]
When looking into https://github.com/pymc-labs/pymc-marketing/pull/186 I saw that a job is failing because:

```python
_______________ ERROR collecting tests/clv/test_distributions.py _______________
ImportError while importing test module '/home/runner/work/pymc-marketing/pymc-marketing/tests/clv/test_distributions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/clv/test_distributions.py:7: in <module>
    from pymc.tests.helpers import select_by_precision
E   ModuleNotFoundError: No module named 'pymc.tests'
```

Can this be related to https://github.com/pymc-devs/pymc/pull/6540 @ricardoV94 ?

**Comment by ricardoV94** [comment]
Yes, we are porting the utilities back to pymc.tests so that they can be used by downstream packages

**Comment by michaelraczycki** [comment]
could you give a bit more insight about this? I could take care of that

**Comment by ricardoV94** [comment]
@michaelraczycki I think I'll take care of it now as it is a problem in multiple libraries we have.

Just because of the urgency
