### ISSUE TITLE
Remove all instances of old repo name, `pymmc`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#190]
Searching the repo, there are a number of instances of the old package name `pymmc`. Some of these are in notebooks, some relate to names of virtual environments. We should remove these to eliminate confusion.

**Comment by wd60622** [comment]
Seeing only a few instances in the notebooks and kernels 
https://github.com/search?q=repo%3Apymc-labs%2Fpymc-marketing+pymmmc&type=code 

I'm surprised that badge still works with the previous repo name. Actually just reroutes to the new repo link
https://github.com/pymc-labs/pymc-marketing/workflows/ci/badge.svg 

I could take but it would require rerunning all the notebooks

**Comment by ricardoV94** [comment]
I think the environment name of the notebooks is fine. The badge worked because github forwards renamed repo names for quite some time.

**Comment by cluhmann** [comment]
Anything left here or can this be closed?

**Comment by ricardoV94** [comment]
Closing tentatively
