### ISSUE TITLE
readthedocs: make the footer not massive

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#191]
Not sure if this is intentional, but the footer is _massive_ and obscures the core content.

If it's possible, could we have it as 'non sticky' so it doesn't occupy any of the screen unless you've scrolled to the bottom of the page?

Safari
<img width="1792" alt="Screenshot 2023-03-06 at 10 39 28" src="https://user-images.githubusercontent.com/6765047/223087415-9653d48b-a1b5-43b8-b8ea-a4669e297d9f.png">
Chrome
<img width="1792" alt="Screenshot 2023-03-06 at 10 40 53" src="https://user-images.githubusercontent.com/6765047/223087698-307f42ec-20a0-4a4f-b5d2-bd218a808673.png">

**Comment by ricardoV94** [comment]
I'm on it

**Comment by OriolAbril** [comment]
I can take a look at some point this afternoon too. It probably has to do withthe 0.13 release of the pydata-sphinx-theme. The theme version message should not be duplicated and the footer be only the messages in a single line, similar to the main labs website
