### ISSUE TITLE
Run tests on oldest supported version of PyMC

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#193]
We should run our tests on the oldest supported version of PyMC (from the `pyproject.toml`) as well as the latest (which we do already)

**Comment by juanitorduz** [comment]
Do you have a reference on how this can be done?

**Comment by ricardoV94** [comment]
I think the easiest is to duplicate the tests and explicitly set pymc=min_version.

The default one tests on the latest already.
