### ISSUE TITLE
MMM transformer(s) fail when parameters are not scalars?

### ISSUE THREAD

**Issue by cluhmann** [pymc-labs/pymc-marketing#196]
I may be naive in attempting to use existing transformers to do forward sampling (e.g., after sampling from the posterior) (and not wanting to use an inefficient for loop: https://github.com/pymc-labs/pymc-marketing/issues/22).  @lucianopaz seems to be working on something similar here: https://github.com/pymc-labs/pymc-marketing/pull/114, though it seems pretty involved (as shape issues tend to be). And @juanitorduz mentioned that he wrote some extra functions to do the forward pass, but the idea of having nearly duplicate code (e.g., `geometric_adstock()` and `geometric_adstock_forward()`) seems less than ideal.  So take that context into account while reading the following.  If what I have below is overly simplistic and https://github.com/pymc-labs/pymc-marketing/pull/114 would be a better, more robust solution, that's fine.

### Adstock
The following works:
```python
x = rng.random(size=100)
alpha = 1
geometric_adstock(x=x, alpha=alpha).eval()
```
The following fails with a constant_folding error:
```python
x = rng.random(size=100)
alpha = rng.random(size=10)
geometric_adstock(x=x, alpha=alpha).eval()
```
I assume this is a reasonable thing to want to do, but maybe I confused.

Perhaps [this line](https://github.com/pymc-labs/pymc-marketing/blob/e4e05e0abcdb6322850969766ef618f97e0ab7f7/pymc_marketing/mmm/transformers.py#L38) should instead be:

```python
return pt.dot(w.T, x_cycle)
```

I think the 2 versions are equivalent when `w.shape==(l_max,)`, but diverge when `w.shape==(l_max,alpha.shape[0])`?  Hand coding this into a fresh geometric adstock function seems to work in both the cases above.  But again, I may be confused.

### Saturation
The following works:
```python
x = rng.random(size=100)
lam = 1
logistic_saturation(x=x, lam=lam).eval()
```
The following fails:
```python
x = rng.random(size=100)
lam = rng.random(size=10)
logistic_saturation(x=x, lam=lam).eval()
```
with this shape error:
```
ValueError: operands could not be broadcast together with shapes (10,) (100,) 
```
The solution here seem to require some reshaping of `x` and `lam` so that the multiplication (e.g. [here](https://github.com/pymc-labs/pymc-marketing/blob/e4e05e0abcdb6322850969766ef618f97e0ab7f7/pymc_marketing/mmm/transformers.py#L128)) works out correctly (e.g., `x.reshape(-1,1)` and `lam.reshape(1,-1)`).

**Comment by cluhmann** [comment]
I also realized that the shape of both `x` and `lam`/`alpha` will probably need to be flexible as doing something like the following will break if `logistic_saturation` assumes that the shape of `x` is `(T,)`.

```python
alpha = rng.random(size=10)
lam = rng.random(size=10)

x = rng.random(size=100)
# x.shape = (100,)
x_adstocked = geometric_adstock(x=x, alpha=alpha).eval()
# x_adstocked.shape = (100, 10)
x_adstocked_saturated = logistic_saturation(x=x, lam=lam).eval()
```

Maybe this is where things like `geometric_adstock_vectorized()` come in? Not sure.

**Comment by cluhmann** [comment]
For a more "realistic" vignette, see [this gist](https://gist.github.com/cluhmann/af9c0d3db6ea155f40f4a221c3a5ac8a). @ricardoV94 you asked for this.

**Comment by ricardoV94** [comment]
@cluhmann Can you check if #221 is doing what you need?

I need to rewrite your gist to align dimensions:
```python
# pump new spend (and old estimated model parameters) through model

alpha1 = mmm.fit_result.posterior["alpha"].sel(channel="x1").values.ravel()
alpha2 = mmm.fit_result.posterior["alpha"].sel(channel="x2").values.ravel()

lam1 = mmm.fit_result.posterior["lam"].sel(channel="x1").values.ravel()
lam2 = mmm.fit_result.posterior["lam"].sel(channel="x2").values.ravel()

beta1 = mmm.fit_result.posterior["beta_channel"].sel(channel="x1").values.ravel()
beta2 = mmm.fit_result.posterior["beta_channel"].sel(channel="x2").values.ravel()

x1_adstocked = geometric_adstock(x=new_x1, alpha=alpha1, l_max=8, normalize=True).eval()
x2_adstocked = geometric_adstock(x=new_x2, alpha=alpha2, l_max=8, normalize=True).eval()

x1_ad_saturated = logistic_saturation(x=x1_adstocked, lam=lam1[..., None]).eval()
x2_ad_saturated = logistic_saturation(x=x2_adstocked, lam=lam2[..., None]).eval()

x1_contribution = beta1[..., None] * x1_ad_saturated
x2_contribution = beta2[..., None] * x2_ad_saturated
```
If you are okay with the samples on the right, instead of all the `[..., None]`, you can just transpose `x1_adstocked` and `x2_adstocked`

**Comment by cluhmann** [comment]
Let me verify that this works and then I can comment on https://github.com/pymc-labs/pymc-marketing/pull/221.

**Comment by cluhmann** [comment]
These lines still seem to fail?

```python
x1_adstocked = geometric_adstock(x=new_x1, alpha=alpha1, l_max=8, normalize=True).eval()
x2_adstocked = geometric_adstock(x=new_x2, alpha=alpha2, l_max=8, normalize=True).eval()
```

With this sort of shape mismatch:

```python
ValueError: shapes (8,4000) and (8,179) not aligned: 4000 (dim 1) != 8 (dim 0)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: dot(TensorConstant{[[1.585635..6575e-13]]}, TensorConstant{[[0.350438..26437124]]})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "[/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py](https://file+.vscode-resource.vscode-cdn.net/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py)", line 1933, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "[/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py](https://file+.vscode-resource.vscode-cdn.net/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py)", line 1092, in transform
    return self.fn(fgraph, node)
...
  File "[/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/link/c/basic.py](https://file+.vscode-resource.vscode-cdn.net/home/xian/mambaforge/envs/pymc/lib/python3.10/site-packages/pytensor/link/c/basic.py)", line 1788, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: Shape mismatch: x has 4000 cols (and 8 rows) but y has 8 rows (and 179 cols)
```

**Comment by ricardoV94** [comment]
Weird, not for me. Are you on this branch for sure?

**Comment by cluhmann** [comment]
Oh sorry.  I thought the code snippet and the PR were independent (which is why I left my previous comment).
