### ISSUE TITLE
Fix (and document) local building of the docs

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#205]
Currently when set up in a dev environment, trying to build the docs locally with `make html` results in the error
```
sphinx-build docs/source docs/build -b html
make: sphinx-build: No such file or directory
make: *** [html] Error 1
```

If someone can point me towards a fix, I can do that and update the dev instructions for local doc builds.

**Comment by ricardoV94** [comment]
CC @OriolAbril

**Comment by OriolAbril** [comment]
That means sphinx is not installed or somehow it is not available from the command line. Try `pip install .[docs]` to install the doc dependencies, then run make html

**Comment by drbenvincent** [comment]
Ah ok, editing the makefile to this does work.

```
html:
    pip install .[docs]
    sphinx-build docs/source docs/build -b html
```

**Comment by OriolAbril** [comment]
In case it helps in future cases, zsh is a bit particular with [], it doesn't work like bash, you need to put them within "", to be able to install packages with extra dependencies with pip from zsh you need to use:

```
pip install ".[docs]"
pip install "pymc-marketing[docs]"
```
