### ISSUE TITLE
How to contribute (and MAP-estimates)

### ISSUE THREAD

**Issue by ChristianMichelsen** [pymc-labs/pymc-marketing#212]
Hi,

First of all, thanks a lot for releasing such a great package!

I started looking into CLV and first found the `lifetimes` package which later led to this package. 
Even though I much prefer fully Bayesian models, I found that the computational complexity of using the full posterior sometimes lead to infeasible run times in my data set. This was not a problem with `lifetimes`. 

As such, I made some minor tweaks to allow for an approximate MAP procedure which if course is an approximation, but also allows for much shorter run times in cases where that is important. 

My changes are located [here](https://github.com/ChristianMichelsen/pymc-marketing/tree/add-MAP). If you find them relevant, I want to help contribute them to this package, however, I couldn't find a contribution guide, so how do you prefer external contributions?

Thanks a lot in advance. 

Cheers!

**Comment by ricardoV94** [comment]
@ChristianMichelsen thanks for taking a look. I don't know if you saw but we already allow for fitting CLV models with MAP in which case the trace has a single point. The summary methods should work fine out of the box with a trave with a single "chain" and "draw" (the MAP)

**Comment by ColtAllen** [comment]
Hey @ChristianMichelsen,

Thanks for offering to contribute! The latest version of  our contributing guide is here:

https://github.com/pymc-labs/pymc-marketing/blob/main/CONTRIBUTING.md

But now that you mention it, a Pull Request Best Practices section would be an excellent addition, [so I've created an issue for it.](https://github.com/pymc-labs/pymc-marketing/issues/213)

It also seems your additions resolve  https://github.com/pymc-labs/pymc-marketing/issues/168, so if you want to go ahead and create a Draft PR, we can advise you on where to go from there.

> I found that the computational complexity of using the full posterior sometimes lead to infeasible run times in my data set. This was not a problem with lifetimes.

@ricardoV94 The new NUTS samplers in the latest `pymc` release are blazing fast. Are we able to use those yet in `pymc-marketing`?

**Comment by ricardoV94** [comment]
Yes you can pass arbitrary kwargs to `pm.sample`, including `nuts_sampler` which allows to defer sampling to Nutpie or Jax samplers

**Comment by ColtAllen** [comment]
> Yes you can pass arbitrary kwargs to `pymc.sample` via `CLVModel.fit`, including `nuts_sampler` which gives access to Nutpie or Jax samplers

Would something like `pip install pymc[numpyro]` work for the JAX samplers? Or do users still need to follow this guide:

https://www.pymc.io/projects/docs/en/latest/installation.html

**Comment by ricardoV94** [comment]
Still need to follow the guide, I don't think we have any optional dependencies defined on PyMC. If you think it would make things easier feel free to open an issue on the repo.

**Comment by ricardoV94** [comment]
@ChristianMichelsen can we close this issue or is there something you think should be addressed code-wise which is not tracked already in other issues?

**Comment by ChristianMichelsen** [comment]
I had completely overlooked the general `CLVModel` and only looked at the `BetaGeoModel` and `GammaGammaModel`. Thanks a lot for the quick and thorough response!
