### ISSUE TITLE
Add PR Best Practices Section to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#213]
I think [aspiring contributors](https://github.com/pymc-labs/pymc-marketing/issues/212) would find this very helpful.  

@drbenvincent  do you want to take a stab at this? We could base it on the PR guides for `bambi` and/or `pymc`:

https://github.com/bambinos/bambi/blob/main/docs/CONTRIBUTING.md
https://www.pymc.io/projects/docs/en/latest/contributing/pr_checklist.html
https://www.pymc.io/projects/docs/en/latest/contributing/pr_tutorial.html

**Comment by drbenvincent** [comment]
I'm happy to give this a go, but I think I'll only have capacity about 1-2 weeks after the release announcement / webinar. If you or anyone else wants to jump in before that point then feel free 👍🏻
