### ISSUE TITLE
MAP fits Failing for `BetaGeoModel`

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#214]
Should probably fix this before the Official Release:

```
from lifetimes.datasets import load_cdnow_summary
from pymc_marketing.clv import BetaGeoModel


df = load_cdnow_summary()

model = BetaGeoModel(customer_id=df['ID'], 
                     frequency=df['frequency'], 
                     recency=df['recency'],
                     T=df['T'],
                    )

model.fit(fit_method='map')
```

```
SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'a_log__': array(0.), 'b_log__': array(0.), 'alpha_log__': array(0.), 'r_log__': array(0.)}

Initial evaluation results:
{'a': 0.0, 'b': 0.0, 'alpha': 0.0, 'r': 0.0, 'likelihood': nan}
```

**Comment by ricardoV94** [comment]
Can probably use a custom initial value for the priors if that's the problem.

**Comment by ricardoV94** [comment]
This has caused a lot of confusion but the second dictionary contains the log-probabilities

**Comment by larryshamalama** [comment]
> This has caused a lot of confusion: the second dictionary contains the log-probabilities. We should write it explicitly in the error message

I can create a beginner friendly issue in the PyMC repo later today

**Comment by ricardoV94** [comment]
> > This has caused a lot of confusion: the second dictionary contains the log-probabilities. We should write it explicitly in the error message
> 
> I can create a beginner friendly issue in the PyMC repo later today

That would be good!

**Comment by ricardoV94** [comment]
For sorting the issue, we need to know why is `a = b = alpha = r = 1` invalid, and what would be a safe default instead. This could also mean that simple positive priors may be incorrect for this model?

**Comment by ColtAllen** [comment]
> For sorting the issue, we need to know why is `a = b = alpha = r = 1` invalid, and what would be a safe default instead. This could also mean that simple positive priors may be incorrect for this model?

Parameter values must be positive, but `a` and `b` are parameters of a beta distribution. Might work better to pool those priors. Here's some code I wrote in the past for this model:

https://github.com/ColtAllen/btyd/blob/main/btyd/models/beta_geo_model.py#L97

**Comment by ricardoV94** [comment]
Regularizing the priors is certainly important, but the snippet above is failing already at the initial point. That means those values can't all be 1 for this dataset (or if they can, our log is too unstable)

**Comment by ColtAllen** [comment]
In the `logp` expression:

```
c4 = a / (b + x - 1)

logp = d1 + d2 + pt.log(c3 + c4 * pt.switch(x_zero, 1, 0))
```

`c4` will throw a DIV/0 if b=1 and x=0. Should it be placed inside `pt.switch()`?

**Comment by larryshamalama** [comment]
> In the `logp` expression:
> 
> ```
> c4 = a / (b + x - 1)
> 
> logp = d1 + d2 + pt.log(c3 + c4 * pt.switch(x_zero, 1, 0))
> ```
> 
> `c4` will throw a DIV/0 if b=1 and x=0. Should it be placed inside `pt.switch()`?

That sounds right! Good catch

**Comment by ricardoV94** [comment]
Cool, yeah sounds like that would solve it

**Comment by larryshamalama** [comment]
I can spin a PR for this
