### ISSUE TITLE
Add plots to BG/NBD example notebook

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#225]
The current [**BG/NBD model** example notebook](https://www.pymc-marketing.io/en/stable/notebooks/clv/bg_nbd.html) is pretty minimal. I think it could be improved in terms of how useful it is for users by adding plots.

I know it's a different dataset, but would it be possible to add in plots like the ones @ricardoV94 put together in [this notebook](https://github.com/pymc-labs/pymc-marketing/pull/163/files#diff-66966ef483af447abefebf60038fee6c4183134933311d080c94d245c9a68d4f) in a PR which will be closed at some point.

If that doesn't work and the current notebook is meant to be a really minimal comparison to Lifetimes, then perhaps we could lift the BG/NBD example from @ricardoV94 's draft. I think it's a shame to loose them completely.

**Comment by juanitorduz** [comment]
Closed by https://github.com/pymc-labs/pymc-marketing/pull/571
