### ISSUE TITLE
Add links to CLV and MMM examples at the end of guide

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#236]
The new guide sections are really cool. I think it makes sense to round them off with the links to the CLV and MMM notebooks, so people can "jump" to the library.

CC @drbenvincent

**Comment by drbenvincent** [comment]
I think that's a great idea. I have to focus on a preparing for a client kickoff call for the rest of the day. So I can do it tomorrow morning, if someone doesn't get to it before

**Comment by ricardoV94** [comment]
I think it's the same as in PyMC and there must be examples there. If not just CC @OriolAbril :D

**Comment by cluhmann** [comment]
I think I can manage/try.  Then someone else can clean up the mess I make :grimacing: .

**Comment by OriolAbril** [comment]
This should help: https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_documentation/docs_presentation.html#cross-referencing-roles

**Comment by drbenvincent** [comment]
> Are there any examples of intra-docs linking? If so, I can use them as a template and add these links to the examples.

Yes. Intra-doc links are in Why PyMC-Marketing page
