### ISSUE TITLE
Create a contributions breakdown chart for MMM

### ISSUE THREAD

**Issue by Garve** [pymc-labs/pymc-marketing#241]
Hi!

I think business stakeholder often enjoy plots like this:
![image](https://user-images.githubusercontent.com/932327/231825847-b87b20e1-604d-4458-bcf6-700edd85bc9a.png)

What do you think?

Best
Robert

**Comment by twiecki** [comment]
I agree @Garve, want to do a PR?

**Comment by Garve** [comment]
Yeah, in my version you can see per day how much sales were generated because of the different media channels. This works for linear models such as the DelayedSaturatedMMM since we can decompose the sales into sales = f(TV spends) + g(Radio spends) + ...
