### ISSUE TITLE
Error when running CLV Quickstart

### ISSUE THREAD

**Issue by JAGalvis** [pymc-labs/pymc-marketing#246]
## Problem Description

I've been trying to run the quickstart for CLV but the `bgm.fit()` returns an error.
I have used the same code and data from the example, as well as tried with my own data with same results.

## Error Message
" 
340 # globals, (look for code object in it's co_consts attribute..) and 
341 # add the result to code_globals 342 if co.co_consts: IndexError: tuple index out of range
"

## Environment
OS: Windows
Python version: 3.11.3
pymc-marketing==0.1.0

Thanks!!

**Comment by JAGalvis** [comment]
I created a new environment with Python 3.9 and is running ok.

**Comment by drbenvincent** [comment]
Thanks for checking out the package - glad it's working now. I'll close this issue, but just send us messages if there's anything else.
