### ISSUE TITLE
CLV quickstart example uses wrong frequency

### ISSUE THREAD

**Issue by AdJasper** [pymc-labs/pymc-marketing#256]
First of all thanks for this amazing library and it's great to see many people actively working on this!

I have two questions regarding the example notebook [CLV Quickstart](https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html#estimating-clv).

1. While estimating the CLV, one of the arguments of the `expected_customer_lifetime_value` method is `time`. The comment in this line says you are predicting for 12 months while the units of time in the rest of the notebook are in weeks. In addition, if I check the API documentation of this method, the default value for `freq` is "D" (days). So if you are predicting for months, `freq` should equal "M", right?
2. How did you define "Customer Lifetime Value" in your package because if we speak about the lifetime of a customer, that also includes the time before the prediction. I believe the method is calculating the value a customer creates after time T, where the period up to T is used to fit the model. 
 
An example: Customer X makes its first purchase at 20-04-2022 (DD-MM-YYYY). We fit a model today (20-04-2023) and predict the number of purchases and their average monetary value for one year in the future (up untill 20-04-2024). The CLV is then the value that the customer generated from 20-04-2022 untill 20-04-2024, right? Is this also what we are computing when we use this package? Or do we estimate the value that the customer will generate in the period today untill 20-04-2024 (so for the future only)?

**Comment by ricardoV94** [comment]
Thanks for the questions.

> In addition, if I check the API documentation of this method, the default value for freq is "D" (days). So if you are predicting for months, freq should equal "M", right?

I could be mistaken, but I think `freq` is just about the granularity (number of steps) at which you estimate the lifetime value. The value is always in terms of months, but you can integrate over hourly, daily, weekly or monthly steps. I will double check to be sure.

> I believe the method is calculating the value a customer creates after time T, where the period up to T is used to fit the model.

Yes that's what it is doing. You already observed the value of the customer until today, so there's no uncertainty there.
