### ISSUE TITLE
compute_mean_contributions_over_time not found

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/pymc-marketing#263]
From: https://discourse.pymc.io/t/pymc-marketing-example-method-not-present-in-package/12017

am trying to reproduce the analysis done in the [Example notebook 1](https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_example.html#part-ii-modeling) for the new Pymc-marketing package.

However, some of the methods used seem to not be present in the package. in particular the [DelayedSaturatedMMM.compute_mean_contributions_over_time](https://www.pymc-marketing.io/en/latest/api/generated/pymc_marketing.mmm.delayed_saturated_mmm.DelayedSaturatedMMM.compute_mean_contributions_over_time.html), is used in the example, it is listed in the docs, but is not present in the actual package.

when running
```
mmm.compute_mean_contributions_over_time()
```
returns
```
AttributeError: 'DelayedSaturatedMMM' object has no attribute 'compute_mean_contributions_over_time'
```

**Comment by juanitorduz** [comment]
This is not a bug, but rather a new method which is available in the main branch but not in the latest release ;l)
