### ISSUE TITLE
Env creation doesn't work for MacOS

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-labs/pymc-marketing#288]
I'm trying to create a fresh env for pymc-marketing on M1 Pro and following the installation steps from https://pymc-marketing--240.org.readthedocs.build/en/240/ doesn't work. After installing all the dependencies and running the mmm tests I'm getting pytensor errors:

```
ERROR    pytensor.graph.rewriting.basic:basic.py:1753 Rewrite failure due to: constant_folding
ERROR    pytensor.graph.rewriting.basic:basic.py:1754 node: InplaceDimShuffle{}(TensorConstant{(1,) of 2})
ERROR    pytensor.graph.rewriting.basic:basic.py:1755 TRACEBACK:
ERROR    pytensor.graph.rewriting.basic:basic.py:1756 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/graph/rewriting/basic.py", line 1918, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/graph/rewriting/basic.py", line 1078, in transform
    return self.fn(fgraph, node)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/tensor/rewriting/basic.py", line 1138, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/basic.py", line 1200, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/basic.py", line 1120, in __compile__
    thunk, module = self.cthunk_factory(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/basic.py", line 1644, in cthunk_factory
    module = cache.module_from_key(key=key, lnk=self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/cmodule.py", line 1240, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/basic.py", line 1543, in compile_cmodule
    module = c_compiler.compile_str(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/cmodule.py", line 2661, in compile_str
    return dlimport(lib_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytensor/link/c/cmodule.py", line 341, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: dlopen(/Users/michalraczycki/.pytensor/compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.9.0-64/tmpydinhm88/mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.so, 0x0002): tried: '/Users/michalraczycki/.pytensor/compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.9.0-64/tmpydinhm88/mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/michalraczycki/.pytensor/compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.9.0-64/tmpydinhm88/mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.so' (no such file), '/Users/michalraczycki/.pytensor/compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.9.0-64/tmpydinhm88/mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

as I've heard that it's a known issue, it would be good to create a reliable installation guide for macOS (I managed to somehow get it to work, but I failed to replicate the solution). Also it seems like it might be something with versioning issues, Once I've tried to make the env available as a jupyter notebook kernel (so installed the ipykernel lib) some of the pytensor functionalities stopped working, after deinstalation of ipykernel and reinstalling pymc it was working again

**Comment by BBDS-Colt** [comment]
Hey @michaelraczycki, 

I may be able to help if you provide some additional information:

OS Name & Version
Environment Manager (Conda, `venv`, `mamba`, etc.)
IDE (VSCode, PyCharm, etc.)

My primary dev workstation for the contributions I've made to this library is a 2023 M2 MacBook Pro, with OS Ventura 13.4. I set up my `pymc-marketing` dev environment with miniconda and Python v3.8.15. I work in PyCharm and have never had any issues.

**Comment by ColtAllen** [comment]
Hey @michaelraczycki,

I may be able to help if you provide some additional information:

OS Name & Version
Environment Manager (Conda, venv, mamba, etc.)
IDE (VSCode, PyCharm, etc.)

My primary dev workstation for the contributions I've made to this library is a 2023 M2 MacBook Pro, with OS Ventura 13.4. I set up my pymc-marketing dev environment with miniconda and Python v3.8.15. I work in PyCharm and have never had any issues.

**Comment by michaelraczycki** [comment]
Hey @ColtAllen, Thank you for your offer, actually I've already found a way to create it on M1. I guess I can close this one now, and probably have a mental note to myself to maybe create some kind of guide for M1s on how to avoid pytensor issues

**Comment by eirikbaekkelund** [comment]
I'm facing this issue @michaelraczycki - would you mind sharing how you got it to work? This should maybe be re-opened or adressed so that the PyMC team is made aware. Because following their current installation guide reproduces this issue when running on a conda env in VSC for the following code block:

`import pymc as pm
import numpy as np
import arviz as az
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

seed = 42
np.random.seed(seed)

def plot_data(x1, x2, y):
    """  
    Plot data
    """
    _, axes = plt.subplots(1, 2, figsize=(10, 5))
    axes[0].scatter(x1, y, color='blue')
    axes[1].scatter(x2, y, color='blue')
    axes[0].set_xlabel('x1')
    axes[1].set_xlabel('x2')
    axes[0].set_ylabel('y')
    plt.tight_layout()
    plt.show()

def generate_data():
    """
    Generate data
    """
    N = 100
    alpha, sig = 1, 1
    beta = [1, 2.5]
    eps = np.random.randn(N) * sig

    x1 = np.random.randn(N)
    x2 = np.random.randn(N) * 0.2

    y = alpha + beta[0] * x1 + beta[1] * x2 + eps
    
    return x1, x2, y

def construct_model(x1, x2, y):
    model = pm.Model()
    with model:
        alpha = pm.Normal('alpha', mu=0, sigma=10)
        beta = pm.Normal('beta', mu=0, sigma=10, shape=2)
        sigma = pm.HalfNormal('sigma', sigma=1)
        mu = alpha + beta[0] * x1 + beta[1] * x2

        y_obs = pm.Normal('y_obs', mu=mu, sigma=sigma, observed=y)
    return model, y_obs, mu, sigma


if __name__ == '__main__':
    x1, x2, y = generate_data()
    # plot_data(x1, x2, y)
    model, y_obs, mu, sig = construct_model(x1, x2, y)
    
    
`

**Comment by twiecki** [comment]
@eirikbaekkelund Can you post the output of `conda list` and what command you used for installation?

**Comment by eirikbaekkelund** [comment]
Currently do not have the environment anymore and got it to work. However, I think it's related to the order of which you install pymc, and blackjax/numpyro/nutpie.
