### ISSUE TITLE
update environment + README to enable use of graphviz

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#29]
Would be good to able to use `pm.model_to_graphviz(model)` in the Jupyter notebooks.

**Comment by cluhmann** [comment]
Looks like https://github.com/pymc-labs/pymc-marketing/pull/163 covers this functionality for the MMM side of things.  CLV does not seem to have anything similar yet.

**Comment by drbenvincent** [comment]
Feel free to close
