### ISSUE TITLE
Publish paper about this package in JOSS

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pymc-marketing#30]
It would be good to maximise the benefits of writing this. So we could put together a paper at JOSS https://joss.theoj.org/

**Comment by larryshamalama** [comment]
Is this still of interest? If so, I can definitely help from the CLV side of things. I am also not sure on how we should tailor the writing towards JOSS.

**Comment by drbenvincent** [comment]
Some folk are putting a paper together I believe. Not sure where they are targeting it at.

**Comment by wd60622** [comment]
I have been interested in this for some of my personal packages and would be interested to see this happen at some point. Aren't some of the JOSS papers quite short? How much effort would this be?
