### ISSUE TITLE
Add posterior population distributions for `BetaGeoModel`

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#301]
Think one of the cool attributes on the `BetaGeoModel` assumptions are the population distributions. 

Think they are useful for understanding the fit high level but also might be interesting to see population shift the time varying parameter version or other variations down the line

Seems like it can be implemented pretty straight forward and wrapped in a function like some of the [GammaGamma Models methods](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/clv/models/gamma_gamma.py)

```python 
with pm.Model(): 
    # Dummy for the sampling
    a = pm.HalfFlat("a")
    b = pm.HalfFlat("b")
    alpha = pm.HalfFlat("alpha")
    r = pm.HalfFlat("r")

    population_dropout = pm.Beta("population_dropout", alpha=a, beta=b)
    # Need to double check this parameterization
    population_purchase_rate = pm.Gamma("population_purchase_rate", alpha=alpha, beta=r)
    
    pp = pm.sample_posterior_predictive(
        self.fit_results, 
        var_names=["population_dropout", "population_purchase_rate"], 
        ... # would be function args like in gamma gamma
    ).posterior_predictive
```

Any thoughts on if this would be a valuable addition? Would be willing to implement and add to the docs 😄

**Comment by ricardoV94** [comment]
@wd60622 would that be equivalent to `distribution_new_customer_spend` in the `GammaGamma` model?

If so, I think it would be a good addition.

**Comment by wd60622** [comment]
Think that is closely related, goes with two of the assumptions of the generation process. 

From these samples, we could create these figures [(taken from here)](https://towardsdatascience.com/modeling-customer-lifetime-value-with-lifetimes-71171a35f654#:~:text=CLV%20estimation%20using%20BG%2DNBD&text=This%20estimate%20relies%20on%20the,values%20in%20the%20observation%20period.) or make statistics about the population

<img width="500" alt="beta-geo-pop-params" src="https://github.com/pymc-labs/pymc-marketing/assets/57733339/3d2703e2-c306-4980-a5c7-0631fe6a755c">
