### ISSUE TITLE
MMM example notebook not working

### ISSUE THREAD

**Issue by smusch2** [pymc-labs/pymc-marketing#321]
[MMM Example Notebook](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html)

Notebook works until the "DelayedSaturatedMMM" model is defined.

`mmm.fit(target_accept=0.95, chains=4, random_seed=rng)`

Error: TypeError: ModelBuilder.fit() missing 1 required positional argument: 'X'

**Comment by ricardoV94** [comment]
CC @michaelraczycki

**Comment by ricardoV94** [comment]
Thanks for reporting. We did some refactoring recently and this might have slipped under our radar.

We'll take a look soon

**Comment by ricardoV94** [comment]
@smusch2 which version of PyMC-Marketing are you using?

That links refers to the last official release on pypi. If you installed from the repo, these would be the up to date docs: https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_example.html

**Comment by ricardoV94** [comment]
How did you install the library?

**Comment by smusch2** [comment]
@ricardoV94 
`pip install git+https://github.com/pymc-labs/pymc-marketing.git`

**Comment by ricardoV94** [comment]
I suggest you install through the official release channels instead: https://www.pymc-marketing.io/en/stable/#installation

Or just `pip install pymc-marketing` without the `git+` bit

**Comment by ricardoV94** [comment]
The `git +` is to test out the next release before it's out, but then you have to check the documentation in `latest` not `stable`. If you just want to try out the library it's better not to do the pre-release installation

**Comment by smusch2** [comment]
Yep, that worked when running in Google Colab. It doesn't work in Jupyter still, but that must be an issue on my side. Thanks!
