### ISSUE TITLE
mmm.model returning none - package error

### ISSUE THREAD

**Issue by allisonwienerclorox** [pymc-labs/pymc-marketing#325]
Hi, I had the sample code from the MMM Example Notebook running just fine one day, but now after rerunning with no changes from my end I'm getting an error that I believe has to do with "mmm.model" being empty. Can you help me determine why? Code below, but it's essentially copy/pasted from https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html.
```
>
%sh 
pip install git+https://github.com/pymc-labs/pymc-marketing.git
%pip install pymc-marketing
%pip install graphviz
```
```python
import scipy
from scipy.linalg import blas
import matplotlib.pyplot as plt
import arviz as az
import numpy as np
import pandas as pd
import pymc as pm
import seaborn as sns

from pymc_marketing.mmm.transformers import geometric_adstock, logistic_saturation
from pymc_marketing.mmm.delayed_saturated_mmm import DelayedSaturatedMMM
```
From: https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html 

```python
mmm = DelayedSaturatedMMM(
    data=data,
    target_column="y",
    date_column="date_week",
    channel_columns=["x1", "x2"],
    control_columns=[
        "event_1",
        "event_2",
        "t",
    ],
    adstock_max_lag=8,
    yearly_seasonality=2,
)

type(mmm.model)
```
TypeError: No model on context stack. 
<
Using pymc-5.6.0

<img width="1359" alt="PyMC Error" src="https://github.com/pymc-labs/pymc-marketing/assets/59663830/f3da3de2-ec88-4898-9a33-2abff43ec78c">

**Comment by cluhmann** [comment]
What you are installing is the (current) development version.  As detailed in [the installation instructions](https://www.pymc-marketing.io/en/stable/#installation), you should only do this to "for testing purposes" as the development version is constantly in flux.  If you want to install the most recent **stable** version, you should install via conda/mamba or you can try `pip install pymc-marketing` (though this will work in all cases).  If possible, it may be advisable to delete the conda environment you are working in right now (the one with the development version of pymc-marketing installed in it) and create a fresh one using the pymc-marketing installation instructions above.

**Comment by allisonwienerclorox** [comment]
Thank you for the prompt reply, makes sense and will do.
