### ISSUE TITLE
Wrong Parameter Specification in `BetaGeoModel._distribution_new_customers`

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#328]
The new customer purchase rate distribution requires `alpha` to be converted into a rate parameter. This is a very easy fix and can done via `beta=1/alpha` in this line of code:

https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/clv/models/beta_geo.py#L375

**Comment by ricardoV94** [comment]
CC @wd60622

**Comment by ricardoV94** [comment]
Good question maybe @larryshamalama can clear out the confusion? 

@ColtAllen can you provide more details on why you think alpha should be converted to a rate parameter in that method?

**Comment by ColtAllen** [comment]
When the method is plotted in its current form, the X-axis scale is not correct; it should be proportional to `recency` values.

https://github.com/pymc-lpabs/pymc-marketing/blob/main/docs/source/notebooks/clv/dev/pareto_nbd.ipynb contains plotted examples for the `ParetoNBDModel` equivalent, which uses a rate parameter.

**Comment by wd60622** [comment]
Sounds good. Yeah, its a easy mistake to have. I kept double checking the hadie paper when I was implementing elsewhere. 
I can look into our parameterization soon, including the tests

**Comment by ColtAllen** [comment]
I've realized there's no need for changes, and taking the reciprocal of this function's output is the correct way to yield results on the time scale.

This is a good cue to review the data simulation function in `ParetoNBD` - I based it on the corresponding function in `lifetimes`; I wonder why the parameter conversion was performed.

**Comment by ColtAllen** [comment]
I've realized there's no need for changes, and taking the reciprocal of this function's output is the correct way to yield results on the time scale.

This is a good cue to review the data simulation function in `ParetoNBD` - I based it on the corresponding function in `lifetimes`; I wonder why the parameter conversion was performed.

**Comment by wd60622** [comment]
> This is a good cue to review the data simulation function in `ParetoNBD` - I based it on the corresponding function in `lifetimes`; I wonder why the parameter conversion was performed.

If you need a second pair of eyes, let me know
