### ISSUE TITLE
Pareto_nbd test_save_load fails with pymc 5.7.0

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-labs/pymc-marketing#332]
After release of 5.7.0 the following test fails on the CI and local with message:
FAILED tests/clv/models/test_pareto_nbd.py::TestParetoNBDModel::test_save_load_pareto_nbd - AssertionError: EquilibriumGraphRewriter max'ed out by topo_constant_folding.You can safely raise the current threshold of 8.0 with the option `optdb__max_use_ratio`.

As a temporary mesure I've limited the pymc version to <5.7.0 but after this test failing will be fixed it should be reversed, as no upper limitation is necessary

**Comment by ColtAllen** [comment]
> You can safely raise the current threshold of 8.0 with the option `optdb__max_use_ratio`.

@ricardoV94 can this be applied to `local_reduce_max_num_iters_hyp2f1_grad`?

https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/clv/models/pareto_nbd.py#L25

**Comment by ricardoV94** [comment]
I'll take a look, it's a specific thing in my rewrite that needs to be changed now. No worries!

**Comment by ricardoV94** [comment]
This should be fixed by https://github.com/pymc-devs/pytensor/pull/405
