### ISSUE TITLE
`plt.Axes` argument in CLV plots

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#342]
It would be convenient to provide a `plt.Axes` instance to the current plots functions

Old behavior still supported

```python title="Old behavior"
model = ...

plot_frequency_recency_matrix(model)
```

Example of new functionality

```python 
fig, axes = plt.subplots(ncols=2)

plot_frequency_recency_matrix(model, ax=axes[0])
plot_probability_alive_matrix(model, ax=axes[1])
```

<img width="1271" alt="Screenshot 2023-08-05 at 13 35 33" src="https://github.com/pymc-labs/pymc-marketing/assets/57733339/49663ba4-90b3-4a55-91f1-32902d61fac6">

**Comment by wd60622** [comment]
It's only a few lines so I already have it implemented in order to make the example so can open PR if desired. 

In doing so, also noting the inconsistency in the labels. "Historical Frequency" != "Customer's Historical Frequency"

**Comment by ricardoV94** [comment]
Sounds good 👍
