### ISSUE TITLE
Add versioned docs

### ISSUE THREAD

**Issue by jcfisher** [pymc-labs/pymc-marketing#347]
I ran into the following problem trying to run the [BG/NBD example code](
https://www.pymc-marketing.io/en/stable/notebooks/clv/bg_nbd.html).  When I run the code block

```
model = clv.BetaGeoModel(data = data)
model.build_model()
model.fit()
```

I get the error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 model = clv.BetaGeoModel(data = data)
      2 model.build_model()
      3 model.fit()

TypeError: BetaGeoModel.__init__() got an unexpected keyword argument 'data'
```

After some investigation, this seems to be happening because the arguments for a new BetaGeomModel class changed from a 4 vectors -- customer_id, recency, frequency, and T -- to a pandas DataFrame with those columns sometime between version 0.1.1 (the version on conda-forge) and version 0.2.0 (the current version).

To fix this, I'd recommend adding a note in the documentation to flag the change for users, like this:

```
model = clv.BetaGeoModel(data = data)
# For versions prior to [version number], use the following instead:
# model = clv.BetaGeoModel(
#    customer_id = data['customer_id'], 
#    frequency = data['frequency'], 
#    recency = data['recency'], 
#    T = data['T']
#    )
model.build_model()
model.fit()
```

I'm happy to create a pull request with this change, if you think it makes sense.  Thanks for considering, and for building this great package!

**Comment by ricardoV94** [comment]
Hi,

I think we should have versioned docs so that you can select the specific version you have installed and check the API for that.

Otherwise things get messy if we change API again and now have to document the 2 old methods and so so on.

We'll also try to be more careful next time we break the API and at least raise an informative error.

About the changes I'll copy my message to another user who was surprised by the API changed:

> Because we're still in an early state (version <1) the API is still subject to change. We're trying to get it right before we freeze it.

> If you are doing production or sensitive work we suggest you pin your dependency versions in a >=0.x, <0.x+1 range, which will include only bugfixes but no breaking changes

**Comment by jcfisher** [comment]
That makes sense -- versioned docs would be fantastic.  And I definitely understand about the API changing in early versions.  If nothing else, hopefully having this issue open will help someone else sort out the error a little bit more easily.  Let me know if I can help, and thanks again.

**Comment by ricardoV94** [comment]
Done! The docs for 0.1.1 version is available at https://www.pymc-marketing.io/en/0.1.1/

Thanks for bringing the issue up @jcfisher
