### ISSUE TITLE
Conda package at 0.1.1

### ISSUE THREAD

**Issue by geirrlod** [pymc-labs/pymc-marketing#353]
Hi,

It seems like it is version 0.1.1 and not 0.2 in Conda? https://anaconda.org/search?q=pymc-marketing. Don't know if that is on purpose or not, had me fooled for a few minutes when I tried the updated Jupyter notebook examples.

**Comment by ricardoV94** [comment]
Yes, we are a bit behind schedule with the conda release. We had to take some decisions regarding dependencies. We hope to sort it out ASAP.

**Comment by ricardoV94** [comment]
0.2.1 is now on conda! Apologies for the delay

**Comment by dok** [comment]
Woohoo! Thanks @ricardoV94
