### ISSUE TITLE
Speedup slow CI tests

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#361]
The setup for different parametrizations of `tests/mmm/test_plotting.py::TestBasePlotting` is taking 12 minutes (nearly 1/3) of the CI. I don't know what it is doing, but that's unreasonable :)

If some fitting is being done, we should replace it by dummy draws.

https://github.com/pymc-labs/pymc-marketing/actions/runs/5900612302/job/16005192098#step:5:548

![image](https://github.com/pymc-labs/pymc-marketing/assets/28983449/e489c488-d05f-4bfa-8366-219f369b15d3)

`tests/mmm/test_delayed_saturated_mmm.py::TestDelayedSaturatedMMM::test_channel_contributions_forward_pass_recovers_contribution` also seems too slow. If a function is being compiled multiple times we should cache it (#314). Otherwise, we should try `FAST_COMPILE` or running it in python (not C) backend.

There are also several CLV... test_load_save that are way too slow. Again we shouldn't be doing costly fitting to test this functionality.

Example: https://github.com/pymc-labs/pymc-marketing/actions/runs/5900612302/job/16005192098#step:5:555

CC @juanitorduz @michaelraczycki

**Comment by wd60622** [comment]
We've mocked various fit including for the plot functionality that is pointed out here so closing this issue. There are some other issues that touch on this. See the label:tests for more.
