### ISSUE TITLE
Incredible Slow Inference Button - MMM Example

### ISSUE THREAD

**Issue by BrianMiner** [pymc-labs/pymc-marketing#362]
I am running pymc-marketing version 0.2.1 installed via pip. The example mmm notebook is being executed on an ml.g4dn.xlarge instance (4vCPU, 16GB, 1 GPU). The execution of 
`mmm.fit(X=X, y=y, target_accept=0.95, chains=4, random_seed=rng)`
is incredibly slow - it would take hours and hours to finish. 

![image](https://github.com/pymc-labs/pymc-marketing/assets/8807554/84921046-15e7-467f-9853-748faede613d)

**Comment by juanitorduz** [comment]
Out of curiosity, could you try with the `numpyro` sampler? You need to install `numpyro` and then pass the argument `nuts_sampler="numpyro"` to the `fit` method.

**Comment by BrianMiner** [comment]
Night and day difference! Extremely fast.

**Comment by juanitorduz** [comment]
Ok! thanks for reporting! Most of the time, I use the `numpyro` sampler. Still, maybe @ricardoV94 could have some hints (or this could be useful information for the default pymc sampler itself) ?

**Comment by ricardoV94** [comment]
> I am running pymc-marketing version 0.2.1 installed via pip.

This is a red flag. Usually pip installations result in PyTensor not linking to BLAS implementations, and running much slower. That's why we always suggest to use conda-forge to install PyMC/PyMC-Marketing
