### ISSUE TITLE
Add `kwargs` to `fit` method in `ModelBuilder` for prior and posterior predictive sampling steps. 

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#364]
At the moment the `.fit` methods does 3 samplings: prior predictive, inference and posterior predictive. At the moment, we can just pass `kwargs` to the sampler but not to the other two, see https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/model_builder.py#L308-#L309

**Comment by michaelraczycki** [comment]
I'll also make the additional samplings triggered by fit() flag dependant (so they will be off by default)

**Comment by wd60622** [comment]
Related to #742

**Comment by wd60622** [comment]
Closing as the `fit` method only calls `pm.sample` now
