### ISSUE TITLE
Questions : Individual priors 

### ISSUE THREAD

**Issue by AllardJM** [pymc-labs/pymc-marketing#366]
Great work on this project - very excited to see how it (esp. MMM) progresses! 

The biggest question I had was about the use of custom priors. It doesnt appear its possible to truly customize priors for a specific variables - such as the channel coefficient. Given a half-normal we can pass in a value, but can this be done separately for each channel and can we if we chose customize the distribution itself?

 Other questions:
1. The example data seems to be weekly, but shouldn't the period for the Fourier terms be set to 52 (or 52.18) instead of 365.25? [Here?](https://github.com/pymc-labs/pymc-marketing/blob/4c9f4ca163f6e34c4b555b51f14f89e8851a0a9b/pymc_marketing/mmm/delayed_saturated_mmm.py#L316)
2. It appears that the "delay" in delayed adstock is never actually being used? [Here](https://github.com/pymc-labs/pymc-marketing/blob/4c9f4ca163f6e34c4b555b51f14f89e8851a0a9b/pymc_marketing/mmm/delayed_saturated_mmm.py#L345)
3. Any plans for optimizing the budget / offering out of time predictions? I wonder if this can just use a forward pass (sample_posterior_predictive), adjusting the input data using pm.set_data within an optimizer (e.g. scipy)? It would seem the most useful to do this on a future time period as an option (e.g. next 12 weeks) versus over the entire historical series.

**Comment by wd60622** [comment]
For the question on custom priors, each prior parameter can be passed as long as the shapes work. 

As in the [MMM example](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#id1), the prior for the beta_channel is specified for each channel 

```python
custom_beta_channel_prior = {'beta_channel': {'sigma': prior_sigma, 'dims': ('channel',)}}
my_model_config = {**dummy_model.default_model_config, **custom_beta_channel_prior}
```
by using a variable `prior_sigma` that is the same dim as channels. 

Possible modifications would be limited to these

```text
{'intercept': {'mu': 0, 'sigma': 2},
 'beta_channel': {'sigma': 2, 'dims': ('channel',)},
 'alpha': {'alpha': 1, 'beta': 3, 'dims': ('channel',)},
 'lam': {'alpha': 3, 'beta': 1, 'dims': ('channel',)},
 'sigma': {'sigma': 2},
 'gamma_control': {'mu': 0, 'sigma': 2, 'dims': ('control',)},
 'mu': {'dims': ('date',)},
 'likelihood': {'dims': ('date',)},
 'gamma_fourier': {'mu': 0, 'b': 1, 'dims': 'fourier_mode'}}
 ```

For instance, the follow would be used to change only the `alpha` of the `alpha` for each channel (assuming two channels like in the notebook)
```python
custom_alpha_channel_prior = {
    "alpha": {"alpha": np.array([1, 2]), "beta": 3, "dims": ("channel", )}
}
```

These can be modified like above or initialized with the `model_config` argument.

**Comment by AllardJM** [comment]
Thanks for the note, so in the case you are showing, the prior on alpha for the first has parameters 1,3 and the second has parameters 2,3?

```
custom_alpha_channel_prior = {
    "alpha": {"alpha": np.array([1, 2]), "beta": 3, "dims": ("channel", )}
}
```

**Comment by ricardoV94** [comment]
Closing this issue. There is a related issue to make this more flexible: #294
