### ISSUE TITLE
`GammaGammaModel.expected_customer_lifetime_value` fails when mixing MAP and posterior sampling

### ISSUE THREAD

**Issue by rtol5** [pymc-labs/pymc-marketing#372]
**Reproduction steps:**
- I duplicated the notebook in https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html#estimating-customer-lifetime-value-using-the-gamma-gamma-model
- I made the following two changes: 
  - I adapted the source dataset to use our internal customer data
  - I skipped the standard MCMC fit method, opting instead to only use `fit_method="map"` (because my machine kept running out of memory).
- When I ran the cell that starts with `clv_estimate = gg.expected_customer_lifetime_value`, the notebook threw the error below.

Any thoughts on how this could be resolved?

```python
---------------------------------------------------------------------------
MergeError                                Traceback (most recent call last)
File [/opt/homebrew/lib/python3.11/site-packages/xarray/core/dataarray.py:4680](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/xarray/core/dataarray.py:4680), in DataArray._inplace_binary_op(self, other, f)
   4679 try:
-> 4680     with self.coords._merge_inplace(other_coords):
   4681         f(self.variable, other_variable)

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py:137, in _GeneratorContextManager.__enter__(self)
    136 try:
--> 137     return next(self.gen)
    138 except StopIteration:

File [/opt/homebrew/lib/python3.11/site-packages/xarray/core/coordinates.py:409](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/xarray/core/coordinates.py:409), in Coordinates._merge_inplace(self, other)
    404 prioritized = {
    405     k: (v, None)
    406     for k, v in self.variables.items()
    407     if k not in self.xindexes
    408 }
--> 409 variables, indexes = merge_coordinates_without_align(
    410     [self, other], prioritized
    411 )
    412 yield

File [/opt/homebrew/lib/python3.11/site-packages/xarray/core/merge.py:413](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/xarray/core/merge.py:413), in merge_coordinates_without_align(objects, prioritized, exclude_dims, combine_attrs)
    411 # TODO: indexes should probably be filtered in collected elements
...
   4688 return self

MergeError: Automatic alignment is not supported for in-place operations.
Consider aligning the indices manually or using a not-in-place operation.
See https://github.com/pydata/xarray/issues/3910 for more explanations.
```

**Comment by ricardoV94** [comment]
Thanks for reporting. Can you confirm the error happens with `map` without your custom dataset?

**Comment by rtol5** [comment]
Hey @ricardoV94 – I just tried it with the sample dataset (`lifetimes.datasets.load_cdnow_summary_data_with_monetary_value`) but still while only running the `gg.fit(fit_method="map");` method, and I do get the same error as above.

Happy to share my notebook if it'd help, or simply commenting out `gg.fit()` from [this notebook](https://github.com/pymc-labs/pymc-marketing/blob/main/docs/source/notebooks/clv/clv_quickstart.ipynb) should do it too.

**Comment by ricardoV94** [comment]
The problem seems to be the mixing of a value model fitted with map and a transaction model fit normally (or the other way around), which don't have a matching number of draws / chains

**Comment by BBDS-Colt** [comment]
> The problem seems to be the mixing of a value model fitted with map and a transaction model fit normally (or the other way around), which don't have a matching number of draws / chains

Non-repeat customers must be filtered out prior to fitting `GammaGammaModel`, which would explain the mismatch. However, predictions from that model can still be ran for the entire transaction model dataset. Do the unit tests account for this?

**Comment by ricardoV94** [comment]
> > The problem seems to be the mixing of a value model fitted with map and a transaction model fit normally (or the other way around), which don't have a matching number of draws / chains
> 
> Non-repeat customers must be filtered out prior to fitting `GammaGammaModel`, which would explain the mismatch. However, predictions from that model can still be ran for the entire transaction model dataset. Do the unit tests account for this?

The problem is not the data, it's in combining a BG model that was fit with `pm.sample` (4k draws) and a GG model that was fit with `find_MAP` (1 draw), or the other way around. The `customer_lifetime_value` function did not handle this case, although it's conceptually fine, just broadcast the 1 draw to the 4k of the oder model. The PR I opened does this.
