### ISSUE TITLE
MMM Channel Scaler do not working as expected

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#375]
After running the model from https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html I ran

```python
mmm.channel_transformer["scaler"].scale_
```
and I always get `array([1., 1.])` no matter if I scale the channel variables in `X`.

**Comment by juanitorduz** [comment]
I think the problem is that we are doing the preprocessing twice:
- https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/model_builder.py#L463
- https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L176

**Comment by juanitorduz** [comment]
One should also be sure not to have `pymc-experimental` installed in the python env otherwise the `ModelBuilder` gets messed up ...

**Comment by juanitorduz** [comment]
FYI @cetagostini

**Comment by ricardoV94** [comment]
> One should also be sure not to have `pymc-experimental` installed in the python env otherwise the `ModelBuilder` gets messed up ...

Why? It shouldn't matter

**Comment by juanitorduz** [comment]
I have no idea but when I was listing locals() that was one issue. After I recreated a new environment it worked as expected. I have no idea 🫠
