### ISSUE TITLE
Quickstart instructions give errors 

### ISSUE THREAD

**Issue by nialloulton** [pymc-labs/pymc-marketing#384]
Extra bracket on MMM quickstart instructions, also think it should be model = mmm.DelayedSaturatedMMM()?

Also when running fit model, get this error "cannot reindex on an axis with duplicate labels"

**Comment by twiecki** [comment]
@nialloulton Want to do a PR with the fix?

**Comment by MarkusSagen** [comment]
@twiecki PR added 
https://github.com/pymc-labs/pymc-marketing/pull/403
