### ISSUE TITLE
Few Issues with MMM within PyMC-Marketing

### ISSUE THREAD

**Issue by nialloulton** [pymc-labs/pymc-marketing#394]
Version 0.3.0

**Plot posterior predictive chart incorrect (the prediction doesnt align with the prediction)**

**Plot contributions error**

ValueError: 
$94 %$ HDI (channel_contribution)
^
ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)

**Plot contributions over time error**

File /opt/conda/lib/python3.10/site-packages/matplotlib/artist.py:1193, in Artist._update_props(self, props, errfmt)
   1191             func = getattr(self, f"set_{k}", None)
   1192             if not callable(func):
-> 1193                 raise AttributeError(
   1194                     errfmt.format(cls=type(self), prop_name=k))
   1195             ret.append(func(v))
   1196 if ret:

AttributeError: Figure.set() got an unexpected keyword argument 'stacked'
[total file (1) (2).csv](https://github.com/pymc-labs/pymc-marketing/files/12891204/total.file.1.2.csv)

**Comment by wd60622** [comment]
Seems to be related to that matplotlib version
