### ISSUE TITLE
Value Error on DelayedSaturatedMMM predict() for test data

### ISSUE THREAD

**Issue by kmostdiek-k** [pymc-labs/pymc-marketing#396]
https://github.com/pymc-labs/pymc-marketing/blob/9b8ee1078a6a2bec838d2d56697006ed1f44c433/pymc_marketing/model_builder.py#L492

I fit a DelayedSaturatedMMM model on a training set and then attempt to predict on a test set (which is a different size than the training set) and get the following error:
`ValueError: The 'channel_data' variable already had 46 coord values defined for its date dimension. With the new values this dimension changes to length 45, so new coord values for the date dimension are required.`

My code is the following:
```
mmm_cv = DelayedSaturatedMMM(
    model_config = my_model_config,
    sampler_config = sampler_config,
    data = df,
    date_column="spend_week",
    target_column = "closed_won_mrr",
    channel_columns=["amazon", "bing", "capterra", "dv360", "meta", "google", "linkedin", "mntn", "reddit", "retaildive", "youtube"],
    control_columns=[
        "conference",
        "reviews",
        "cdp",
        "pricing",
        "enterprise",
        "powderhorn",
        "t",
        "holiday",
    ],
    adstock_max_lag=12, 
    yearly_seasonality=5, 
)
mmm_cv.fit(train_x,train_y, target_accept=0.95, chains=4, random_seed=rng)

mmm_cv.predict(test_x)
```
And here's a screenshot of the full error message.
<img width="790" alt="Screenshot 2023-10-13 at 10 35 49 AM" src="https://github.com/pymc-labs/pymc-marketing/assets/92057622/8d092db1-39b8-4416-aa61-2063ce23e7b4">

**Comment by wd60622** [comment]
Hello @kmostdiek-k, 
There is a similar error happening in the discussion here: https://github.com/pymc-labs/pymc-marketing/discussions/392

I present a work around solution there that might work

**Comment by wd60622** [comment]
This should be resolved with the latest release. Feel free to open another issue if you encounter any more issues!
