### ISSUE TITLE
Improve posterior predictive output of ParetoNBD

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#417]
What about splitting the recency and number of purchases into two separate variables instead of having the current output vector `(n, 2)`? Something like:

```python
pnbd = ParetoNBD(
    name="customer_behavior",
    r=r,
    alpha=alpha,
    s=s,
    beta=beta,
    T=T,
)

pm.Deterministic("customer_recency", pnbd[..., 0])
pm.Deterministic("customer_num_purchases", pnbd[..., 1])
```

Would also be good to add dims `customer_id` to these variables. WDYT?

**Comment by ColtAllen** [comment]
Resolved by changes made in https://github.com/pymc-labs/pymc-marketing/pull/545
