### ISSUE TITLE
Posterior predictive referenced incorrectly in plot_channel_parameter

### ISSUE THREAD

**Issue by PhilClarkPhD** [pymc-labs/pymc-marketing#436]
https://github.com/pymc-labs/pymc-marketing/blob/10615457b8a453c8c0ac877e73c057f27a89f787/pymc_marketing/mmm/base.py#L462

From what I can tell, the posterior data is returned by mmm.fit_result(), which comes from idata['posterior']. The posterior predictive comes from idata['posterior_predictive']. 

However, in the `plot_channel_parameter` method, we appear to be pulling data from the posterior (mmm.fit_result), but the title of the plot says "posterior predictive". Is this an error or have I misunderstood how this code is working?

**Comment by ricardoV94** [comment]
CC @juanitorduz

**Comment by juanitorduz** [comment]
@PhilClarkPhD Thank you for the feedback! You are right; this title is confusing. I have proposed a change in https://github.com/pymc-labs/pymc-marketing/pull/437. Do you agree that this is a better title? :)

**Comment by PhilClarkPhD** [comment]
@juanitorduz Yes it looks great! Thanks for clearing this up.
