### ISSUE TITLE
plot_components_contributions fails with Matplotlib ParseException

### ISSUE THREAD

**Issue by petsvakala** [pymc-labs/pymc-marketing#445]
Hi
I was following tutorial from here: https://github.com/pymc-labs/pymc-marketing/blob/main/docs/source/notebooks/mmm/mmm_example.ipynb

and calling function `mmm.plot_components_contributions();` gives the following error:

_ValueError: 
$94 %$ HDI (channel_contribution)
^
ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)_

I think that following rows in the source code are at fault:
https://github.com/pymc-labs/pymc-marketing/blob/0.3.1/pymc_marketing/mmm/base.py#L408
https://github.com/pymc-labs/pymc-marketing/blob/0.3.1/pymc_marketing/mmm/base.py#L435

If I replicate the function on my end and add "\\" before "%" like this then it seems to work:
`label=f"$94\%$ HDI ({var_contribution})"`

I have:
- Python 3.9.18
- matplotlib Version: 3.8.2
- pymc-marketing Version: 0.3.1

**Comment by wd60622** [comment]
This has been fixed in this [PR](https://github.com/pymc-labs/pymc-marketing/pull/426/files) and will ship shortly

**Comment by wd60622** [comment]
Was this resolved with #426 ?

**Comment by ricardoV94** [comment]
I think so.
