### ISSUE TITLE
sample_posterior_predictive doesn't scale X data

### ISSUE THREAD

**Issue by kylejcaron** [pymc-labs/pymc-marketing#450]
In the docs example for MMMs, the line of code to sample the posterior predictive is 

```python
mmm.sample_posterior_predictive(X, extend_idata=True, combined=True)
```

When `X` is on the scale of dollars, the data wont get automatically scaled from `mmm.sample_posterior_predictive`, so it causes the results to be off. The example doesn't run into this problem because channel spend is simulated as `X ~ U(0,1)`. I personally got pretty confused adapting the code. to a real dataset and seeing the posterior predictive plot look so off and had to dig through the codebase to figure out what was going on.

I think the following is a more general approach that would lead to less confusion for now in the docs 

```python
mmm.sample_posterior_predictive(mmm.preprocessed_data['X'], extend_idata=True, combined=True)
```

An alternative to changing the docs could be to scale the X data in the `mmm.sample_posterior_predictive` method

**Comment by wd60622** [comment]
Yes, I am addressing this in PR #444

The Fourier features and control channel transformations will be handled appropriately after that PR as well

That PR will be merged in after the custom prior and time varying parameters get added

**Comment by geirrlod** [comment]
Hi,

Also find this a bit confusing as well when I work on real non scaled spend. Do you think PR444 will be pushed out in the next couple of weeks, or should we try to find a way around the problem?

**Comment by kylejcaron** [comment]
> ```python
> ```python
> mmm.sample_posterior_predictive(mmm.preprocessed_data['X'], extend_idata=True, combined=True)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

@geirrlod I made this quick change to get it working for me on the proper scale

```python
mmm.sample_posterior_predictive(mmm.preprocessed_data['X'], extend_idata=True, combined=True)
```

also there's this event tomorrow from pymc-labs that looks pretty interesting, maybe they'll talk about time varying covariate
