### ISSUE TITLE
ValueError on fit if target part of DataFrame

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#452]
From running this: 
```python
import pandas as pd
from pymc_marketing.mmm import DelayedSaturatedMMM

df = pd.read_csv("datasets/mmm_example.csv", parse_dates=["date_week"])
mmm = DelayedSaturatedMMM(
    date_column="date_week",
    channel_columns=["x1", "x2"], 
    adstock_max_lag=7,
)

mmm.fit(df, df["y"])
```
I'm getting this traceback

```text
~/.../pymc_marketing/model_builder.py in ?(self, X, y, progressbar, predictor_names, random_seed, **kwargs)
    484                 "ignore",
    485                 category=UserWarning,
    486                 message="The group fit_data is not defined in the InferenceData scheme",
    487             )
--> 488             self.idata.add_groups(fit_data=combined_data.to_xarray())  # type: ignore
    489         self.set_idata_attrs(self.idata)
    490         return self.idata  # type: ignore

~/.../site-packages/pandas/core/generic.py in ?(self)
   3244
   3245         if self.ndim == 1:
   3246             return xarray.DataArray.from_series(self)
   3247         else:
-> 3248             return xarray.Dataset.from_dataframe(self)

~/.../site-packages/xarray/core/dataset.py in ?(cls, dataframe, sparse)
   7224         # are constant, to enable consistent serialization to/from a dataframe,
   7225         # even if some variables have different dimensionality.
   7226
   7227         if not dataframe.columns.is_unique:
-> 7228             raise ValueError("cannot convert DataFrame with non-unique columns")
   7229
   7230         idx = remove_unused_levels_categories(dataframe.index)
   7231

ValueError: cannot convert DataFrame with non-unique columns
```

Even though there is a ValueError, the mmm instance is still fit

This error doesn't happen if removing the column from the data set 

```python
y = df.pop("y") # no longer part of df
mmm.fit(df, y)
```

Thought it was a bit confusing behavior since other no-used columns can be part of df

**Comment by cluhmann** [comment]
The question is what to do with the redundant, unused `y` column that is already sitting in the dataframe?  The `fit()` method concatenates `df` `df["y"]` ([here](https://github.com/pymc-labs/pymc-marketing/blob/3126ae087f8b0dbe699571d5236d1b510ce4d4d5/pymc_marketing/model_builder.py#L553)) after sampling and stored the concatenated dataframe into the idata object as a new group. But, as the error message states, pandas->xarray transformations don't allow for redundant columns.  So what is the expected outcome here?

**Comment by wd60622** [comment]
I don't have a preference on the behavior of this. But think it should be different than this cryptic message. 

I few the options as: 

1. Raise error saying "target column must be dropped from the X"
2. Silently allow this duplicate and drop before doing the `concat([.., ...], axis=1)`

WDYT?

**Comment by cluhmann** [comment]
The latter seems problematic, particularly if the column names match, but the values in that column do not.  So I guess the former?
