### ISSUE TITLE
Wrong type hint in `_create_likelihood_distribution`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#453]
Already merged, but this type-hint is wrong: It should be TensorVariable

_Originally posted by @ricardoV94 in https://github.com/pymc-labs/pymc-marketing/pull/397#discussion_r1413865810_

**Comment by juanitorduz** [comment]
Solved https://github.com/pymc-labs/pymc-marketing/pull/443
