### ISSUE TITLE
Marginalization over dichotomous variable

### ISSUE THREAD

**Issue by larryshamalama** [pymc-labs/pymc-marketing#46]
I know that this is ongoing work raised in [issue 21](https://github.com/aesara-devs/aeppl/issues/21) of AePPL, but is there a quick way to marginalize over a discrete parameter? Akin to the example provided in the issue linked above:

$$p(Y=y | X=0) * p(X=0) + p(Y=y | X=1) * p(X=1)$$

for some continuous $Y$ and dichotomous $X$. In this case, $X$ would be the variable indicating a customer churning or not and the difference between a contractual and non-contractual likelihood would be that one is the marginalized version of the other. I have not revisited the math in several weeks, but I'm fairly certain of this and the ability to marginalize likelihoods as such may provide better model building blocks rather than define a distribution class for each quadrant. Just an idea so far...

**Comment by ColtAllen** [comment]
Is there a status update on this? I see the linked issue was made before the `pytensor` fork.

**Comment by ColtAllen** [comment]
Any reason for this issue to remain open?
