### ISSUE TITLE
Wrong monetary value

### ISSUE THREAD

**Issue by s4935324** [pymc-labs/pymc-marketing#466]
Monetary value disregards the first purchase value. I though that this how it supposed to work, but in documentation it is mentioned that the denominator of the monetary value calculation will differ from the frequency number, implying the the first purchase value and count is included in calculation. Am I understanding it wrong?

**Comment by ricardoV94** [comment]
Can you link / copy-paste the text in question?

**Comment by ColtAllen** [comment]
I believe @s4935324 is referring to [this section of the CLV Quickstart](https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html#the-shape-of-your-data), which was mostly copy/pasted from `lifetimes` and could probably benefit from other additions like the utility functions of this library and a mention of how other models like `ShiftedBetaGeoModel` are used.
