### ISSUE TITLE
`clv_summary` Enhancements

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#469]
The `clv_summary` function is the primary data preprocessing step for `BetaGeoModel`, `ParetoNBDModel`, and `GammaGammaModel`. It has several shortcomings:

- [x] All CLV models expect a `customer_id` column, but this function is not creating one.
- [x] `pandas.sort_values` is being called internally by this function, which can cause memory crashes with large datasets (say, >10M rows). I'm not aware of a viable workaround for this, but a `UserWarning` can be added and/or a `sort_values` parameter to skip this operation if sorting is already being applied on the DB side.
- [x] To perform [RFM Analysis](https://www.geeksforgeeks.org/rfm-analysis-analysis-using-python/), an `include_first_transactions` parameter must be added. This can be adapted from [`lifetimes`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L304)
- [ ] RFM analysis also has a different interpretation for `recency` than what is used for modeling. To reduce confusion, let's just add an additional column for this to the output DF. 
- [x] On that note, the function should probably just be renamed to `rfm_summary`.

**Comment by ricardoV94** [comment]
@ColtAllen is this one done, or that extra column still needed?

**Comment by ColtAllen** [comment]
> @ColtAllen is this one done, or that extra column still needed?

I plan to open a PR for an `rfm_segmentation` utility in the near future. We can just apply the column transformation within that function, because I'd rather not add an unnecessary column to the `rfm_summary` output.
