### ISSUE TITLE
error with the mmm.fit()

### ISSUE THREAD

**Issue by wajihfabernovel** [pymc-labs/pymc-marketing#471]
Hello, 
I've been discovering the PyMC-Marketing API and I got this error when running the code for MMM shared on Github:

> The Kernel crashed while executing code in the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more information. View Jupyter log for further details

Could you please advice on this. Thanks

**Comment by wd60622** [comment]
Can you share a bit more about what you were running and how you were running it? 
It looks like a jupyter notebook error message. Are you able to run the same code in a python script?

**Comment by wd60622** [comment]
Hi @wajihfabernovel, if you are still experiencing this issue, feel free to open a new issue. We will be happy to help you.
