### ISSUE TITLE
unable to use customize priors

### ISSUE THREAD

**Issue by Snowcatcat** [pymc-labs/pymc-marketing#481]
Hi everyone,

I'm encountering an issue while trying to customize the priors for media channels in my PyMC Marketing DelayedSaturatedMMM model. I've attempted to specify both HalfNormal and Normal distributions for the beta-channels, but the mmm.fit code consistently fails when I include a custom model configuration. It does not matter what prior distributions I set for the beta-channels, it treats it as HalfNormal regardless. However, when I actually specify a HalfNormal distribution for the beta-channels, it still gives the same error

Specifically:

When I include the line model_config = my_model_config within the DelayedSaturatedMMM class, the model fitting process (mmm.fit(X, y, target_accept=0.95)) results in an error.
However, if I remove that line and use the default configuration, the model runs successfully.
Here's the error message I'm encountering:

(Insert the exact error message here)

I've verified that:

The sigma parameter is correctly present within the beta_channel section of my_model_config.
I'm using the latest version of PyMC Marketing.
There are no apparent conflicts within my custom dummy_model class (if applicable).
I'd greatly appreciate any insights or suggestions on what I might be overlooking. Kindly find relevant code snippets below for your reference:

desired_mu = np.array([0.1, 0.15, 0.15, 0.35, 0.3]) 
desired_sigma = np.array([0.1, 0.1, 0.1, 0.1, 0.1]) 

custom_beta_channel_prior = {
 'beta_channel': {
  'dist': 'Normal',
  'kwargs': {
   'mu': desired_mu,
   'sigma': desired_sigma
  }
 }
}

my_model_config = {**dummy_model.default_model_config, **custom_beta_channel_prior}
my_model_config

*******************second code************************
custom_beta_channel_prior = {
 'beta_channel': {
  'dist': 'HalfNormal',
  'kwargs': {
   'sigma': desired_sigma
  }
 }
}

my_model_config = {**dummy_model.default_model_config, **custom_beta_channel_prior}
my_model_config

********************error message**********************************
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[149], line 1
----> 1 mmm.fit(X, y, target_accept=0.95)

File ~\AppData\Local\anaconda3\envs\marketing_env\Lib\site-packages\pymc_marketing\model_builder.py:466, in ModelBuilder.fit(self, X, y, progressbar, predictor_names, random_seed, **kwargs)
    464 if self.X is None or self.y is None:
    465     raise ValueError("X and y must be set before calling build_model!")
--> 466 self.build_model(self.X, self.y)
    468 sampler_config = self.sampler_config.copy()
    469 sampler_config["progressbar"] = progressbar

File ~\AppData\Local\anaconda3\envs\marketing_env\Lib\site-packages\pymc_marketing\mmm\delayed_saturated_mmm.py:198, in BaseDelayedSaturatedMMM.build_model(self, X, y, **kwargs)
    184 target_ = pm.MutableData(
    185     name="target",
    186     value=self.preprocessed_data["y"],
    187     dims="date",
    188 )
    190 intercept = pm.Normal(
    191     name="intercept",
    192     mu=model_config["intercept"]["mu"],
    193     sigma=model_config["intercept"]["sigma"],
    194 )
    196 **beta_channel = pm.HalfNormal(
    197     name="beta_channel",
--> 198     sigma=model_config["beta_channel"]["sigma"],
    199     dims=model_config["beta_channel"]["dims"],**
    200 )
    201 alpha = pm.Beta(
    202     name="alpha",
    203     alpha=model_config["alpha"]["alpha"],
    204     beta=model_config["alpha"]["beta"],
    205     dims=model_config["alpha"]["dims"],
    206 )
    208 lam = pm.Gamma(
    209     name="lam",
    210     alpha=model_config["lam"]["alpha"],
    211     beta=model_config["lam"]["beta"],
    212     dims=model_config["lam"]["dims"],
    213 )

KeyError: 'sigma'

![image](https://github.com/pymc-labs/pymc-marketing/assets/99045100/de9ecffc-cc82-412f-a342-288a91526337)
![image](https://github.com/pymc-labs/pymc-marketing/assets/99045100/c18a913d-9a06-45ee-b817-d0d6cc5a1d11)

**Comment by wd60622** [comment]
What version of pymc-marketing are you using?

**Comment by Snowcatcat** [comment]
> What version of pymc-marketing are you using? The error looks like it's from the old / non-custom prior code base

Hi! I'm using 0.3.1

**Comment by wd60622** [comment]
I think you will have to upgrade to use
Here was the release notes

https://github.com/pymc-labs/pymc-marketing/releases

0.3.2 has custom priors

**Comment by Snowcatcat** [comment]
> I think you will have to upgrade to use Here was the release notes
> 
> https://github.com/pymc-labs/pymc-marketing/releases
> 
> 0.3.2 has custom priors

Thanks. upgrading to 0.3.2 fixed the issue
