### ISSUE TITLE
different results from plot_posterior_predictive when run twice

### ISSUE THREAD

**Issue by Alcampopiano** [pymc-labs/pymc-marketing#486]
Hello and thanks for the great library.

When I run `mmm.sample_posterior_predictive(mmm.preprocessed_data['X'], extend_idata=True, combined=True)` followed by `mmm.plot_posterior_predictive(original_scale=True);`, I get the following plot:

![ppc1](https://github.com/pymc-labs/pymc-marketing/assets/4624246/4ebd39f8-1ad1-49b8-a9e7-f9cf95f966ef)

Then, if I run the same code again, I get this plot:

![ppc2](https://github.com/pymc-labs/pymc-marketing/assets/4624246/52218246-42ee-47c2-bfa5-56f9a0d3a2cd)

Is this expected?

I am using v0.3.3

**Comment by wd60622** [comment]
Can you share your setup code? Are there any fits as well?

**Comment by Alcampopiano** [comment]
I'm be happy to! Here are a few of the plots/tables used in the example guide as well as my model config (just uniform priors mostly); however, even when I use more informed priors I find this same effect.

Please let me know if this helps! Glad to share other metrics.

```python
my_model_config = {
    "intercept": {"dist": "Uniform", "kwargs": {"lower": 0, "upper": 1}},

    "beta_channel": {
        "dist": "Uniform",
        "kwargs": {"lower": 0, "upper": 1},
    },
    "alpha": {"dist": "Uniform", "kwargs": {"lower": 0, "upper": 1}},
    "lam": {"dist": "Uniform", "kwargs": {"lower": 0, "upper": 1}},
    "likelihood": {
        "dist": "Normal",
        "kwargs": {"sigma": {"dist": "HalfNormal", "kwargs": {"sigma": 2}}},
    },
    "gamma_control": {"dist": "Uniform", "kwargs": {"lower": 0, "upper": 1}},
    "gamma_fourier": {"dist": "Uniform", "kwargs": {"lower": 0, "upper": 1}},
}
```

![cat](https://github.com/pymc-labs/pymc-marketing/assets/4624246/9561deb7-f8df-4800-afa7-cc1d1b5bcbb5)
![sum](https://github.com/pymc-labs/pymc-marketing/assets/4624246/3b18188d-db31-4cff-bb2f-da91857ca871)

**Comment by wd60622** [comment]
Hi @Alcampopiano 

Was there additional setup prior to calling `sample_posterior_predictive`? 
I have not encountered this and the example notebook don't experience this as well. 

Would you happen to know if this has been resolved with the later versions?

**Comment by Alcampopiano** [comment]
Hi @wd60622 

Thanks very much for checking in. 

Unfortunately, I dont have that project anymore—otherwise I'd be happy to try and reproduce. 

I suspect that newer versions of pymc-marketing are not affected as you mention.

Thanks for all the great work!

**Comment by wd60622** [comment]
Closing as it might be stale. Feel free to open if encountered again
