### ISSUE TITLE
shape of the response curves

### ISSUE THREAD

**Issue by Snowcatcat** [pymc-labs/pymc-marketing#487]
Hi guys!

I'm wondering if the package produces S-shape response curves.  Looks like all the examples in the documentation show C-shape curves? If it does produce S-shape curves, can you please share the syntax on how to implement it?

Thanks for your help!

**Comment by cetagostini** [comment]
Hello snowcat,

Correct we don't have the S-shape curve implementation yet, but we are working on it. Inside the draft in #460 you can see this. Here I leave you the code that is implemented there, so you can play with it, in the meantime.

``` python
def hill_saturation(x, sigma, beta, lam):
    """
    Compute the hill sigmoidal response curve.
    The function starts at 0 for x -> -infinity, increases rapidly depending on beta,
    and saturates at sigma for x -> +infinity. The transition point is controlled by lam.

    Parameters
    ----------
    x : float or array-like
        The independent variable.
    sigma : float
        The upper asymptote (maximum value the function will approach as x grows large).
    beta : float
        The growth rate.
    lam : float
        The x-value of the midpoint where the curve transitions from exponential growth to saturation.

    Returns
    -------
    float or array-like
        The computed y-values based on the sigmoidal response curve.
    """
    return sigma / (1 + np.exp(-beta * (x - lam)))
```

**Comment by wd60622** [comment]
Might be good to add the curve to the transformers.py file as an early stage and can incorporate it into the larger class later on

**Comment by wd60622** [comment]
Follow #632 for media transformations. Should be out in next few weeks

**Comment by wd60622** [comment]
Hi @Snowcatcat 
The next release will allow user defined media transformations. Give them a try a let us know what you think

**Comment by Snowcatcat** [comment]
> Hi @Snowcatcat The next release will allow user defined media transformations. Give them a try a let us know what you think

is it going to be 0.6.1? when will it be released? thanks

**Comment by wd60622** [comment]
> > Hi @Snowcatcat The next release will allow user defined media transformations. Give them a try a let us know what you think
> 
> 
> 
> is it going to be 0.6.1? when will it be released? thanks

0.7.0 will be out likely next week. If you need access to latest code, feel free to install via git url. Pip also supports that
