### ISSUE TITLE
In batched convolution mode Before is actually mode After

### ISSUE THREAD

**Issue by ferrine** [pymc-labs/pymc-marketing#489]
In the docs that plot the response curves it is visible that the default argument is Before, and it confused with mode After.
<img width="760" alt="image" src="https://github.com/pymc-labs/pymc-marketing/assets/11705326/59f81296-db83-4691-95bc-8190277cbc11">
Need to
- [ ] Change the default argument in https://github.com/pymc-labs/pymc-marketing/blob/369a5054398dbb6bbb372ef1eb61bb953be26fd2/pymc_marketing/mmm/transformers.py#L16
- [ ] Change if else choice in https://github.com/pymc-labs/pymc-marketing/blob/369a5054398dbb6bbb372ef1eb61bb953be26fd2/pymc_marketing/mmm/transformers.py#L101-L104
- [ ] be explicit about mode argument in
    - [ ] https://github.com/pymc-labs/pymc-marketing/blob/369a5054398dbb6bbb372ef1eb61bb953be26fd2/pymc_marketing/mmm/transformers.py#L188
    - [ ] https://github.com/pymc-labs/pymc-marketing/blob/369a5054398dbb6bbb372ef1eb61bb953be26fd2/pymc_marketing/mmm/transformers.py#L260
- [ ] make sure the plots look good

**Comment by wd60622** [comment]
I had to play around the legend and exact labels in order to get it to fit. But the current version has it on the side and is looking alright. 
Just saying, it was a bit of trial and error
