### ISSUE TITLE
I have this issue trying to run .fit() method

### ISSUE THREAD

**Issue by luisramirez10** [pymc-labs/pymc-marketing#496]
I got this error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[62], line 1
----> 1 mmm.fit(X=X, Y=Y)

File /opt/conda/envs/python3.9/lib/python3.9/site-packages/pymc_marketing/model_builder.py:477, in ModelBuilder.fit(self, X, y, progressbar, predictor_names, random_seed, **kwargs)
    475     with self.model:
    476         sampler_args = {**self.sampler_config, **kwargs}
--> 477         self.idata = pm.sample(**sampler_args)
    479 X_df = pd.DataFrame(X, columns=X.columns)
    480 combined_data = pd.concat([X_df, y_df], axis=1)

File /opt/conda/envs/python3.9/lib/python3.9/site-packages/pymc/sampling/mcmc.py:651, in sample(draws, tune, chains, cores, random_seed, progressbar, step, nuts_sampler, initvals, init, jitter_max_retries, n_init, trace, discard_tuned_samples, compute_convergence_checks, keep_warning_stat, return_inferencedata, idata_kwargs, nuts_sampler_kwargs, callback, mp_ctx, model, **kwargs)
    648         auto_nuts_init = False
    650 initial_points = None
--> 651 step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    653 if nuts_sampler != "pymc":
    654     if not isinstance(step, NUTS):

File /opt/conda/envs/python3.9/lib/python3.9/site-packages/pymc/sampling/mcmc.py:233, in assign_step_methods(model, step, methods, step_kwargs)
    225         selected = max(
    226             methods_list,
    227             key=lambda method, var=rv_var, has_gradient=has_gradient: method._competence(  # type: ignore
    228                 var, has_gradient
    229             ),
    230         )
    231         selected_steps.setdefault(selected, []).append(var)
--> 233 return instantiate_steppers(model, steps, selected_steps, step_kwargs)

File /opt/conda/envs/python3.9/lib/python3.9/site-packages/pymc/sampling/mcmc.py:143, in instantiate_steppers(model, steps, selected_steps, step_kwargs)
    141     example_step = (list(selected_steps.keys()) or pm.STEP_METHODS)[0]
    142     example_step_name = getattr(example_step, "name")
--> 143     raise ValueError(
    144         f"Invalid key{s} found in step_kwargs: {unused_args}. "
    145         "Keys must be step names and values valid kwargs for that stepper. "
    146         f'Did you mean {{"{example_step_name}": {{"{example_arg}": ...}}}}?'
    147     )
    149 if len(steps) == 1:
    150     return steps[0]

ValueError: Invalid key found in step_kwargs: {'Y'}. Keys must be step names and values valid kwargs for that stepper. Did you mean {"nuts": {"Y": ...}}?

I'm just trying to run with this config

![image](https://github.com/pymc-labs/pymc-marketing/assets/60514527/21f6e375-d658-4a0b-b3b6-2cff5da043dd)

Can someone help me with this? My data is in millions maybe that could cause that?

**Comment by wd60622** [comment]
Try a lowercase y instead of Y
