### ISSUE TITLE
Remove Lint steps from CI as we have pre-commit-ci?

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#500]
Shall we remove

https://github.com/pymc-labs/pymc-marketing/blob/bc71f159490a75660e563a6ae4bd7214ca2b18d1/.github/workflows/ci.yml#L13-L26

as we have https://pre-commit.ci/ ?

We would lose checking this against a grid of Python versions and old and new PyMc versions, but I do not think this is super necessary. Any thoughts?

**Comment by ricardoV94** [comment]
I think that's fine, we are still running the tests against the old PyMC, no? That's the one that matters

**Comment by juanitorduz** [comment]
Indeed!
