### ISSUE TITLE
Pydantic for data validation?

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/pymc-marketing#502]
At the end of https://github.com/pymc-labs/pymc-marketing/pull/498, we touched on a point it was been on my mind for a while now. 

**Shall we use [`pydantic`](https://docs.pydantic.dev/latest/) for data validation?**
I have worked with Pydantic on many projects, and I love it! It is super fast and actively maintained! See for example the data generation process in https://juanitorduz.github.io/multilevel_elasticities_single_sku/
This would provide a modern and elegant way to validate data (input data and parameters). If we agree on doing it I would be happy to kick-off this initiative 😄 .

**Comment by ColtAllen** [comment]
Is it common for model parameters to be incorrectly specified? If not I think `pydantic` is overkill. It's great for data pipelines, but although `pydantic` can validate if an input is a pandas DataFrame, it can't validate the contents of that dataframe. Same with a dict for model_config.

**Comment by juanitorduz** [comment]
Actually I think you can add custom checks and balances n the fields (eg the data frame). Look in the example I shared above I have something like

```python
@field_validator("items")
    def validate_item_ids(cls, value):
        if len({item.id for item in value}) != len(value):
            raise ValueError("items must have unique ids")
        return value
```

Which is a custom check :)

**Comment by ColtAllen** [comment]
I did look at it, and was in the middle of editing my previous post when you replied haha.

I've used `pandera` in the past for validating dataframes, but feel it's too specialized to add as a library requirement. In general I'm in favor of keeping requirements to a minimum and not adding any additional development overhead unless this is a significant problem we should go ahead and address?

On a related note, I created an issue to add a [data validation utility method](https://github.com/pymc-labs/pymc-marketing/issues/175) to the CLV module for users who provide their own RFM data, but have other priorities at the moment.

**Comment by juanitorduz** [comment]
>  In general I'm in favor of keeping requirements to a minimum.

I also agree with this in general.

I think `pydantic` is a widely popular library so I don't think is as bad as a very niche one. Still, it is a fair point.

I think the problem we want to solve is to have a unified way for data and parameter validation. There is nothing wrong on how we are using it now, it is more about a nicer API. Still, I do not have a very strong option. I will investigate more and see if `pydantic` can bring us more benefits. 

Thanks for the feedback :)

**Comment by ferrine** [comment]
For dataframes you use panders

**Comment by ferrine** [comment]
Pandera is great, it is as actively developed as pydantic

**Comment by juanitorduz** [comment]
we can close this one IMO
