### ISSUE TITLE
Unable to predict on unseen data due to need to change coords in data setter

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#507]
Hello Everyone,

I am facing a weird issue while trying to predict on unseen data. I am using the below model :

```
import datetime
from sklearn.model_selection import train_test_split
sampler_config= {"progressbar": True}


# Define Model parameters
X = df_mmm.drop(["A","Dates"],axis=1)
y = df_mmm["A"]

# Another way to split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, shuffle=False)

train_df = pd.DataFrame(X_train,y_train)


mmm = DelayedSaturatedMMM(
    model_config = mynew_model_config,#dummy_model.default_model_config,
    sampler_config = sampler_config,
    data=train_df,
    target_column='Joins',
    date_column='Date',
    validate_data = True,
    channel_columns=['A','B','C','Displ','META','Radio','Snapchat,'TikTok','TV','YouTube'],
    control_columns = ['google_trends'],
    adstock_max_lag = 1,
    yearly_seasonality = 2
)
mmm.model_config
```

However when I try to predict on X_test, it says the coords value needs to be set, the error is specifically in the _data_setter method. 

There are 292 records in my training dataset and 72 in the test and it is a mismatch on that account.

Below is the completed error message:

I am not sure if this is an issue or I am doing something wrong but I need to figure this out quickly hence posting it here for better understanding and resolution.

```
pred_samples = mmm_model.predict(X_test,extend_idata=False)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[57], line 3
      1 # samples
      2 X_test.head()
----> 3 pred_samples = ufpf_model.predict(X_test,extend_idata=False)

File C:\my_py\Lib\site-packages\pymc_marketing\model_builder.py:524, in ModelBuilder.predict(self, X_pred, extend_idata, **kwargs)
    492 def predict(
    493     self,
    494     X_pred: Union[np.ndarray, pd.DataFrame, pd.Series],
    495     extend_idata: bool = True,
    496     **kwargs,
    497 ) -> np.ndarray:
    498     """
    499     Uses model to predict on unseen data and return point prediction of all the samples. The point prediction
    500     for each input row is the expected output value, computed as the mean of MCMC samples.
   (...)
    521     >>> pred_mean = model.predict(prediction_data)
    522     """
--> 524     posterior_predictive_samples = self.sample_posterior_predictive(
    525         X_pred, extend_idata, combined=False, **kwargs
    526     )
    528     if self.output_var not in posterior_predictive_samples:
    529         raise KeyError(
    530             f"Output variable {self.output_var} not found in posterior predictive samples."
    531         )

File C:\my_py\Lib\site-packages\pymc_marketing\model_builder.py:614, in ModelBuilder.sample_posterior_predictive(self, X_pred, extend_idata, combined, **kwargs)
    595 def sample_posterior_predictive(self, X_pred, extend_idata, combined, **kwargs):
    596     """
    597     Sample from the model's posterior predictive distribution.
    598 
   (...)
    612         Posterior predictive samples for each input X_pred
    613     """
--> 614     self._data_setter(X_pred)
    616     with self.model:  # sample with new input data
    617         post_pred = pm.sample_posterior_predictive(self.idata, **kwargs)

File C:\my_py\Lib\site-packages\pymc_marketing\mmm\delayed_saturated_mmm.py:639, in BaseDelayedSaturatedMMM._data_setter(self, X, y)
    636         raise TypeError("y must be either a pandas Series or a numpy array")
    638 with self.model:
--> 639     pm.set_data(data)

File C:\my_py\Lib\site-packages\pymc\model\core.py:1979, in set_data(new_data, model, coords)
   1976 model = modelcontext(model)
   1978 for variable_name, new_value in new_data.items():
-> 1979     model.set_data(variable_name, new_value, coords=coords)

File C:\my_py\Lib\site-packages\pymc\model\core.py:1136, in Model.set_data(self, name, values, coords)
   1134 if original_coords is not None:
   1135     if new_coords is None:
-> 1136         raise ValueError(
   1137             f"The '{name}' variable already had {len(original_coords)} coord values defined for "
   1138             f"its {dname} dimension. With the new values this dimension changes to length "
   1139             f"{new_length}, so new coord values for the {dname} dimension are required."
   1140         )
   1141 if isinstance(length_tensor, TensorConstant):
   1142     # The dimension was fixed in length.
   1143     # Resizing a data variable in this dimension would
   1144     # definitely lead to shape problems.
   1145     raise ShapeError(
   1146         f"Resizing dimension '{dname}' is impossible, because "
   1147         "a `TensorConstant` stores its length. To be able "
   (...)
   1150         "or define it via a `pm.MutableData` variable."
   1151     )
```

ValueError: The 'channel_data' variable already had 292 coord values defined for its date dimension. With the new values this dimension changes to length 73, so new coord values for the date dimension are required.

I am also uploading a dummy dataset from which the last 20% will be the test dataset.
[DT.csv](https://github.com/pymc-labs/pymc-marketing/files/14120721/DT.csv)

**Comment by shuvayan** [comment]
<img width="1440" alt="Screenshot 2023-06-17 at 12 12 14 PM" src="https://github.com/pymc-labs/pymc-marketing/assets/11851253/01200de3-765e-440d-bd01-3da18ee96876">

**Comment by shuvayan** [comment]
![Screenshot 2024-02-01 at 12 04 36 AM](https://github.com/pymc-labs/pymc-marketing/assets/11851253/ed7d3d5f-5851-447b-a33f-81f2265100ed)

**Comment by wd60622** [comment]
I am a little bit confused by the setup as the keyword args are different from [docs](https://www.pymc-marketing.io/en/stable/api/generated/pymc_marketing.mmm.delayed_saturated_mmm.DelayedSaturatedMMM.html#pymc_marketing.mmm.delayed_saturated_mmm.DelayedSaturatedMMM)

Are you calling `fit` method before the predict method?
For instance, 
```python
mmm.fit(X_train, y_train)
```

I also see that you are dropping the "Date" column before the split but are using it in the model initialization. Is that correct?

**Comment by wd60622** [comment]
Also, #482 to support new data was just merged in and has not been released on PyPI just yet

**Comment by shuvayan** [comment]
> I am a little bit confused by the setup as the keyword args are different from [docs](https://www.pymc-marketing.io/en/stable/api/generated/pymc_marketing.mmm.delayed_saturated_mmm.DelayedSaturatedMMM.html#pymc_marketing.mmm.delayed_saturated_mmm.DelayedSaturatedMMM)
> 
> Are you calling `fit` method before the predict method? For instance,
> 
> ```python
> mmm.fit(X_train, y_train)
> ```
> 
> I also see that you are dropping the "Date" column before the split but are using it in the model initialization. Is that correct?

The date column being dropped is a duplicated called 'Dates' which is why I drop it. There is a separate Date column in the data which is being used during the model building process. 
Also can you please elaborate on the kwargs being different?
And yes I first fit the model and then trying to predict on unseen data.
This is the first time that I am using bayesian hence not sure if that is not the correct approach, in which case please guide me.

**Comment by shuvayan** [comment]
> Also, #482 to support new data was just merged in and has not been released on PyPI just yet

Oh , awesome. Is there any way I can implement the new data support method with the existing library?

**Comment by wd60622** [comment]
> Oh , awesome. Is there any way I can implement the new data support method with the existing library?

At the moment you'd have to pip install via the GitHub URL. However, I suspect the release to be within the next week or so

**Comment by shuvayan** [comment]
> > Oh , awesome. Is there any way I can implement the new data support method with the existing library?
> 
> At the moment you'd have to pip install via the GitHub URL. However, I suspect the release to be within the next week or so

That is great news. Thank you so much for the quick reverts and awesome library!!

**Comment by wd60622** [comment]
> That is great news. Thank you so much for the quick reverts and awesome library!!

Glad you are enjoying the package!

**Comment by wd60622** [comment]
Package was just released to PyPI
I will close the issue. Feel free to open another one if you run into any issues

**Comment by shuvayan** [comment]
Hello @wd60622 ,

That is great news. Will it be available on conda or should I build it from PyPI source?

**Comment by wd60622** [comment]
Definitely on PyPI at the moment
If you install Pymc from conda and Pymc market from pypi, that might work
