### ISSUE TITLE
Relax numpy version in requirements

### ISSUE THREAD

**Issue by ferrine** [pymc-labs/pymc-marketing#508]
Hi, I found that pymc_marketing installation changes numpy version. Why do we need this constraint?
https://github.com/pymc-labs/pymc-marketing/blob/b411b309f59edf1b49c9083862715f4c34edf349/pyproject.toml#L17C6-L17C25

**Comment by ferrine** [comment]
I found it was introduced in https://github.com/pymc-labs/pymc-marketing/pull/370

**Comment by ricardoV94** [comment]
Looks like a mistake?

**Comment by ferrine** [comment]
I think so, let me open a PR
