### ISSUE TITLE
Plot channel contribution with adstock and lag effects

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#513]
Hello ,

I was trying to use the MMM.plot_direct_contribution_curves function to plot the contribution curves for each channel with the adstock and delayed effects but could not find an option to do so.
Is there a way to do that which I am missing ?

Can someone please guide me here?

**Comment by shuvayan** [comment]
Also, is there a way to export these plots outside of python environment so that it can input to another tool?

**Comment by wd60622** [comment]
> Hello ,
> 
> I was trying to use the MMM.plot_direct_contribution_curves function to plot the contribution curves for each channel with the adstock and delayed effects but could not find an option to do so. Is there a way to do that which I am missing ?
> 
> Can someone please guide me here?

The channel contributions variable does include the adstock and saturation from the spends in the training data set. It is already accounted for then in the `plot_direct_contribution_curves` function
See here: https://github.com/pymc-labs/pymc-marketing/blob/9148a9158eec9840cf490277ddf399d550ae0989/pymc_marketing/mmm/base.py#L982-L984

**Comment by wd60622** [comment]
> Also, is there a way to export these plots outside of python environment so that it can input to another tool?

What do you have in mind? A matplotlib object is returned which can be saved with [`plt.savefig` function](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html)

**Comment by shuvayan** [comment]
Something like the attached image. We want to see the channel contributions on the MMM curves as in the image. 
Basically need to see the contribution lines and access their values as returned by compute_channel_contribution_original_scale
![Screenshot 2024-02-07 at 4 50 15 PM](https://github.com/pymc-labs/pymc-marketing/assets/11851253/613bf584-2c29-4627-81b1-93379bcf4321)

**Comment by wd60622** [comment]
You might want to just save off the data from the channel contributions directly. The DataArray can be saved via a DataFrame with the xarray methods
