### ISSUE TITLE
`test_new_data_sample_posterior_predictive_method` takes 50 minutes (70%) of CI time

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#514]
I counted 35 parametrizations, each of which takes roughly 90 seconds long. This accounts for 50 minutes or 70% of the whole CI in this run:

https://github.com/pymc-labs/pymc-marketing/actions/runs/7771863902/job/21193663231?pr=506#step:5:872

**Comment by ricardoV94** [comment]
Somewhat related to #361

**Comment by ricardoV94** [comment]
CC @wd60622

**Comment by wd60622** [comment]
Might be best to change the fixture scope. Maybe to [session](https://pytest-with-eric.com/pytest-advanced/pytest-fixture-scope/#Session-Scope)?
I think I didn't have it part of the class like the other tests
