### ISSUE TITLE
Rename `models` folder

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#520]
https://github.com/pymc-labs/pymc-marketing/tree/main/models

**Comment by ricardoV94** [comment]
Which notebook? Should be in datasets if needed but is it needed?

**Comment by wd60622** [comment]
the budget allocation
https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_budget_allocation_example.html

**Comment by ricardoV94** [comment]
Should go here then no? It's where we save other data for examples

https://github.com/pymc-labs/pymc-marketing/tree/main/datasets

And maybe have a better name?

**Comment by ricardoV94** [comment]
I mean the trace filename should have a better name

**Comment by twiecki** [comment]
So yes, two issues:
* Rename the idata file to have a better name
* Rename `datasets` to `data`, move the idata file to `data`.
