### ISSUE TITLE
Add `nutpie` Fit Example to Docs

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#522]
`nutpie` is a lightning fast NUTS sampler built in Rust that puts to rest the claims that Bayesian models take forever to fit. I think some example code would be a great addition to one or more of the modeling notebooks.

**Comment by wd60622** [comment]
Think we are good to close this out: https://www.pymc-marketing.io/en/stable/notebooks/general/other_nuts_samplers.html
