### ISSUE TITLE
Publish `ParetoNBDModel` Notebook

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#524]
We should complete https://github.com/pymc-labs/pymc-marketing/pull/463 before doing this.

**Comment by ColtAllen** [comment]
Now that covariates are supported, I'll prioritize this.

- [ ] Overview of model, with brief history and `ParetoNBD` distribution block and latent distribution plots.
- [ ] Example with and w/o covariates using the CDNOW dataset (raw transaction data includes items per purchase, and money spent)
- [ ] `expected_probability_alive` plots.
- [ ] Some caveats on model fitting.
- [ ] Unsupported functionality: https://github.com/pymc-labs/pymc-marketing/issues/183

**Comment by juanitorduz** [comment]
@ColtAllen I will mark this one as done :)
