### ISSUE TITLE
Data preprocessors not implemented correctly for out-of-sample prediction  

### ISSUE THREAD

**Issue by amanderson** [pymc-labs/pymc-marketing#542]
I have some doubts that the current version is setup to do out-of-sample prediction correctly. I think the issue lies with data preprocessing. Shouldn't the preprocessors, e.g. MaxAbsScaleChannels be fit once on in-sample data, with those same scaling parameters made available to out-of-sample data? If you have to refit the pre-processors on out-of-sample data, surely this would lead to possible prediction error especially if you model has non-linear transformations on channel data.

**Comment by amanderson** [comment]
Thanks @wd60622 I think you're right here about the implementation in the `DelayedSaturationMMM`. I was building on the `BaseMMM` class for a custom model and probably confused myself. You're right about the Mixin - they do require you to hold a lot of implementation detail in your head. Maybe there's justification for refactoring this into the `predict` step?

**Comment by wd60622** [comment]
Subclassing from BaseMMM if definitely unknown territory for me and I don't think the user experience to know what is required is clear. 

For the DelayedSaturationMMM, maybe the `sample_posterior_predictive` method would be better part of the `BaseMMM` class as that is what handles the new data correctly which would help in subclassing?
https://github.com/pymc-labs/pymc-marketing/blob/a366a3033618cd19bc30307918f1792010518abb/pymc_marketing/mmm/delayed_saturated_mmm.py#L856

`sample_posterior_predictive` is what is used in all of the other out of sample methods, including `predict` 

FYI: If you have any suggestions on preferred API, we've started a discussion here: https://github.com/pymc-labs/pymc-marketing/discussions/537

**Comment by amanderson** [comment]
Thanks @wd60622 for the comments. I'll close this and check out the discussion on the API. I think that's ultimately where I stumbled.
