### ISSUE TITLE
Data Used in CLV Quickstart

### ISSUE THREAD

**Issue by BeiYaaa** [pymc-labs/pymc-marketing#548]
Hi there, 

Under 1.1 Data Requirements the file read from the hyper link is different from the output in the tutorial.
#### What's on the UI:
![image](https://github.com/pymc-labs/pymc-marketing/assets/33733796/58f9038c-0cc3-47c6-af91-635ab2fcae91)
#### What I get:
![image](https://github.com/pymc-labs/pymc-marketing/assets/33733796/42326ecd-4db5-4138-b54f-cac08b9328c8)

**Comment by ColtAllen** [comment]
Hey @BeiYaaa,

The hyperlink is correct. Looks like that cell simply wasn't re-ran when the Quickstart was updated. It's a very simple fix if you want to open a PR. Otherwise I'll get around to it after finishing some enhancements for the CLV module.
