### ISSUE TITLE
Is there a way to apply the weibul adstock transformation in model 

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#551]
Hello,

I see that there is a weibull adstock transformation function available but it is not currently being called in the delayed_saturated_mmm module (only geometric adstock) is being called.
May I know if there is a way I can use the weibul adstock transformation within the framework?

**Comment by wd60622** [comment]
You're right. The delayed MMM class doesnt currently have support for different saturation functions. 

At the moment, you would have to inherit from the class and override the build_model method to use the adstock, saturation, etc that you would like to use

**Comment by shuvayan** [comment]
Okay. Thank you so much for sharing the methodology , I will see if I can implement it!!

**Comment by wd60622** [comment]
Hi @shuvayan 
Hope you were able to figure out a solution.
FYI: We are working on a #632 where a user can specify the saturation function (as well as adstock)
