### ISSUE TITLE
compute_sigmoid_second_derivative is wrong

### ISSUE THREAD

**Issue by Garve** [pymc-labs/pymc-marketing#569]
Hi!

I just noticed that the second derivative of the extended sigmid function is wrong.
https://github.com/pymc-labs/pymc-marketing/blob/9d8dab3299558a8ddb41bdd0524dea6d150f37e9/pymc_marketing/mmm/utils.py#L221-L227

If you take this function
<img width="73" alt="image" src="https://github.com/pymc-labs/pymc-marketing/assets/932327/6118bfc2-ab51-4c43-89d7-8e1ae097eaa8">
and compute the derivative wrt to *x*, you get
<img width="112" alt="image" src="https://github.com/pymc-labs/pymc-marketing/assets/932327/97dc1de2-7125-49ee-aecd-66e04192bb3d">
or, if you like the negative exponents, 
<img width="134" alt="image" src="https://github.com/pymc-labs/pymc-marketing/assets/932327/12116a4f-911f-4d25-b5d6-f30f29e04d70">

In code:
```python
(
    -2*alpha
    * lam**2
    * (1-np.exp(-lam*x))
    * np.exp(-lam*x)
    / (1 + np.exp(-lam * x)) ** 3 
)
```

You can also see that this function only has one inflection point at 0, so we don't need this function
https://github.com/pymc-labs/pymc-marketing/blob/9d8dab3299558a8ddb41bdd0524dea6d150f37e9/pymc_marketing/mmm/utils.py#L230

This function is used in mmm/base.py, but whatever it returns, it is wrong.

**Comment by juanitorduz** [comment]
Thanks @Garve ! Would you like to fix this with a PR?

**Comment by juanitorduz** [comment]
@carlosagostini

**Comment by cetagostini** [comment]
Hey @Garve 

You are right, we are not computing the actual inflection point, and not the actual second derivative. It's a naming issue.

We are looking to show the point at which the response of your channels begins to saturate and separate from a linear response. At the beginning of the saturation functions we could have a small area that is almost linear and at a certain point, the function begins to diverge from this, and shift, that's the point we seek to show.

Here is the plot and what we are computing:
![image](https://github.com/pymc-labs/pymc-marketing/assets/59846724/b4b53591-e13f-43bf-82d5-39bba93f57e0)

Why? We could say that within a response curve we have several areas:
1. **The "safe" zone**, where you can invest and your returns will be the maximum possible (even when you are losing growth opportunities).
2. **The "optimal" zone**, where you invest and are paying a "fair" price, would usually be around the middle area of the curve.
3. **The "unprofitable" zone**, where you manage to make the most of all possible contributions but at a very high cost.

This point we marked should represent how far your "safe" zone goes. As you can see it is not exactly the inflection point, in fact, at the beginning we called this "elbow" (You can check #287). But at some point, he changed his name.

**Comment by cetagostini** [comment]
Hey guys, I'm closing the issue and opening a new PR for it.
