### ISSUE TITLE
mmm.plot_posterior_predictive() does not work

### ISSUE THREAD

**Issue by Garve** [pymc-labs/pymc-marketing#570]
Hi! I trained a model, and when I execute
`mmm.plot_posterior_predictive()`, I get 

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[262], line 1
----> 1 mmm.plot_posterior_predictive()

File [~\miniconda3\envs\mmm\Lib\site-packages\pymc_marketing\mmm\base.py:303](http://localhost:8888/lab/tree/Desktop/MMM/~/miniconda3/envs/mmm/Lib/site-packages/pymc_marketing/mmm/base.py#line=302), in BaseMMM.plot_posterior_predictive(self, original_scale, **plt_kwargs)
    300 def plot_posterior_predictive(
    301     self, original_scale: bool = False, **plt_kwargs: Any
    302 ) -> plt.Figure:
--> 303     posterior_predictive_data: Dataset = self.posterior_predictive
    304     likelihood_hdi_94: DataArray = az.hdi(
    305         ary=posterior_predictive_data, hdi_prob=0.94
    306     )[self.output_var]
    307     likelihood_hdi_50: DataArray = az.hdi(
    308         ary=posterior_predictive_data, hdi_prob=0.50
    309     )[self.output_var]

File [~\miniconda3\envs\mmm\Lib\site-packages\pymc_marketing\mmm\base.py:251](http://localhost:8888/lab/tree/Desktop/MMM/~/miniconda3/envs/mmm/Lib/site-packages/pymc_marketing/mmm/base.py#line=250), in BaseMMM.posterior_predictive(self)
    248 @property
    249 def posterior_predictive(self) -> Dataset:
    250     if self.idata is None or "posterior_predictive" not in self.idata:
--> 251         raise RuntimeError("The model hasn't been fit yet, call .fit() first")
    252     return self.idata["posterior_predictive"]

RuntimeError: The model hasn't been fit yet, call .fit() first
```

The `self.idata` exists, but it does not have a posterior_predictive attribute.

pymc_marketing version 0.4.0.

**Comment by wd60622** [comment]
Did you set the extend = True when using the 'sample_posterior_predictive' method?

**Comment by Garve** [comment]
Hi!

I just trained a model and called this method. I didn't call sample_posterior_predictive explicitly anywhere.

Best
Robert

**Comment by smusch2** [comment]
Having the same issue. Is it possible this is only available in the "base" model?

[https://github.com/pymc-labs/pymc-marketing/blob/9d8dab3299558a8ddb41bdd0524dea6d150f37e9/pymc_marketing/mmm/base.py](base.py) - posterior_predictive on __init__ line 61

[https://github.com/pymc-labs/pymc-marketing/blob/9d8dab3299558a8ddb41bdd0524dea6d150f37e9/pymc_marketing/mmm/delayed_saturated_mmm.py](delayed_saturated_mmm.py) - posterior_predictive not listed within __init__

**Comment by smusch2** [comment]
@Garve Did you run the top line shown here? It fixed my issue.

mmm.sample_posterior_predictive(X, extend_idata=True, combined=True)
mmm.plot_posterior_predictive(original_scale=True)

**Comment by juanitorduz** [comment]
We need a better error message for this one.

**Comment by ulfaslak** [comment]
I have run into this too. How about adding some logic that does `sample_posterior_predictive` inside `plot_posterior_predictive` if it hasn't already been done.

**Comment by wd60622** [comment]
#741 introduces new error message telling user to call sample_posterior_predictive method
