### ISSUE TITLE
Add a job that tests all notebooks upon every release

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/pymc-marketing#576]
We sometimes break API that is described in some of the example notebooks without us noticing it right away. It would be great to have a CI job that rerurns all notebooks and checks for errors upon every release (every PR would probably take too long).

CC @wd60622 @juanitorduz

**Comment by juanitorduz** [comment]
A first *brute-force* attempt was tried at https://github.com/pymc-labs/pymc-marketing/pull/624. Instead, we want to go the way PyMC runs the core notebooks.

> it's on the readthedocs job, not github actions. The relevant lines are: https://github.com/pymc-devs/pymc/blob/main/docs/source/conf.py#L149-L153 (with on_readthedocs being https://github.com/pymc-devs/pymc/blob/main/docs/source/conf.py#L109 so building docs locally skips running notebooks and is therefore faster)

**Comment by juanitorduz** [comment]
More input:
> https://myst-nb.readthedocs.io/en/latest/computation/execute.html#exclude-notebooks-from-execution
If you want to specify paths/patterns to match to paths add this variable to conf.py, it also possible to include/exclude based on extension
