### ISSUE TITLE
Returning parameters for saturation & carryover effect

### ISSUE THREAD

**Issue by smusch2** [pymc-labs/pymc-marketing#587]
Following the main 2 examples:

https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html
Carryover/adstock effect's default:
`'alpha': {'dist': 'Beta', 'kwargs': {'alpha': 1, 'beta': 3}}`

Saturation effect's default:
`'lam': {'dist': 'Gamma', 'kwargs': {'alpha': 3, 'beta': 1}}`

---

https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_budget_allocation_example.html
Then, for the saturation curve, I see alpha & **lambda** being returned. 
`sigmoid_params = mmm.compute_channel_curve_optimization_parameters_original_scale(method='sigmoid')`

"After running the code above, you will receive a dictionary containing α and λ for each channel."

`'x1': array([2.40931096, 6.11360947])`

Why is this now being referred to as lambda?

**Comment by wd60622** [comment]
lambda is a keyword in python so it isnt typically used. 
https://www.programiz.com/python-programming/keyword-list
I dont think think you can override it. Like with return or def

In my mind,
lam = lambda = $\lambda$ 
but lam would be available normal character variable name and likey used in code. 

Let me know if I misunderstood your question
