### ISSUE TITLE
Figure out API for incorporating information from lift tests on MMM

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#60]
@juanitorduz mentioned that in the literature this is usually incorporated into the prior information, but I think that in the HelloFresh project @lucianopaz found a way to incorporate such information via observed variables in the same MMM model?

**Comment by juanitorduz** [comment]
I think with the great work by @wd60622 in https://github.com/pymc-labs/pymc-marketing/pull/590, we can close this one 🚀 !
