### ISSUE TITLE
Potential typo in CLV Quickstart documentation

### ISSUE THREAD

**Issue by gcarnelos** [pymc-labs/pymc-marketing#609]
This issue reports a potential inconsistency in the CLV Quickstart documentation, specifically within the "Estimating CLV" section.

The text currently reads:

- "According to our models, customer 6 has a much higher expected CLV."

There might be a typo in the customer reference. Here are two possibilities for a more accurate representation:
1. "According to our models, customer 5 has a much higher expected CLV."
2. "According to our models, the 6th customer has a much higher expected CLV."

https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html#estimating-customer-lifetime-value-using-the-gamma-gamma-model

![pymc-marketing-clv_quickstart](https://github.com/pymc-labs/pymc-marketing/assets/77063377/f553c774-0a2e-4c78-bf21-79eb6a9fcfea)

**Comment by twiecki** [comment]
That's confusing indeed. Maybe clearest would be "According to our models, customer[5] has a much higher expected CLV." Want to do a PR?

**Comment by ColtAllen** [comment]
I'm making some changes to the Quickstart in https://github.com/pymc-labs/pymc-marketing/pull/601, and went ahead and added the fix for this.

**Comment by juanitorduz** [comment]
@ColtAllen can we close this one after we merged the PR?

**Comment by ColtAllen** [comment]
Whoops, forgot this was still open. Closing now.
