### ISSUE TITLE
Reference correct adstock function in DelayedSaturatedMMM documentation

### ISSUE THREAD

**Issue by fountaindive** [pymc-labs/pymc-marketing#610]
Hi,

I had a quick question about the `DelayedSaturatedMMM` model. The documentation says it uses a 'delayed adstock' however, if I look at the code it seems to use the 'geometric adstock'. Is this a typo?

Sorry if this issue is raised already, I had a look but couldn't see anything.

Many thanks!

**Comment by wd60622** [comment]
Hi @fountaindive 
It seems like it is a typo. The code in the DelayedSaturatedMMM model would be the ground truth. 
Can you link where this typo is?
Thanks!

**Comment by fountaindive** [comment]
Hey!

yup sure thing

[here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L48) the doc string says 'delayed'

and I believe [here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L367) is where the geometric adstock is used

**Comment by fountaindive** [comment]
sorry noticed another couple places

[here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L511)

[here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L952)

**Comment by wd60622** [comment]
> sorry noticed another couple places
> 
> [here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L511)
> 
> [here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L952)

Thanks for tracking them down, @fountaindive 🎉 
Would you be interested in making these corrections?

**Comment by fountaindive** [comment]
Yup I'm happy to put a PR together but just to double check there would be quite a lot of code changes in order to change the code from 'DelayedSaturatedMMM' to something like 'GeometricAdstockSaturatedMMM'?

**Comment by fountaindive** [comment]
Oh I see the PR, that sounds really awesome. It doesn't make much sense to me to change the docs right now given that the other PR is going to generalise 'DelayedSaturatedMMM' and therefore the docs are going to have to change anyway. Sorry about this!
