### ISSUE TITLE
MMM Example Notebook doesn't work

### ISSUE THREAD

**Issue by arthurmello** [pymc-labs/pymc-marketing#634]
I'm trying to run this [example notebook](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#part-ii-modeling) for MMM, but there seems to be an issue.

Here's the full code, up to the part where it breaks:

```py
import warnings

import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm
import seaborn as sns

from pymc_marketing.mmm.delayed_saturated_mmm import DelayedSaturatedMMM
from pymc_marketing.mmm.transformers import geometric_adstock, logistic_saturation

warnings.filterwarnings("ignore")

az.style.use("arviz-darkgrid")
plt.rcParams["figure.figsize"] = [12, 7]
plt.rcParams["figure.dpi"] = 100

%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = "retina"

seed: int = sum(map(ord, "mmm"))
rng: np.random.Generator = np.random.default_rng(seed=seed)

# date range
min_date = pd.to_datetime("2018-04-01")
max_date = pd.to_datetime("2021-09-01")

df = pd.DataFrame(
    data={"date_week": pd.date_range(start=min_date, end=max_date, freq="W-MON")}
).assign(
    year=lambda x: x["date_week"].dt.year,
    month=lambda x: x["date_week"].dt.month,
    dayofyear=lambda x: x["date_week"].dt.dayofyear,
)

n = df.shape[0]
print(f"Number of observations: {n}")

# media data
x1 = rng.uniform(low=0.0, high=1.0, size=n)
df["x1"] = np.where(x1 > 0.9, x1, x1 / 2)

x2 = rng.uniform(low=0.0, high=1.0, size=n)
df["x2"] = np.where(x2 > 0.8, x2, 0)


fig, ax = plt.subplots(
    nrows=2, ncols=1, figsize=(10, 7), sharex=True, sharey=True, layout="constrained"
)
sns.lineplot(x="date_week", y="x1", data=df, color="C0", ax=ax[0])
sns.lineplot(x="date_week", y="x2", data=df, color="C1", ax=ax[1])
ax[1].set(xlabel="date")
fig.suptitle("Media Costs Data", fontsize=16);

# apply geometric adstock transformation
alpha1: float = 0.4
alpha2: float = 0.2

df["x1_adstock"] = (
    geometric_adstock(x=df["x1"].to_numpy(), alpha=alpha1, l_max=8, normalize=True)
    .eval()
    .flatten()
)
```

On that last line, I get the following error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-57-b5e9c74d676a> in <cell line: 6>()
      4 
      5 df["x1_adstock"] = (
----> 6     geometric_adstock(x=df["x1"].to_numpy(), alpha=alpha1, l_max=8, normalize=True)
      7     .eval()
      8     .flatten()

/opt/dataiku/dss_design/code-envs/python/pymc/lib/python3.10/site-packages/pymc_marketing/mmm/transformers.py in geometric_adstock(x, alpha, l_max, normalize, axis)
    199     w = pt.power(pt.as_tensor(alpha)[..., None], pt.arange(l_max, dtype=x.dtype))
    200     w = w / pt.sum(w, axis=-1, keepdims=True) if normalize else w
--> 201     return batched_convolution(x, w, axis=axis, mode=ConvMode.After)
    202 
    203 

/opt/dataiku/dss_design/code-envs/python/pymc/lib/python3.10/site-packages/pymc_marketing/mmm/transformers.py in batched_convolution(x, w, axis, mode)
    105 
    106     if l_max is None:  # pragma: no cover
--> 107         raise NotImplementedError(
    108             "At the moment, convolving with weight arrays that don't have a concrete shape "
    109             "at compile time is not supported."

NotImplementedError: At the moment, convolving with weight arrays that don't have a concrete shape at compile time is not supported.
```

I'm using:
- Python 3.10
- scipy == 1.12 (this is not the latest version, but using anything later than this gives an import error, according to [this issue](https://discourse.pymc.io/t/importerror-cannot-import-name-gaussian-from-scipy-signal/14170/4)
- pymc == 5.13.1
- pymc_marketing == 0.4.2

Any idea where this comes from?

**Comment by juanitorduz** [comment]
Hey! Thanks for reporting! would you mind trying the latest versions of scipy (1.13.0) and arviz (0.18.0) please 🙏 ?

**Comment by arthurmello** [comment]
Hi! Just did, same error :(
(although with arviz 0.18.0 I can use scipy 1.13.0 without the import error previously mentioned)

**Comment by juanitorduz** [comment]
ok! Can you try please try with pymc == 5.12.0 ? I am also looking to it from my side 🙏

**Comment by juanitorduz** [comment]
It is weird the error is triggered when `if l_max is None`, but you are clearly passing that parameter, right?

**Comment by arthurmello** [comment]
Just tried with pymc== 5.12.0, still the same error. Does it work for you?

I checked the [source code](https://www.pymc-marketing.io/en/stable/_modules/pymc_marketing/mmm/transformers.html), and the `l_max` they are refering to in the error message is not the one inside `geometric_adstock`, but the one inside `batched_convolution` (which is called by `geometric_adstock`) :

```py
w = pt.power(
        pt.as_tensor(alpha)[..., None],
        (pt.arange(l_max, dtype=x.dtype) - pt.as_tensor(theta)[..., None]) ** 2,
    )
w = w / pt.sum(w, axis=-1, keepdims=True) if normalize else w
```

[...]

```py
  w = pt.as_tensor(w)
  l_max = w.type.shape[-1]
  if l_max is None:
      try:
          l_max = w.shape[-1].eval()
      except Exception:
          pass
```

[...]

```py
  if l_max is None:  # pragma: no cover
      raise NotImplementedError(
          "At the moment, convolving with weight arrays that don't have a concrete shape "
          "at compile time is not supported."
      )
```

**Comment by juanitorduz** [comment]
Ok! I will investigate! For me is running fine ... let's see what I discover ... 🙏

**Comment by juanitorduz** [comment]
@arthurmello, are you on a Windows machine ? (trying to figure out causes)

**Comment by juanitorduz** [comment]
As an alternative, while we figure it out, you can try running the notebook in Docker https://github.com/pymc-labs/pymc-marketing/tree/main/scripts/docker ...

**Comment by arthurmello** [comment]
No, I'm on Linux...
I will try to run it on Docker in parallel to compare outputs and debug. Will post any updates here, thanks for helping :)

**Comment by juanitorduz** [comment]
Can you try with pymc-marketing 0.5.0 (latest release)/ 🙏 /

**Comment by arthurmello** [comment]
Just did, and I get the same error... haven't had the time to try it on Docker yet, sorry :(

**Comment by juanitorduz** [comment]
Have you any update? What about with version 0.6.0?

**Comment by arthurmello** [comment]
Yes, I updated it and still get the same error.
There is a error-like warning message before the actual Python error. It's too long for the comment, so I'll attach it as a file.
[error.txt](https://github.com/user-attachments/files/15544480/error.txt)

**Comment by wd60622** [comment]
> Yes, I updated it and still get the same error. There is a error-like warning message before the actual Python error. It's too long for the comment, so I'll attach it as a file. [error.txt](https://github.com/user-attachments/files/15544480/error.txt)

Seems like a pytensor installation issue. Are you using conda or mamba to install the environment? A fresh installation in virtual environment might do the trick

**Comment by arthurmello** [comment]
Indeed, it seems to be exclusively a local problem related to the installation, not with the source code.
I've tried it in a a different machine, using Docker, and it works.
Thanks!
