### ISSUE TITLE
MMM Example Notebook returns KeyError: 'dist'

### ISSUE THREAD

**Issue by rym903** [pymc-labs/pymc-marketing#658]
When I tried to run [MMM Example Notebook](https://www.pymc-marketing.io/en/0.2.2/notebooks/mmm/mmm_example.html) on my Macbook and Colab Enterprise on Vertex AI, I encountered KeyError like below in both environments:

![image](https://github.com/pymc-labs/pymc-marketing/assets/28842214/0997e560-3200-447c-843f-ba5326f3ed64)

Package versions I used are following.↓
```
Running on PyMC3 v5.13.1
Running on ArviZ v0.18.0
Running on NumPy v1.26.4
Running on Pandas v2.2.2
Running on PyMC_Marketing v0.5.0
```

**Comment by rym903** [comment]
I found that if I don't specify any configuration in _my_config_, then it works.

![image](https://github.com/pymc-labs/pymc-marketing/assets/28842214/97aa67ae-409e-4223-bd3d-d275126fc0c7)

**Comment by wd60622** [comment]
Can you able display the `model_config` attribute for the model instance

**Comment by rym903** [comment]
sorry, i've read old version example.
