### ISSUE TITLE
Negative custom priors (again!)

### ISSUE THREAD

**Issue by charlesshawmsix** [pymc-labs/pymc-marketing#668]
I feel there is a small but important issue in PyMC with respect to custom priors.

Let's say I have a context variable coefficient that needs to be negative. For example, competitor spend.

context_vars = [
    "variable_1",
    "variable_2",
    "variable_3",
    "variable_4",
    "competitor_spend"
]

context_signs = [
    "positive",
    "positive",
    "positive",
    "positive",
    "negative"
]

There is a discuss here about the negative coeff channels:

https://discourse.pymc.io/t/pymc-marketing-mmm-setting-negative-negative-variables-using-priors/13109/4

which was then raised as issue #413 (but not resolved)
https://github.com/pymc-labs/pymc-marketing/issues/413

So the question is this: does the library allow a user to force negative coefficients for selected regressors?

For some models we run this is a bit of an issue. For example, models with competitor spend (I tend to work with industries that are highly competitive). Also, this raises some questions about modelling price.

**Comment by charlesshawmsix** [comment]
Right. So you seem to be saying to multiply the data by -1 before passing it to the model.

I guess another solution is to specify a uniform prior, between some negative value and 0. Then it would be bounded at zero. But this feels unsatisfactory.

I am not worried about the channel variables, just the controls.

**Comment by wd60622** [comment]
Maybe a note about this in the example MMM notebook if this is the recommended solution
