### ISSUE TITLE
Handle recent pymc deprecation warnings

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#669]
MutableData -> Data
coords_mutable -> coords

Should a minimal version of PyMC be pinned?

**Comment by juanitorduz** [comment]
We have this https://github.com/pymc-labs/pymc-marketing/blob/main/pyproject.toml#L20 (we can control this). We need to make it consistent with https://github.com/pymc-labs/pymc-marketing/blob/main/pyproject.toml#L20 🙈

**Comment by wd60622** [comment]
Maybe good to have lower as 5.13.0 instead of 5.12.0 and get rid of the mutable deprecation warnings? Think one minor release difference for that is not too much

Ref: https://github.com/pymc-devs/pymc/releases/tag/v5.13.0
