### ISSUE TITLE
Pull out fourier transformation from MMM method

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#679]
Pulling out fourier transformation from the MMM methods would be very convenient and reduce the dependency with that class.

I think the logic can be isolated, making it very easy to a isolate in a model. For instance,
```python
fourier = YearlyFourier(nodes=10)

coords = {"date": [...], "fourier_components": fourier.columns}
with pm.Model(coords=coords) as model: 
    dayofyear = pm.Data("dayofyear", ..., dims="date")
    seasonality = pm.Deterministic(
        "seasonality", 
        fourier.apply(x=dayofyear), 
        dims=("date", "fourier_components"), 
    )
    
    mu = seasonality.sum(axis=1)
```

Then it could be used pretty easily in more larger more custom models (following flow of #632)

```python
from pymc_marketing.mmm.components import MichaelisMenten, GeometricAdstock

adstock = GeometricAdstock(l_max=10, mode=ConvType.Before)
saturation = MichaelisMenten()

def create_forward_pass(first, second): 
    def media_forward_pass(x, dim): 
        return second.apply(x=first.apply(x=x, dim=dim), dim=dim)
    return media_forward_pass

forward_pass = create_forward_pass(adstock, saturation)

with model: 
    model.add_coord("channel", ["C1", "C2", "C3"])
    
    media_data = pm.Data("media_data", ..., dims=("date", "channel"))
    media_contribution = pm.Deterministic(
        "media_contribution",  
        forward_pass(media_data, dim="channel"), 
        dims=("date", "channel"),
    )
    
    mu += media_contribution.sum(axis=1)

with model: 
    ...
    mu += holiday_effects + time_varying_intercept + endless_imagination
```

The `YearlyFourier` class could hold information about the priors to be familiar with the new classes from #632

Thoughts on the isolation and API idea?

**Comment by juanitorduz** [comment]
@wd60622 Personally, I like this suggestion a lot as is towards the direction of a more modular MMM constructor :) Also, it makes the module conceptually consistent :). We could even have a weekly Fourier class (for daily data) so a more general class with period and length (no strong opinion about the approach)

**Comment by wd60622** [comment]
Sounds great, then I will get to implementing!

One of the aspects suggested from this example API is having the fourier transformations in pytensor. Any reasons against the switch from numpy / dataframe to pytensor completely?
Having these tranforms in pytensor would allow to set Data of dayofyear instead of fourier transformation itself. Might be an easier user experience imo. Thoughts?

**Comment by juanitorduz** [comment]
Having everything written in `pytensor ` is the way to go 100% :D
