### ISSUE TITLE
Differentiate between RFM segmentation and CLV when defining recency/frequency/monetary

### ISSUE THREAD

**Issue by hmanz** [pymc-labs/pymc-marketing#697]
I noticed in [the code](https://github.com/pymc-labs/pymc-marketing/blob/61da9c05721a70cd80e41dd68a7772622ca23cac/pymc_marketing/clv/utils.py#L490) that a differentiation is made for the definitions depending on if we are doing RFM segmentation or CLV. However in the docs (e.g. [CLV Quickstart](https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html)) this differentiation is not mentioned and it can lead to some confusion particularly for people who are new to either RFM segmentation or CLV.

**Comment by wd60622** [comment]
Hi @hmanz 
Good eye! Thank you for pointing this out. 
Would you like to make a PR?

**Comment by ColtAllen** [comment]
Hey @hmanz,

I can roll this into the existing https://github.com/pymc-labs/pymc-marketing/pull/680 PR.
