### ISSUE TITLE
Deploy streamlit app with pymc-labs

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#704]
The streamlit app is routed through @louismagowan's branch on a fork of the main repo

It'd be ideal to set this up with a merge to pymc-labs/main branch so that streamlit links come back to main branch.

Can streamlit be deployed with GitHub action? or is it only through their streamlit UI via an account. A bit unknown to me

See also #701 

There were some details in the original issue #613 and PR #614

**Comment by louismagowan** [comment]
@wd60622 - would you have time this week for us to close this one? It should be super simple - just requires someone with full permissions on pymc-marketing to do it ☺️

**Comment by wd60622** [comment]
> @wd60622 - would you have time this week for us to close this one? It should be super simple - just requires someone with full permissions on pymc-marketing to do it ☺️

Hey @louismagowan 
Sounds good. I will reach out to you

**Comment by wd60622** [comment]
Thanks @louismagowan  for the help!
