### ISSUE TITLE
Model config wrapper around `pm.find_contrained_prior`

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#706]
It might be convenient to support wrapper around [find_contrained_prior](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.find_constrained_prior.html) from the dictionary model config somehow. 

For instance, 

```python
model_config = {
    "beta_channel": {
        "dist": "Normal", 
        "kwargs": {"mu": 0, "sigma": 1}, 
        # Just add this 
        "bounds": {"lower": -3, "upper": 3}, 
    }, 
    ...
}
mmm = DelayedSaturatedMMM(..., model_config=model_config, ...)

# Which would be converted to via some internal logic
beta_channel_parameters = pm.find_contrained_prior(pm.Normal, lower=-3, upper=3, init_guess={"mu": 0, "sigma": 1})
beta_channel = pm.Normal("beta_channel", **beta_channel_parameters, dims="channel")
```
Though a user can do this outside of the model, I'd imagine it would have to be done many times so this would be convenience.

Would love to hear any thoughts on this

**Comment by juanitorduz** [comment]
Yes! I think this would be a great feature!

**Comment by wd60622** [comment]
> Yes! I think this would be a great feature!

## 1. How should the dictionary look?

Do you think that other parameters of the find_contrained_prior function should be exposed as well? 
Should the "kwargs" be for that functions then? 
i.e. 
```python
beta_channel_config = {
    "dist": "Normal", 
    "init_guess": {"mu": 0, "sigma": 1}, 
    # kwargs for the find_contrained_prior
    "kwargs": dict(lower=-3, upper=3, mass=0.90), 
}
```
Think that there would need to be a new key / different set of keys from in order to distinguish the branch of logic to take. So this could look many different ways.

## 2. Should it be internal or external of class initialization? 

Also might be a good util function instead so it is done once and outside of the model initialization. 
i.e. 
```python
model_config = ... # Whatever dictionary format is agreed upon
model_config = pymc_marketing.utils.find_contrained_prior(model_config)

# model_config now has "kwargs" that will fit the format as before
# Models would only take the already done format of the model_config

**Comment by juanitorduz** [comment]
I like the external approach better 👍
