### ISSUE TITLE
Hierarchical distributions for all parameters in model config

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#708]
The [_create_likelihood_distribution](https://github.com/pymc-labs/pymc-marketing/blob/b763c1207f432f17b6ea920764abafb8c14bd6ba/pymc_marketing/mmm/delayed_saturated_mmm.py#L210) accepts a nested dictionary. i.e. 
https://github.com/pymc-labs/pymc-marketing/blob/b763c1207f432f17b6ea920764abafb8c14bd6ba/pymc_marketing/mmm/delayed_saturated_mmm.py#L540-L545

That is based on the [single recursive section](https://github.com/pymc-labs/pymc-marketing/blob/b763c1207f432f17b6ea920764abafb8c14bd6ba/pymc_marketing/mmm/delayed_saturated_mmm.py#L279-L300) of that method

It might be beneficial to allow this nesting for other parameters in the model. For example, a spin on the current [gamma_control](https://github.com/pymc-labs/pymc-marketing/blob/b763c1207f432f17b6ea920764abafb8c14bd6ba/pymc_marketing/mmm/delayed_saturated_mmm.py#L546) can be viewed as hierarchical parameters for the control coefficients. Where the "gamma_control_mu" and "gamma_control_sigma" are then scaler population parameters for "gamma_control"
```python
model_config = {
    ..., 
    "gamma_control": {
        "dist": "Normal", 
        "kwargs": {
            # "mu": 0,
            "mu": {"dist": "Normal", "kwargs": {"mu": 0, "sigma": 1}}, 
            # "sigma": 2, 
            "sigma": {"dist": "HalfNormal", "kwargs": {"sigma": 1}}, 
        }, 
        # Implicit in the model to have dims=control but could be explicit as well
        # "dims": "control"
    }, 
    ..., 
}
```
Overall, think it would be easy to add and would consolidate the model_config logic in the process.
Open to other's thoughts

**Comment by wd60622** [comment]
> I've been wanting to nest distributions on the `CLV` side because Beta priors benefit from a pooled approach:
> 
> 
> 
> https://discourse.pymc.io/t/prior-distribution-for-certainty-parameter-of-beta-distribution/1071
> 
> 
> 
> However, as-written `_create_likelihood_distribution` doesn't support Beta distributions.

Good to know. Thanks for the link

Can you point out where you had this in mind in clv module for reference. 

Will Beta be the only likelihood you use? Or do they overlap with the mmm likelihood stored in that method?

In my mind, there will be some overlap in functionality so itd make sense to at least pull out the method into function. Then maybe have two separate main functions if needed

**Comment by ColtAllen** [comment]
> Can you point out where you had this in mind in clv module for reference.

`BetaGeoModel`, `ShiftedBetaGeoModelIndividual`, and the upcoming `BetaGeoBetaBinomModel` all require Beta distributions.

> Will Beta be the only likelihood you use? Or do they overlap with the mmm likelihood stored in that method?

Pooling distributions like Pareto and Uniform would also be needed. I used both in my fork of `lifetimes`:

https://github.com/ColtAllen/btyd/blob/main/btyd/models/beta_geo_model.py#L110

This was the only way I could get the MCMC posterior means to match the MAP values during testing. Right now `BetaGeoModel` will return rather different parameter estimates for both.

> In my mind, there will be some overlap in functionality so itd make sense to at least pull out the method into function. Then maybe have two separate main functions if needed

Could also move `create_likelihood_distribution` into the base `ModelBuilder` class so it's supported across the library.

**Comment by juanitorduz** [comment]
Yes! This would be great indeed!
