### ISSUE TITLE
Does pymc-marketing mmm library scale control columns?

### ISSUE THREAD

**Issue by melis-adjust** [pymc-labs/pymc-marketing#720]
Hello team,

The question is in the title. I know that it's written [here](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mmm/delayed_saturated_mmm.py#L824-L826) that you do not scale them.

However, what makes me confused is that when I check output data via this `model.compute_mean_contributions_over_time(original_scale=True)` I see different results for control contributions when original_scale=True and False. Therefore, I wanted to make sure whether control variables are scaled.

Thanks in advance for your answers annd thank you so much for this awesome library!

**Comment by juanitorduz** [comment]
We no not scale the control variables. The pre-processing steps are defined in the class definition

```python
class DelayedSaturatedMMM(
    MaxAbsScaleTarget,
    MaxAbsScaleChannels,
    ValidateControlColumns,
    BaseDelayedSaturatedMMM,
):
    ...
```

So back to your question:

> However, what makes me confused is that when I check output data via this model.compute_mean_contributions_over_time(original_scale=True) I see different results for control contributions when original_scale=True and False. Therefore, I wanted to make sure whether control variables are scaled.

Note that we also scale the target variable. So we do expect the contributions for control change with the parameter `original_scale` as this is the impact on the target :)
