### ISSUE TITLE
Fix `ParetoNBDModel` Docstring Typos

### ISSUE THREAD

**Issue by ColtAllen** [pymc-labs/pymc-marketing#727]
While working on https://github.com/pymc-labs/pymc-marketing/issues/527, I noticed some docstring typos and syntax errors for `ParetoNBDModel`. The docstrings in `BetaGeoModel` follow an identical convention and are error-free, so this would be a very quick PR fix.

**Comment by Mews** [comment]
I took a look at the docstrings and I fixed a few typos but I'm not sure if I got everything
I'll open a PR anyway so that you can take a look

**Comment by juanitorduz** [comment]
> I took a look at the docstrings and I fixed a few typos but I'm not sure if I got everything I'll open a PR anyway so that you can take a look

Thanks for the PR! We can work on iterations :)
