### ISSUE TITLE
Wrapper `Prior` / `Distribution` class

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#749]
Personally don't like writing the priors in big dictionaries. Inspired here by the bambi API 

```python
mu = Prior("Normal")
sigma = Prior("HalfNormal")
hierarchical_parameter = Prior("Normal", mu=mu, sigma=sigma, dims="channel", centered=False)
```

Honestly think this will be way shorted than dictionaries plus bring in goodies like:
- initialization check for distribution name in `pm` module 
- make use of pymc distributions having defaults
- dims will broadcast / are possible
- quick distribution creation used under hood or for checks: 
    ```python
    with pm.Model(coords={"channel": ["A", "B", "C"]}):
        alpha = hierarchical_parameter.create_variable("alpha")
    ```

This could be a documented submodule and would help demystify what goes in dictionary instead of any type of key!

This can also support post creation transformations. For instance: 
```python
positive_hierarchical_parameter = Prior("Normal", mu=mu, sigma=sigma, dims="channel", centered=False, transform="exp")
```

And some support for to and from dictionary for the serialization requirement. 

Just some thoughts after typing out many large dictionaries in #747 
CC: @carlosagostini @juanitorduz

**Comment by juanitorduz** [comment]
Yes! I love this idea! These dictionaries are growing up a lot and becoming hard to maintain! (also ... Pydantic haha)

**Comment by wd60622** [comment]
> Yes! I love this idea! These dictionaries are growing up a lot and becoming hard to maintain! (also ... Pydantic haha)

Big fan of pydantic. How does kwargs in intialization method work though?

**Comment by wd60622** [comment]
Any thoughts here @ColtAllen

**Comment by wd60622** [comment]
Think it would be interesting to also wrap it into #706 

```python
mu = Prior("Normal", mu=0, sigma=1).constraint(lower=5, upper=10)

mu.kwargs # {"mu": 7.5, "sigma": 1.25}

**Comment by ColtAllen** [comment]
> Any thoughts here @ColtAllen

It's certainly more convenient than dealing with a bunch of nested dicts in a custom model config. Is this an issue unique to `pymc-marketing`? If not it'd make more sense as a `pymc` addition.

**Comment by wd60622** [comment]
> It's certainly more convenient than dealing with a bunch of nested dicts in a custom model config. Is this an issue unique to `pymc-marketing`? If not it'd make more sense as a `pymc` addition.

I think it could definitely be used elsewhere. I think it can start here, can be pitched to larger PyMC group, then go from there
