### ISSUE TITLE
Having `pt` as default shows full module path in docs

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#769]
https://www.pymc-marketing.io/en/stable/api/generated/pymc_marketing.mmm.lift_test.calculate_lift_measurements_from_curve.html#pymc_marketing.mmm.lift_test.calculate_lift_measurements_from_curve

**Comment by radiokosmos** [comment]
Any ideas how to fix it?
I've tried several ways but none of them worked

**Comment by wd60622** [comment]
I do not. There is probably some setting in sphinx. Or maybe we use a None as default which then changes to `pt` in the case of None
