### ISSUE TITLE
Hill Saturation and Weibull adstock not showing up the gamma values

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#776]
Hello,

I was trying out the new features of applying weibull cdf and hill saturation parameters within the DelayedSaturatedMMM class as below :
```
test_mmm = DelayedSaturatedMMM(
    #model_config=my_model_config,
    target_column='Joins',
    date_column='Date',
    validate_data=True,
    channel_columns=spend_cols,
    #control_columns=control_columns,
    adstock="Weibull CDF",
    saturation="Hill",
    adstock_max_lag=10,
    yearly_seasonality=2,
    time_varying_intercept=True
)

# Fit the model on the dataset
idata = ollies_mmm.fit(X, y, target_accept=0.95, chains=4, random_seed=43)
```

But while the process is running I noticed that below are the parameters being used:
"""
```
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [intercept_time_varying_multiplier_eta, intercept_time_varying_multiplier_ls, intercept_time_varying_multiplier_hsgp_coefs, intercept_base, beta_channel, alpha, lam, gamma_fourier, likelihood_sigma]
```

I think that the hill saturation function is as below:
```
def hill_saturation(x, lam, beta, gamma):
    return beta * (x**lam) / (gamma**lam + x**lam)
```

So I would expect gamma to be a parameter too?
Am I doing something wrong here? Can someone help me with this?

**Comment by wd60622** [comment]
1. The adstock / saturation functionality is not part of 0.6.0 (current release) so youd have to install from github url
2. We are switching the class to MMM instead of DelayedSaturatedMMM. The release 0.7.0 will have a deprecation warning for the class

pip install the code from the main branch and give it a try

**Comment by shuvayan** [comment]
Ahh, got it.
Thank you for the quick revert. I wll try the github version. 
May I know the planned release date for the next version?

**Comment by shuvayan** [comment]
Closed as features will be available in the next version.

**Comment by wd60622** [comment]
> Ahh, got it.
> 
> Thank you for the quick revert. I wll try the github version. 
> 
> May I know the planned release date for the next version?

Not set in stone. Discussed about tomorrow. There are a few final edits and checks to notebooks happening. However, the code is the current main branch so id recommend pip installing directly
