### ISSUE TITLE
add_lift_measurements_to_likelihood does not work with the refactored DelayedSaturedMMM on the development branch

### ISSUE THREAD

**Issue by sangrey** [pymc-labs/pymc-marketing#789]
Hello, 
   So I've been experimenting with PyMC Marketing and recently switched over to using the development version. That version appears to have broken the `add_lift_measurements_to_likelihood_function` when used with the `MMM` class in the `DelayedSaturatedMMM` module. 
   
   In particular, I'm getting an error that the  `'MMM' object has no attribute 'named_vars_to_dims'`.  When searching throught the codebase on Github, I'm not seeing any definition of `named_vars_to_dims` that the code should be finding. 
   
Here's some code: 

```python
pip install git+https://github.com/pymc-labs/pymc-marketing

from pymc_marketing.mmm.delayed_saturated_mmm import MMM
from pymc_marketing.mmm.transformers import weibull_adstock
from pymc_marketing.mmm.lift_test import add_lift_measurements_to_likelihood

mmm = MMM(
    model_config=my_model_config,
    sampler_config=my_sampler_config,
    date_column="date_week",
    channel_columns=channels,
    control_columns=[] + holiday_names,
    adstock_max_lag=26,
    yearly_seasonality=12,
    adstock='weibull',
    saturation='michaelis_menten'
)

mmm.fit(X=X, y=y, target_accept=0.99, chains=4)

add_lift_measurements_to_likelihood(df_list_tests, 
                                      {"alpha": "alpha_in_model", "lam": "lam_in_model"},
                                  mmm.saturation,
                                    model=mmm)

```

That produces the following error: 

```python
AttributeError: 'MMM' object has no attribute 'named_vars_to_dims'
File <command-2794099507113844>, line 1
----> 1 add_lift_measurements_to_likelihood(df_list_tests, 
      2                                       {"alpha": "alpha_in_model", "lam": "lam_in_model"},
      3                                   mmm.saturation,
      4                                     model=mmm)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d8e0ebc-bbd7-4105-87ce-a0aeeeb86909/lib/python3.11/site-packages/pymc_marketing/mmm/lift_test.py:177, in indices_from_lift_tests(df_lift_test, model, var_names)
    145 def indices_from_lift_tests(
    146     df_lift_test: pd.DataFrame,
    147     model: pm.Model,
    148     var_names: list[str],
    149 ) -> Indices:
    150     """Get the indices of the lift test results in the model.
    151 
    152     These are the mapping from the lift test result to the index of the
   (...)
    172         Dictionary of indices for the lift test results in the model.
    173     """
    175     named_vars_to_dims = {
    176         name: dims
--> 177         for name, dims in model.named_vars_to_dims.items()
    178         if name in var_names
    179     }
    181     required_dims = required_dims_from_named_vars_to_dims(named_vars_to_dims)
    183     for col in required_dims:
```

**Comment by juanitorduz** [comment]
Thanks for reporting! We will take a look! 

FYI @wd60622

**Comment by wd60622** [comment]
Hi @sangrey 
That's is not the recommended workflow. Try: 
```python
mmm  = MMM(...)
mmm.build_model(X, y)
mmm.add_lift_test_measurements(df_lift_tests)
mmm.fit(X, y)
```
Here are the [methods docs](https://www.pymc-marketing.io/en/latest/api/generated/pymc_marketing.mmm.delayed_saturated_mmm.MMM.add_lift_test_measurements.html#pymc_marketing.mmm.delayed_saturated_mmm.MMM.add_lift_test_measurements) and [notebook example](https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_lift_test.html) for reference.

FYI. The mmm.model is what is passed rather than then mmm itself. mmm.model is a PyMC model which has `named_vars_to_dims`

Give that a try and let me know how it works out!

**Comment by sangrey** [comment]
I had actually did that first. 

running: 

`mmm.add_lift_measurements_to_likelihood(df_list_tests)`

gives: 

`AttributeError: 'MMM' object has no attribute 'add_lift_measurements_to_likelihood'
`

**Comment by juanitorduz** [comment]
I think the method does not have the `to_likelihood` ending. Can you try it out?

See https://www.pymc-marketing.io/en/latest/api/generated/pymc_marketing.mmm.delayed_saturated_mmm.MMM.add_lift_test_measurements.html#pymc_marketing.mmm.delayed_saturated_mmm.MMM.add_lift_test_measurements
