### ISSUE TITLE
Should unit tests live outside of the package?

### ISSUE THREAD

**Issue by lucianopaz** [pymc-labs/pymc-marketing#79]
We are shipping our the `tests` folder inside of the `pymmmc` package. I don't think is is necessary or desirable. I propose that we move the `tests` folder to the root directory instead.

Current organization:
root/
└─> pymmmc/
       └─> tests/

Proposed:
root/
├─> pymmmc/
└─> tests/

**Comment by drbenvincent** [comment]
Agree. I believe this means that the tests are not packaged up into the pypi build, which is good. 

Probably want a clear split (with folders?) between mmm and clv tests.

**Comment by ricardoV94** [comment]
Closed by #116 (there was a typo)
