### ISSUE TITLE
add ModelBuilder to documentation

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#798]
The `ModelBuilder` is not in the documentation. However, there are some references and some examples that are present in the docstrings.

Steps: 
- [ ] Add to the docs/source/api/index.md
- [ ] Use `.. code-block:: python` for examples
- [ ] Add any additional information and examples 
- [ ] Better reference to the new section

**Comment by ColtAllen** [comment]
Are there instances where you anticipate users will use the `ModelBuilder` class directly?

**Comment by wd60622** [comment]
> Are there instances where you anticipate users will use the `ModelBuilder` class directly?

Potentially. It is at least helpful reference for developers

To me, just referencing it other places in docs makes it docs-worthy
