### ISSUE TITLE
Unable to change 'method' for DelayedSaturatedMMM.plot_direct_contribution_curves() on pymc-marketing version 0.7.0

### ISSUE THREAD

**Issue by ezjsiwu** [pymc-labs/pymc-marketing#804]
Hi there I'm rebuilding my MMM in pymc-marketing version 0.7.0 due to the newly available saturation and adstock capabilities. However, when I tried using the DelayedSaturatedMMM.plot_direct_contribution_curves() it gave me an error when I want to choose the method to 'michaelis-menten'.. 
<img width="611" alt="Screenshot 2024-07-03 at 2 45 27 PM" src="https://github.com/pymc-labs/pymc-marketing/assets/168010301/8d27512d-75a0-4e03-806f-80f18e8db7c3">

**Comment by wd60622** [comment]
> Hi there I'm rebuilding my MMM in pymc-marketing version 0.7.0 due to the newly available saturation and adstock capabilities. However, when I tried using the DelayedSaturatedMMM.plot_direct_contribution_curves() it gave me an error when I want to choose the method to 'michaelis-menten'.. 
> 
> <img width="611" alt="Screenshot 2024-07-03 at 2 45 27 PM" src="https://github.com/pymc-labs/pymc-marketing/assets/168010301/8d27512d-75a0-4e03-806f-80f18e8db7c3">
> 
> 

Are you calling the method on the class itself? Or on an instance of the class?

**Comment by ezjsiwu** [comment]
hi Will, thanks for your response.. i'm calling on the method on the class itself.. 
Here's the code for my model config..
`mmm = MMM(
    model_config = my_model_config,
    sampler_config = sampler_config,
    date_column="week",
    channel_columns=spend_cols,
    control_columns=control_cols,
    adstock="geometric", 
    saturation="logistic",
    adstock_max_lag=10,
    yearly_seasonality=10
)

mmm.build_model(X_train, y_train)


df_lift_test = pd.DataFrame.from_dict({
        "channel": ['spend_youtube','spend_linkedin','spend_facebook'],
        "x": [75900,48863.60,80000],
        "delta_x": [91000,10433,12000],
        "delta_y": [300,857,50],
        "sigma": [72,102,18]
    })

mmm.add_lift_test_measurements(df_lift_test)

mmm.fit(X=X_train, y=y_train, target_accept=0.90, chains=4, draws=1000, random_seed=123)

mmm.sample_posterior_predictive(X_train, extend_idata=True, combined=True)
`

Model was fitted fine and had acceptable results.. I just wasn't able to use the plot_direct_contribution_curve using  method.. I ran this same exact code in version 0.6.0 and it worked fine..
`mmm.plot_direct_contribution_curves(show_fit=True, method='sigmoid',xlim_max=3,same_axes=False)`

**Comment by wd60622** [comment]
> Model was fitted fine and had acceptable results.. I just wasn't able to use the plot_direct_contribution_curve using  method.. I ran this same exact code in version 0.6.0 and it worked fine..
> 
> `mmm.plot_direct_contribution_curves(show_fit=True, method='sigmoid',xlim_max=3,same_axes=False)`

Try it without the method keyword then. It seems to have been dropped as the fit curve will come from 'saturation' specified at initialization.

**Comment by juanitorduz** [comment]
Yes we can do this!

**Comment by ezjsiwu** [comment]
That works! Thanks @wd60622 :)
