### ISSUE TITLE
Wrong type hint for samples in `plot_budget_allocation` and `plot_allocated_contribution_by_channel`

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#821]
samples is actually Dataset rather than InferenceData

https://github.com/pymc-labs/pymc-marketing/blob/d766722da45eee10c8049da0b18d3d9844d29df9/pymc_marketing/mmm/delayed_saturated_mmm.py#L2030-L2032

Same here: 
https://github.com/pymc-labs/pymc-marketing/blob/d766722da45eee10c8049da0b18d3d9844d29df9/pymc_marketing/mmm/delayed_saturated_mmm.py#L2129-L2131

**Comment by Ishaanjolly** [comment]
hey, I am a newbie, I'd love to contribute to PyMC and have been following for a long time. How can I connect with you to deal with this GitHub issue?

**Comment by wd60622** [comment]
> hey, I am a newbie, I'd love to contribute to PyMC and have been following for a long time. How can I connect with you to deal with this GitHub issue?

Hi @Ishaanjolly 
Thank you for your interest! It'd be great to have this contribution from you
Follow this guide here: https://github.com/pymc-labs/pymc-marketing/blob/main/CONTRIBUTING.md
After the fork and creation of a branch, push it up and open a PR even if it is in early stages so that we can help you and provide feedback
