### ISSUE TITLE
saving with media transformation config

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#826]
MMM with `adstock` and `saturation` configurations can potentially not be saved correctly since the additional kwargs are not saved off. 

 Having these classes serializable and taking advantage of them in `save` and `load` methods would be a good idea.

 For instance, a model that would not be able to be loaded correctly would be:

 ```python
 from pymc_marketing.mmm import MMM, GeometricAdstock, LogisticSaturation

 mmm = MMM(
     ..., 
     adstock=GeometricAdstock(l_max=4, normalize=False, mode="Before"), 
     saturation=LogisticSaturation(),
     ..., 
)
```

This is because both the `normalize` and `mode` are not saved off.

This would involve reconstructing the `adstock` and `saturation` upon loading here: 

https://github.com/pymc-labs/pymc-marketing/blob/2be2664557fa84471e448d9ba12fe78ccacd69f3/pymc_marketing/mmm/delayed_saturated_mmm.py#L637-L659

**Comment by wd60622** [comment]
Think that this is rather important but the version of the model will likely have to be updated. Making the previous version not able to be reloaded. 
Have any thoughts on this @juanitorduz ?

**Comment by wd60622** [comment]
There might be a benefit of having a to_json and from_json on the classes directly

**Comment by juanitorduz** [comment]
Yes! Even though we "break" some model versions, we should fix this so that we can recover the complete (and consistent!) model.
