### ISSUE TITLE
Decide how to handle `date_column` dtype and transformations

### ISSUE THREAD

**Issue by lucianopaz** [pymc-labs/pymc-marketing#83]
At the moment, the `date_column` is left untouched in the data. This might be ok, but it would be great to support `datetime` dtypes as inputs. Those can be easily handled in plots of time series, and they are more natural to reason about as opposed to floating point arrays referenced to some onset event and using some unknown resolution in some unknown time zone. The difficulty of supporting `datetime` dtypes is that we need to:

1. Ensure that the `date_column` is a date time compatible dtype
2. Convert it to a `datetime` if it isn't using some string format?
3. Add a transformation to go from datetimes to floating point arrays and back. This is necessary if we want to have time series with seasonal components or other mathematical dependencies on time.

**Comment by wd60622** [comment]
Added by @juanitorduz in f17d9902
