### ISSUE TITLE
Model Diagnostics Tests

### ISSUE THREAD

**Issue by shuvayan** [pymc-labs/pymc-marketing#832]
Hello,

I could not find any statistical tests to validate my bayesian model.

For example , LOO or KL Divergence Maybe. 
I tried the tests in the pymc link below :

[https://pymcmc.readthedocs.io/en/latest/modelchecking.html](url)

but I don't think these work anymore.
Is there a way I can test my model diagnostics using statistical tests if any

**Comment by wd60622** [comment]
For loo, try this
https://github.com/pymc-labs/pymc-marketing/discussions/805

**Comment by wd60622** [comment]
Hi @shuvayan 
Any luck with this?

**Comment by shuvayan** [comment]
Hey @wd60622 ,

My apologies, I have not been able to look into it further. 
I am closing this for now , but keeping it in my log of to do please.

But if you think otherwise, kindly reopen.
