### ISSUE TITLE
Documentation Visual for `hill_saturation` function

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#851]
The adstock and saturation tranformations in the transformers module all display example 
parameter values in order to display the shape of function. However, hill is not implemented or not displayed. 

This should be added to the docstring of the `hill_saturation` function

The requirements here: 
- match the style of the other functions in the module
- display handful of different parameter values to show the shape of the function

The most similar function would be the `michaelis_menten` since `alpha` and `sigma` are both scaling parameters.

**Comment by PatrickRobotham** [comment]
The issue is caused by the plotting code for `hill_saturation` having a bug. 
I've submitted a PR here https://github.com/pymc-labs/pymc-marketing/pull/857
