### ISSUE TITLE
support for more dims in pymc_marketing\model_config.py

### ISSUE THREAD

**Issue by lorenze3** [pymc-labs/pymc-marketing#871]
Howdy,

Trying to follow the example [here](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_components.html) with a larger list of dimensions and I encountered this message:

>   File "C:\Users\Lorenzt01\PycharmProjects\pymcmarketinghierarchy\.venv\Lib\site-packages\pymc_marketing\model_config.py", line 210, in create_dim_handler
>     raise UnsupportedShapeError(
> pymc_marketing.model_config.UnsupportedShapeError: At most two dims can be specified. Raise an issue if support for more dims is needed.
> 

My use case does in fact involve more than two dims; I'm quite certain a workaround will be findable, but I do like to follow directions.  FWIW, this pymc version 5.15.1 and pymc-marketing 0.7.0.

Thanks for all the work on a lovely software package!
TL

**Comment by wd60622** [comment]
Hi @lorenze3 

This is solved with the Prior class. Have your tried the example on the latest / main branch instead of 0.7.0?

**Comment by lorenze3** [comment]
If I flip the documentation URL over to /latest/ instead of /stable/, I can see that there have been (or will be?) changes, but I haven't managed to get a different version of the package installed. Iam not finding a 'how to install dev version' or 'nightly release' version anywhere.  0.7.0 _is_ the current latest version, yes?

I can work through a non-dim and coord- approach to building my model and wait for the changes to work there way through the system.

**Comment by lorenze3** [comment]
Ok, I've managed to get that example (the version here: https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_components.html ) running by just running the modules out of a download of the main branch of the repo. . . I'll try my 'many many dimensions' using the Prior class -- thanks for the pointer!.

**Comment by wd60622** [comment]
Correct, 0.7.0 is the latest version at the moment. I will make a release shortly which will include the Prior class as well.

Happy to hear that you got it running. If you have any issues with the new class, feel free to raise another issue!
