### ISSUE TITLE
Graphviz Not Working for Model Graphs

### ISSUE THREAD

**Issue by louismagowan** [pymc-labs/pymc-marketing#889]
Hi there - the model graphs with GraphViz seem to not be working. Any tips would be much appreciated! 🙇‍♂️ 

I've built my MMM using
```
from pymc_marketing.mmm import (
    MMM,
    GeometricAdstock,
    LogisticSaturation,
)

mmm = MMM(
    date_column=c.DATE_COLUMN,
    channel_columns=FEATURES["ft_paid"] + FEATURES["ft_organic"] + FEATURES["ft_competitor"],
    control_columns=FEATURES["ft_control"] + ["trend"],
    adstock_max_lag=8,
    adstock=GeometricAdstock(l_max=8),
    saturation=LogisticSaturation(),
    yearly_seasonality=SEASONALITY_CONFIG["seasonality_n_order"],
    time_varying_intercept=False,
    time_varying_media=False,
    adstock_first=True,
    sampler_config=SAMPLER_CONFIG,
)
```

`pm.model_to_graphviz(model=mmm)` and `mmm.graphviz` don't seem to work

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/297a3fc0-45e4-49e8-be00-bdf755bcccbb">

**Comment by wd60622** [comment]
> Hi there - the model graphs with GraphViz seem to not be working. Any tips would be much appreciated! 🙇‍♂️
> 
> I've built my MMM using
> 
> ```
> from pymc_marketing.mmm import (
>     MMM,
>     GeometricAdstock,
>     LogisticSaturation,
> )
> 
> mmm = MMM(
>     date_column=c.DATE_COLUMN,
>     channel_columns=FEATURES["ft_paid"] + FEATURES["ft_organic"] + FEATURES["ft_competitor"],
>     control_columns=FEATURES["ft_control"] + ["trend"],
>     adstock_max_lag=8,
>     adstock=GeometricAdstock(l_max=8),
>     saturation=LogisticSaturation(),
>     yearly_seasonality=SEASONALITY_CONFIG["seasonality_n_order"],
>     time_varying_intercept=False,
>     time_varying_media=False,
>     adstock_first=True,
>     sampler_config=SAMPLER_CONFIG,
> )
> ```
> 
> `pm.model_to_graphviz(model=mmm)` and `mmm.graphviz` don't seem to work
> 
> <img alt="image" width="1212" src="https://private-user-images.githubusercontent.com/59659198/353503189-297a3fc0-45e4-49e8-be00-bdf755bcccbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTA4NTUsIm5iZiI6MTcyMjM1MDU1NSwicGF0aCI6Ii81OTY1OTE5OC8zNTM1MDMxODktMjk3YTNmYzAtNDVlNC00OWU4LWJlMDAtYmRmNzU1YmNjY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0NDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MDc4ZjBlNzMwNzQ1ZmUyYjIwZThhYWE5MjhkZjE0M2QwNzVlMTkxZTQ3Y2U0N2RkMzE2NzFlZWU5MmJkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vcIyxfwtvmZzPVesUKSYp2ButBmRx75qmiu8E05klNo">

Pass `mmm.model` instead of `mmm` itself. 
Or use the `mmm.graphviz` method

**Comment by louismagowan** [comment]
Ahh sorry yes - the issue wasn't in the method (one of my cols had a sneaky negative value and the model wasn't being created when instantiating `MMM()`

**Comment by louismagowan** [comment]
It's fixed! Thanks haha
