### ISSUE TITLE
Remove "Sampling: []" with `plot_channel_contributions_grid` method

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#896]
The calls to `sample_posterior_predictive` produce "Sample: []" many times which is distracting. This should be removed somehow

Example: https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#media-deep-dive

**Comment by Ishaanjolly** [comment]
Looks a some loop gone wrong. Can I deal with this issue?

**Comment by wd60622** [comment]
> Looks a some loop gone wrong. Can I deal with this issue? 

Sure! Thanks @Ishaanjolly

**Comment by Ishaanjolly** [comment]
@wd60622  Sorry I have been away for couple of weeks - this `Sampling: []` is not just present in your link, but in many other notebooks. How would you like me to approach this?

**Comment by Ishaanjolly** [comment]
`mmm_components.ipynb` and `mmm_example.ipynb` specifically.

**Comment by PabloRoque** [comment]
Hello. I took the liberty to create #1043. 
Sorry to step in uninvited, I was having a look at code around this functionality and came up with a potential fix.

**Comment by Ishaanjolly** [comment]
Glad you did. I was a bit slow! I'll just do some other issue :)
