### ISSUE TITLE
Additional Customisation on Adstock x Saturation

### ISSUE THREAD

**Issue by louismagowan** [pymc-labs/pymc-marketing#903]
Hello!

**1. `adstock_first` customisability in MMM class**
Is there a way to specify this per channel? Currently, it seems to be controlled by a bool which sets the same order across all channels. Would it be possible to change it to make it an array of bools so that users can choose specific channels to saturate and adstock vs which ones to adstock and then saturate?

**2. `adstock_max_lag` customisability in MMM class**
Similar to point 1, is it possible to specify this per channel rather than as a bool that's constant across all channels?

**3. `adstock_max_lag` arg repeated twice**
When you pass in the `AdstockTransformation` class into the `adstock` arg in `MMM`, you have to specify twice the `adstock_max_lag` - once in the MMM arg, and once in the `AdstockTransformation` object itself. Is there a reason for this? It's not obvious from the docstring which of the two you pass in takes precedence.

Could we perhaps remove this argument from MMM, as well as the string support for specifying adstock and saturation in MMM and instead encourage people to specify them as classes themselves directly (in the documentation, such as MMM example doc)? I feel like this would encourage people towards leveraging the really cool customisation features that you guys have added, as well as maybe being an easier model specification experience.
e.g. Instead of
```
mmm = MMM(
    model_config=my_model_config,
    sampler_config=my_sampler_config,
    date_column="date_week",
    adstock="geometric",
    saturation="logistic",
    channel_columns=["x1", "x2"],
    control_columns=[
        "event_1",
        "event_2",
        "t",
    ],
    adstock_max_lag=8,
    yearly_seasonality=2,
)
```

It becomes
```
adstock = DelayedAdstock(l_max=10)
saturation = LogisticSaturation()

mmm = MMM(
    model_config=my_model_config,
    sampler_config=my_sampler_config,
    date_column="date_week",
    adstock=adstock,
    saturation=saturation,
    channel_columns=["x1", "x2"],
    control_columns=[
        "event_1",
        "event_2",
        "t",
    ],
    yearly_seasonality=2,
)
```

**Comment by juanitorduz** [comment]
Good points!

**Comment by wd60622** [comment]
The `adstock_max_lag` initialization parameter is deprecated / *should* warn that the class definition is recommended.
The reason for going with the class isinitialziation is that there is additional parameters to the Adstock classes that don't exist as init params. Can you link any documentation where this is duplicated? @louismagowan

**Comment by louismagowan** [comment]
Thanks for the info! 😁 

Docs I found:
- [BaseMMM docstring](https://github.com/pymc-labs/pymc-marketing/blob/dffae874f94a115f34e06709f37297a91df74fbc/pymc_marketing/mmm/delayed_saturated_mmm.py#L84-L90)
- [MMM Example Doc](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#id1) uses string adstock and saturation with separate max_lag
- [Lift Test Doc](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_lift_test.html) uses string adstock and saturation with separate max_lag


Also - I don't seem to get a deprecation warning when fitting or building the model and using string specification?

<img width="698" alt="image" src="https://github.com/user-attachments/assets/b02abcb6-379a-453b-987a-8a80db410ac6">

**Comment by wd60622** [comment]
> Thanks for the info! 😁 
> 
> 
> 
> Docs I found:
> 
> - [BaseMMM docstring](https://github.com/pymc-labs/pymc-marketing/blob/dffae874f94a115f34e06709f37297a91df74fbc/pymc_marketing/mmm/delayed_saturated_mmm.py#L84-L90)
> 
> - [MMM Example Doc](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#id1) uses string adstock and saturation with separate max_lag
> 
> - [Lift Test Doc](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_lift_test.html) uses string adstock and saturation with separate max_lag
> 
> 
> 
> 
> 
> Also - I don't seem to get a deprecation warning when fitting or building the model and using string specification?
> 
> 
> 
> <img width="698" alt="image" src="https://github.com/user-attachments/assets/b02abcb6-379a-453b-987a-8a80db410ac6">
> 
> 

Is that the example notebook? Doesnt it have ignoring of warning put at the top?

**Comment by louismagowan** [comment]
Oh nah this is from my notebook, no warning filter applied ☺️

**Comment by wd60622** [comment]
> Oh nah this is from my notebook, no warning filter applied ☺️

Sounds good. Thanks for updating

NOTE: I think notebooks have some amount of auto filtering. We should probably try to override and force deprecation warnings as many will likely use notebooks

**Comment by wd60622** [comment]
Hi @louismagowan 
Can we close this or make it a bit more specific

**Comment by louismagowan** [comment]
Hey @wd60622  - I believe that more flexible adstock and saturation is already in the works for you guys right?

I do think that having the option to specify the order of saturation and adstock per channel, as well as l_max per channel, would add value. But I think that's already being tackled elsewhere, in which case I'm happy to close this

**Comment by wd60622** [comment]
Yes, much of that tooling exists just maybe not all in MMM. If there are specifics, lets break down into smaller issues. 

Lets close this in favor of smaller issues

**Comment by louismagowan** [comment]
Ok all good! Thanks 😁
