### ISSUE TITLE
Optional Negative Values in MMM Channels

### ISSUE THREAD

**Issue by louismagowan** [pymc-labs/pymc-marketing#915]
Currently the MMM by default informs our channels to be >=0 via the HalfNormal and inclusion of only non-negative values (see [`ValidateChannelColumns`](https://github.com/pymc-labs/pymc-marketing/blob/6779fd152c1c62f4c51ba42c38cc10ee57bab693/pymc_marketing/mmm/validating.py#L77-L79).

However, the opposite could be true for certain variables. For example, you might believe that the amount your competitors are spending on your Brand keywords in Search Engine Advertising could only have a negative or 0 effect on your target metric.

It would be nice to have an option to pass in a column of negative values, such that the effect of that channel is negative overall (since we don't need to change from the default HalfNormal prior, we can just multiply).

It could look something like this

```
mmm = MMM(
    date_column="date",
    channel_columns=["facebook", "google", "competitor",...],
    control_columns=["control_1", "control_2"]
    allow_negative_columns=["competitor"]
    adstock=my_adstock,
    saturation=my_saturation,
    adstock_max_lag=4,
)
```

I think it should be straightforward to extend [`ValidateChannelColumns`](https://github.com/pymc-labs/pymc-marketing/blob/6779fd152c1c62f4c51ba42c38cc10ee57bab693/pymc_marketing/mmm/validating.py#L77-L79) to allow for negative columns.

I'm happy to work on this PR, perhaps with Ruari from Qonto too 😁

**Comment by wd60622** [comment]
Can you negate the controls in the DataFrame and use `validate_data` = False? Does that work?

**Comment by louismagowan** [comment]
Hey @wd60622 your tip works, thanks! I still think it might be nice behaviour to let users select certain columns not to validate, or pass as negative etc rather than a blanket validate all vs validate none.

^If nobody takes this, I'd still be interested in doing this at some point ☺️
