### ISSUE TITLE
does hill_sat go through (0, 0)

### ISSUE THREAD

**Issue by dirknbr** [pymc-labs/pymc-marketing#917]
Is it possible that your hill_saturation function doesn't pass through (0, 0), which would be necessary since we assume 0 sales if a single channel is 0

![Screenshot from 2024-08-07 16-36-12](https://github.com/user-attachments/assets/4198688d-0cf9-44d3-b90d-b085002761dc)

**Comment by juanitorduz** [comment]
Thanks for reporting this @dirknbr ! We have a fix in https://github.com/pymc-labs/pymc-marketing/pull/920

**Comment by dirknbr** [comment]
but does this fix mean that sigma is still the aymptote for all positive values of lambda and beta?

**Comment by juanitorduz** [comment]
> but does this fix mean that sigma is still the aymptote for all positive values of lambda and beta?

Actually, is going to be sigma minus the offset. Let me reopen this issue and see is we bring the original parametrization.

**Comment by dirknbr** [comment]
why not use equation 4 of https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46001.pdf

**Comment by juanitorduz** [comment]
Ok! Seems the way to go. I am unsure about the current parameterization via exponentials.

**Comment by juanitorduz** [comment]
> why not use equation 4 of https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46001.pdf

Ok! Sterted a PR https://github.com/pymc-labs/pymc-marketing/pull/925

**Comment by juanitorduz** [comment]
We added the original implementation of the paper (with the corresponding reference)
