### ISSUE TITLE
budget_optimizer logic doesn't make sense when applied to DelayedSaturatedMMM model. 

### ISSUE THREAD

**Issue by patrick-immensityforartists** [pymc-labs/pymc-marketing#927]
Suppose we have 2 marketing channels:

`X1`
`X2`

Now, suppose we create a **delayed_saturated_mmm** model and call `fit()`. The `_generate_and_preprocess_model_data()` that gets invoked calls the `max_abs_scale_channel_data` in **preprocessing.py**. This method applies max-abs scaling WITHIN each channel. Therefore, the `saturation_beta` and `saturation_lam parameters` are relative to the maximum spend of that particular channel. 

Now, let's consider the `allocate_budget_to_maximize_response()` method in **delayed_saturated_mmm.py**

This method recovers the channel-specific `saturation_beta` and `saturation_iam` parameters from the model. It then scales the total budget and the bounds ACROSS the groups. Then, the transformations are applied to a series of spend data on this across-channel scale. 

By scaling the data across the groups, it doesn't make sense to apply saturation and calculate contributions using the recovered parameters because the recovered parameters were specific to scaling WITHIN groups. Both the `saturation beta` and `saturation_lam` parameters are specific to the scale of the data.

**Comment by shuvayan** [comment]
Hello @wd60622 ,
It seems there are two ways (we need to select either ) to fix this:
1. Consistently scale the data within channels or across channels throughout the process, or
2. Adjust the recovered parameters to match the scaling context used during budget allocation.

Kindly suggest so that we can fix this (only if this is something already taken care of and can be invoked by using the appropriate methods).

**Comment by cetagostini** [comment]
Hey @patrick-immensityforartists and @shuvayan 

Indeed, the optimizer scales where not properly align. We solve the issue in [the following PR](https://github.com/pymc-labs/pymc-marketing/pull/933).

You can check and correct the implementation but should be merge soon.

**Comment by cluhmann** [comment]
Is this issue still open or did https://github.com/pymc-labs/pymc-marketing/pull/933 fix it?

**Comment by cetagostini** [comment]
Fixed already!

**Comment by cluhmann** [comment]
So can we close this?
