### ISSUE TITLE
Stale `mmm_tvp_example` notebook

### ISSUE THREAD

**Issue by ilaria-giunti** [pymc-labs/pymc-marketing#930]
## Summary

The TVP notebook [here](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_tvp_example.html) makes edits to `model_config` as if it is the older, dictionary format. This needs to be updated to the `Prior` class at least in the `create_and_fit_MMM` function. 

There could be some additional steps required. But it would likely look like: 

- [ ] Add `Prior` import at top of notebook
- [ ] Use `Prior` instead of dictionary syntax for the model_config alterations
- [ ] Make sure that the whole notebook runs top to bottom

## Original Message
Why do I have this error when I try to have my mmm?
this is the error: TypeError: 'Prior' object does not support item assignment

and this is the function
```python
def create_and_fit_MMM(data: pd.DataFrame, target: pd.Series) -> DelayedSaturatedMMM:
    mmm = DelayedSaturatedMMM(
        date_column="Weeks",
        channel_columns=COORDS["media"],
        control_columns=COORDS["control"],
        adstock_max_lag=10,
        time_varying_intercept=True,
        sampler_config={
            "chains": 4,
            "draws": 4000,
            "tune": 1000,
            "nuts_sampler": "numpyro",
        },
    )
    mmm.model_config["intercept"]["dist"] = "HalfNormal"
    mmm.model_config["intercept"]["kwargs"] = {"sigma": 5}
    mmm.fit(data, target)
    return mmm


mmm_seasonal = create_and_fit_MMM(data_train, data_train["target_seasonal"])
```

**Comment by wd60622** [comment]
Hi @ilaria-giunti 

Thanks for raising

Can you post the full traceback

**Comment by wd60622** [comment]
Think I know what it is. Take a look at the mmm.model_config. It now uses the Prior class for each of the distributions. You will will have to define the whole value ie `mmm.model_config["intercept"] = Prior("HalfNormal", ...)`

**Comment by ilaria-giunti** [comment]
but I'm following this code: https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_tvp_example.html

and i have the error of Prior
![image](https://github.com/user-attachments/assets/6e6ae120-513c-4606-919a-caded9b41766)

**Comment by wd60622** [comment]
Can you post the error message instead of the code 🙏

**Comment by wd60622** [comment]
I am seeing that is is a stale notebook. 

Can you try the solution `mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)` and report if that works

**Comment by wd60622** [comment]
```python
from pymc_marketing.prior import Prior
```

**Comment by ilaria-giunti** [comment]
but it says not mmm is not defined 

mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)

NameError: name 'mmm' is not defined

**Comment by wd60622** [comment]
> but it says not mmm is not defined
> 
> mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)--------------------------------------------------------------------------- NameError Traceback (most recent call last) Cell In[9], line 1 ----> 1 mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)
> 
> NameError: name 'mmm' is not defined

You will likely have to rerun the reload the notebook or make sure that that mmm variable is defined outside of the function

**Comment by ilaria-giunti** [comment]
import warnings
from datetime import date

import arviz as az
import matplotlib.pylab as plt
import numpy as np
import numpy.typing as npt
import pandas as pd
import pymc as pm

from pymc_marketing.mmm import DelayedSaturatedMMM

from pymc_marketing.prior import Prior

SEED = sum(map(ord, "Time varying parameters are awesome!"))
rng = np.random.default_rng(SEED)

warnings.filterwarnings("ignore")

az.style.use("arviz-darkgrid")
plt.rcParams["figure.figsize"] = [12, 7]
plt.rcParams["figure.dpi"] = 100

%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = "retina";

DATA = pd.read_csv("mock_cgp_data-no-target.csv", parse_dates=["Weeks"])

# Define which columns are media and control
COORDS = {
    "media": ["Google Search", "DV360", "Facebook", "AMS", "TV", "VOD", "OOH", "Radio"],
    "control": ["Numeric Distribution", "RSP", "Promotion"],
    "week": DATA["Weeks"],
}

DATA.head()

fig, ax = plt.subplots()
DATA.set_index("Weeks").plot(ax=ax)
ax.set_title("Time series of the data")
ax.set_ylabel("Spending")
ax.legend(loc="center left", bbox_to_anchor=(1, 0.5));

def synthesize_and_plot_target(synthetic_intercept: npt.NDArray) -> npt.NDArray:
    # Create the model, with channel spend, control variables, adstock, and yearly seasonality.
    # This model is **structurally identical** to the model we will fit a couple of cells below.
    mmm_synth = DelayedSaturatedMMM(
        date_column="Weeks",
        channel_columns=COORDS["media"],
        control_columns=COORDS["control"],
        adstock_max_lag=10,
        time_varying_intercept=True,
    )

    mmm_synth.build_model(DATA, np.ones(DATA.shape[0]))

    # Synthetic model parameters. These are largely arbitrary, though chosen to be somewhat realistic.
    synthetic_params = {
        "intercept": synthetic_intercept,
        "saturation_beta": np.array([3.5, 2.0, 5.0, 3.2, 1.5, 2.0, 1.0, 1.5]) * 4,
        "adstock_alpha": np.array([0, 0.5, 0.1, 0.1, 0.9, 0.5, 0.9, 0.95]),
        "saturation_lam": 1 / (DATA[COORDS["media"]].mean(0)).values,
        "y_sigma": 0.25,
    }

    # Manually set the model parameters. The `do` operator returns a new model where the parameters
    # which were supplied are deterministic.
    true_model = pm.do(
        mmm_synth.model,
        synthetic_params,
    )

    # Draw the target series from the model
    target = pm.draw(true_model.y, random_seed=SEED)

    # Plot the simulated target series
    fig, ax = plt.subplots()
    ax.set_title("Target")
    ax.plot(DATA.Weeks, target, label="Sales")
    ax.plot(DATA.Weeks, synthetic_intercept, label="Synthetic intercept")
    ax.legend()

    return target


# Define a synthetic time-varying intercept. In this first example, we set the intercept
# to be a cosine wave with a period of 52.18 weeks (1 year) which oscillates around 5.
N = DATA.shape[0]
synthetic_intercept_seasonal = (
    np.cos(2 * np.pi / 52.18 * np.arange(N)) / 2 + 1
) * 5  # 👈 Intercept that oscillates around 5

DATA["target_seasonal"] = synthesize_and_plot_target(synthetic_intercept_seasonal)

SPLIT_N = 52
data_train = DATA.iloc[:-SPLIT_N]
data_test = DATA.iloc[-SPLIT_N:]

mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)

---> here is the code

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)

NameError: name 'mmm' is not defined

**Comment by wd60622** [comment]
You would want to add that in the function where `mmm` is a local variable

**Comment by ilaria-giunti** [comment]
I didn't get it

**Comment by ilaria-giunti** [comment]
thank you!

**Comment by ilaria-giunti** [comment]
mmm_seasonal = create_and_fit_MMM(data_train, data_train["target_seasonal"])

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], [line 1](vscode-notebook-cell:?execution_count=11&line=1)
----> [1](vscode-notebook-cell:?execution_count=11&line=1) mmm_seasonal = create_and_fit_MMM(data_train, data_train["target_seasonal"])

Cell In[10], [line 16](vscode-notebook-cell:?execution_count=10&line=16)
      [2](vscode-notebook-cell:?execution_count=10&line=2) mmm = DelayedSaturatedMMM(
      [3](vscode-notebook-cell:?execution_count=10&line=3)     date_column="Weeks",
      [4](vscode-notebook-cell:?execution_count=10&line=4)     channel_columns=COORDS["media"],
   (...)
     [13](vscode-notebook-cell:?execution_count=10&line=13)     },
     [14](vscode-notebook-cell:?execution_count=10&line=14) )
     [15](vscode-notebook-cell:?execution_count=10&line=15) mmm.model_config["intercept"] = Prior("HalfNormal", sigma=5)
---> [16](vscode-notebook-cell:?execution_count=10&line=16) mmm.fit(data, target)
     [17](vscode-notebook-cell:?execution_count=10&line=17) return mmm

File /opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:544, in ModelBuilder.fit(self, X, y, progressbar, predictor_names, random_seed, **kwargs)
    [542](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:542) sampler_args = {**self.sampler_config, **kwargs}
    [543](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:543) with self.model:
--> [544](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:544)     idata = pm.sample(**sampler_args)
    [546](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:546) if self.idata:
    [547](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc_marketing/model_builder.py:547)     self.idata = self.idata.copy()

File /opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc/sampling/mcmc.py:721, in sample(draws, tune, chains, cores, random_seed, progressbar, progressbar_theme, step, var_names, nuts_sampler, initvals, init, jitter_max_retries, n_init, trace, discard_tuned_samples, compute_convergence_checks, keep_warning_stat, return_inferencedata, idata_kwargs, nuts_sampler_kwargs, callback, mp_ctx, blas_cores, model, **kwargs)
    [717](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc/sampling/mcmc.py:717)         raise ValueError(
...
---> [24](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc/sampling/jax.py:24) import jax
     [25](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc/sampling/jax.py:25) import jax.numpy as jnp
     [26](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/marketing_env/lib/python3.12/site-packages/pymc/sampling/jax.py:26) import numpy as np

ModuleNotFoundError: No module named 'jax'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?d99ee334-58b7-4c34-a1c7-dbc6b4d8dd38) or open in a [text editor](command:workbench.action.openLargeOutput?d99ee334-58b7-4c34-a1c7-dbc6b4d8dd38). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by wd60622** [comment]
That's a separate package that needs to be installed. Try install our conda env
