### ISSUE TITLE
mlflow module not showing up on the documentation page

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#932]
The `mlflow` module has not been showing up in the documentation even with the merge to the main branch. View the documentation [here](https://www.pymc-marketing.io/en/latest/api/index.html).

This would want to be added such that it displays.

**Comment by wd60622** [comment]
Would @OriolAbril understand why this is not showing up

**Comment by OriolAbril** [comment]
sphinx autodoc imports the objects it documents, and it is not being able to import it given mlflow is needed but it is not installed in the docs env.

There are two options:

* add mlflow to the doc env
* use [autodoc_mock_imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) to mock it and avoid the import error

I'd probably try the mock option and check what happens with the docs of [autolog](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mlflow.py#L395), if the decorator modifies the docstrings/methods dynamically it might end up looking weird when that doesn't happen.

**Comment by wd60622** [comment]
> sphinx autodoc imports the objects it documents, and it is not being able to import it given mlflow is needed but it is not installed in the docs env.
> 
> There are two options:
> 
> * add mlflow to the doc env
> * use [autodoc_mock_imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) to mock it and avoid the import error
> 
> I'd probably try the mock option and check what happens with the docs of [autolog](https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/mlflow.py#L395), if the decorator modifies the docstrings/methods dynamically it might end up looking weird when that doesn't happen.

You are a lifesaver! Will try out these suggestions

**Comment by wd60622** [comment]
There might be a conflict since the package name is `mlflow` and our module is also same name. Giving the auto_mock_imports a try first

**Comment by wd60622** [comment]
Thanks @OriolAbril !
