### ISSUE TITLE
Question on lift test calibration

### ISSUE THREAD

**Issue by iraur** [pymc-labs/pymc-marketing#948]
Hello! 

This is more a question than an issue, relating to lift test calibration. I really like this feature and [this doc](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_lift_test.html#about-lift-tests) is great, but it wasn't so clear to me what my pre-test channel spend should be.

Suppose I am modelling at a weekly level and I have the results of a 6 week test in which a certain channel spend was reduced to 0. What should my pre-test spend, `x`, be? Is it the spend in the 6 weeks before the test or is it an averaged weekly value? Similarly, should my `delta_y` be a total or a weekly average?

Thanks!

**Comment by wd60622** [comment]
I have in my mind that they are averages. They are being evaluated on the saturation curve itself so total (or sum(x)) would be in a different scale and wouldn't make sense. 

I suspect the noise would just need to be adjusted accordingly. 6 week test = less variation

WDYT?

**Comment by iraur** [comment]
Yes, great, that makes sense to me - thanks! I guess my weekly sigma here would be total sigma divided by sqrt(6). Thanks again @wd60622 🙂

**Comment by iraur** [comment]
Closing this after confirming with @wd60622
