### ISSUE TITLE
Reproducibility Issues in mmm.fit()

### ISSUE THREAD

**Issue by louismagowan** [pymc-labs/pymc-marketing#958]
Hi there! I seem to be unable to reproduce my MMMs across runs. Similarly, I'm unable to reproduce the results obtained in the PyMC-Marketing example notebook. 

Any advice on how to resolve this would be greatly appreciated! 🙏 

It seems like my rng is not being applied correctly when I call mmm.fit().

Evidence in screenshots, notice e.g. how adstock_alpha changes:
![image](https://github.com/user-attachments/assets/035faee7-863d-447d-ada5-e3d460cedbda)
![image](https://github.com/user-attachments/assets/f4426323-bb68-4cec-9a8c-6722a557e9eb)

```
import pymc as pm
import pymc_marketing
print(pm.__version__)
print(pymc_marketing.__version__)

# Create MMM with pymc-marketing
mmm = MMM(
    date_column=c.DATE_COLUMN,
    channel_columns=FEATURES["ft_channels"],
    control_columns=FEATURES["ft_control"] + ["trend"],
    adstock="geometric",
    saturation="logistic",
    adstock_max_lag=4,
    sampler_config={"progressbar": False},
    validate_data=False, # Necessary to allow negative competitor spend
)


# Run MMM with the experiment results included
rng: np.random.Generator = np.random.default_rng(seed=42)
idata = mmm.fit(X_train, y_train, random_seed=rng)

idata.posterior.adstock_alpha.mean()


# Create MMM with pymc-marketing
mmm = MMM(
    date_column=c.DATE_COLUMN,
    channel_columns=FEATURES["ft_channels"],
    control_columns=FEATURES["ft_control"] + ["trend"],
    adstock="geometric",
    saturation="logistic",
    adstock_max_lag=4,
    sampler_config={"progressbar": False},
    validate_data=False, # Necessary to allow negative competitor spend
)


# Run MMM with the experiment results included
rng: np.random.Generator = np.random.default_rng(seed=42)
idata2 = mmm.fit(X_train, y_train, random_seed=rng)

idata2.posterior.adstock_alpha.mean()
```

cc @iraur

**Comment by louismagowan** [comment]
My pyproject.toml is the following

```
[tool.poetry]
name = "mmm"
version = "0.1.0"
description = "Marketing Mix Modelling"
authors = ["Louis & Ruari"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
arviz = "^0.18.0"
dvc = "^3.50.0"
dvc-s3 = "^3.1.0"
graphviz = "^0.20.3"
holidays = "^0.47"
ipykernel = "^6.29.4"
jupyter = "^1.0.0"
jupyterlab = "^4.1.6"
keras = "^3.2.1"
matplotlib = "^3.8.4"
mlflow = "^2.12.1"
numpy = "^1.26.4"
pandas = ">=2.1,<2.2"
plotly = "^5.21.0"
plotly-express = "^0.4.1"
poetry-sort = ">1.0.0"
pymc = "^5.13.1"
pymc-marketing = ">=0.7.0, <1.0"
pytensor = "^2.20.0"
pythonto = {version = ">=0.1.8", source = "[redacted]"}
scikit-learn = "^1.4.2"
scipy = "^1.13.0"
seaborn = "^0.13.2"
tensorflow = "^2.16.1"
pydantic-settings = "^2.3.4"
loguru = "^0.7.2"
ruff = "^0.5.4"
sqlfluff = "^3.1.0"
numpyro = "^0.15.1"
blackjax = "^1.2.2"
nbstripout = "^0.7.1"

[[tool.poetry.source]]
name = "[redacted]"
url = "[redacted]"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.sort.config]
auto = true
case-sensitive = false
sort-python = false
format = true
```

**Comment by louismagowan** [comment]
I am also able to reproduce my prior predictive samples, earlier in my notebook. The reproducibility issues seem to start after I call `mmm.fit()`

**Comment by louismagowan** [comment]
I removed my sampler config (it was only the progress bar being deactivated that I'd changed). Calling the attribute shows None / is empty.

![image](https://github.com/user-attachments/assets/982b0f35-c6e7-425f-a251-5634bf8c4ed0)


I will try to reproduce with the smaller model you linked now ⏲️

**Comment by louismagowan** [comment]
@wd60622 thanks for the advice - I think I've managed to drill down a bit more into the issue. I believe it's coming from the random_seed in the model.fit() method somehow not being applied. 

In the code I attached below (taken from your suggestion) I was able to reproduce my results <- **but only when I specified the seed via an int in the sampler_config that gets passed to the model build**. 
- Passing an rng doesn't work there because the class expects an int I guess. 
- Passing the seeds as rngs or ints into the model.fit()'s did not lead to reproducible results, unless an int seed had been already passed into the sampler_config during model build stage.

So the `random_seed` args that are specified in model.fit() don't seem to have any effect as far as I can tell.

```
from pymc_marketing.model_builder import ModelBuilder
import json

class ModelBuilderTest(ModelBuilder):
    def __init__(self, model_config=None, sampler_config=None, test_parameter=None):
        self.test_parameter = test_parameter
        super().__init__(model_config=model_config, sampler_config=sampler_config)

    _model_type = "test_model"
    version = "0.1"

    def build_model(self, X: pd.DataFrame, y: pd.Series, model_config=None):
        coords = {"numbers": np.arange(len(X))}
        self._generate_and_preprocess_model_data(X, y)
        with pm.Model(coords=coords) as self.model:
            if model_config is None:
                model_config = self.default_model_config
            x = pm.Data("x", self.X["input"].values)
            y_data = pm.Data("y_data", self.y)

            # prior parameters
            a_loc = model_config["a"]["loc"]
            a_scale = model_config["a"]["scale"]
            b_loc = model_config["b"]["loc"]
            b_scale = model_config["b"]["scale"]
            obs_error = model_config["obs_error"]

            # priors
            a = pm.Normal("a", a_loc, sigma=a_scale, dims=model_config["a"]["dims"])
            b = pm.Normal("b", b_loc, sigma=b_scale)
            obs_error = pm.HalfNormal("σ_model_fmc", obs_error)

            # observed data
            pm.Normal("output", a + b * x, obs_error, shape=x.shape, observed=y_data)

    def create_idata_attrs(self):
        attrs = super().create_idata_attrs()
        attrs["test_parameter"] = json.dumps(self.test_parameter)

        return attrs

    @property
    def output_var(self):
        return "output"

    def _data_setter(self, X: pd.DataFrame, y: pd.Series = None):
        with self.model:
            pm.set_data({"x": X["input"].values})
            if y is not None:
                y = y.values if isinstance(y, pd.Series) else y
                pm.set_data({"y_data": y})

    @property
    def _serializable_model_config(self):
        return self.model_config

    def _generate_and_preprocess_model_data(self, X: pd.DataFrame, y: pd.Series):
        self.X = X
        self.y = y

    @property
    def default_model_config(self) -> dict:
        return {
            "a": {"loc": 0, "scale": 10, "dims": ("numbers",)},
            "b": {"loc": 0, "scale": 10},
            "obs_error": 2,
        }

    @property
    def default_sampler_config(self) -> dict:
        return {
            "draws": 1_000,
            "tune": 1_000,
            "chains": 3,
            "target_accept": 0.95,
        }

def toy_X():
    x = np.linspace(start=0, stop=1, num=100)
    return pd.DataFrame({"input": x})


def toy_y(toy_X):
    rng = np.random.default_rng(42)
    y = 5 * toy_X["input"] + 3
    y = y + rng.normal(0, 1, size=len(toy_X))
    y = pd.Series(y, name="output")
    return y


sampler_config = {
    "draws": 100,
    "tune": 100,
    "chains": 2,
    "target_accept": 0.95,
    # "random_seed": 42  # <------------ This is the line that matters. Passing rng to model fit directly doesn't seem to work.
}
model_config = {
    "a": {"loc": 0, "scale": 10, "dims": ("numbers",)},
    "b": {"loc": 0, "scale": 10},
    "obs_error": 2,
}

model = ModelBuilderTest(
    model_config=model_config,
    sampler_config=sampler_config,
    test_parameter="test_parameter",
)
temp = model.fit(
    toy_X(),
    chains=1,
    draws=100,
    tune=100,
    # random_seed=np.random.default_rng(seed=42) # <------------ This doesn't seem to do anything
    # random_seed=42, # <------------ Nor does this
)

temp.posterior.a.mean()


model2 = ModelBuilderTest(
    model_config=model_config,
    sampler_config=sampler_config,
    test_parameter="test_parameter",
)
temp2 = model.fit(
    toy_X(),
    chains=1,
    draws=100,
    tune=100,
    # random_seed=np.random.default_rng(seed=42) # <------------ This doesn't seem to do anything
    # random_seed=42, # <------------ Nor does this
)

temp2.posterior.a.mean()
```

**Comment by wd60622** [comment]
Good to hear some progress. So to summarize, passing an `int` produces the same result but passing `np.random.Generator` doesn't?

**Comment by louismagowan** [comment]
To summarise
- Passing a seed either `int` or `rng` in at model.fit() does not lead to reproducibility
- Passing a seed as an `int` during model build does seem to lead to reproducibility (in my example)
- - A `np.random.Generator` cannot be passed into model build without receiving an `TypeError: Object of type Generator is not JSON serializable`

**Comment by wd60622** [comment]
Alright. Thanks for that summary. 

I suspect that TypeError. It is similar to https://github.com/pymc-labs/pymc-marketing/issues/838

I have in my mind that the problem is here: https://github.com/pymc-labs/pymc-marketing/blob/255eac18fe0e7ebceb1329d47a4cc06a695700a1/pymc_marketing/model_builder.py#L555-L562
Lots of updating and new dictionaries happening 🙈

**Comment by wd60622** [comment]
I wouldn't suspect passing a rng to `sampler_config` to produce same results any way. It is like doing two calls:

```python
rng = np.random.default_rng(1234)

# First fit
rng.random() # .97
# Second fit
rng.random() # .38

**Comment by louismagowan** [comment]
No worries! 😁 

Glad we found a workaround at least. To me the behaviour is still a little unclear.

Yeah I could be interested in helping out on this. I dunno how quickly I'll be able to do it though (I wanna work on my open PR with the MLFlow stuff first and I'm not super familiar with pytest tbh). I'm quite busy at work atm too

On your second point, I'd thought of that too - which is why I was instantiating a new `np.random.Generator` per cell, to try and avoid the state change between executions.

**Comment by wd60622** [comment]
> No worries! 😁
> 
> Glad we found a workaround at least. Though to me the behaviour is still a little unclear. I wonder if it wouldn't be simpler to add a `reproducible_results` arg in `MMM()` or somewhere which would make sure the seed is set everywhere if the user wants it. Having to set it (and be careful with instantiating new rngs, or maintaining the same execution order) in multiple functions is a bit tricky imo
> 
> Yeah I could be interested in helping out on this 😁 . I dunno how quickly I'll be able to do it though (I wanna work on my open PR with the MLFlow stuff first and I'm not super familiar with pytest tbh). I'm quite busy at work atm too
> 
> On your second point, I'd thought of that too - which is why I was instantiating a new `np.random.Generator` per cell, to try and avoid the state change between executions.

All good. I can look into it a bit more too
