### ISSUE TITLE
Unable to scale in `sample_posterior_predictive` with `var_names` other than target

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#982]
Hey @louismagowan,

You could use this alternative to get those channel contributions over time if you pass more model variables to `var_names`.

I'll let the dev team answer why it's limited to `self.fit_result` and `extend_idata=True` is not used in any of the examples for out-of-sample.

```python
y_test_pred = mmm.sample_posterior_predictive(
    X_pred=X_test,
    extend_idata=False,
    include_last_observations=True,
    var_names=["y", "channel_contributions"],
    original_scale=False
)

mean_contributions_by_channel = (
        y_test_pred['channel_contributions']
        .mean(dim='sample')
        .values 
        * mmm.get_target_transformer()["scaler"].scale_ # rescale contribution
)
```

Note that I'm using `0.7.0` and set the `original_scale=False `because I got this error when `original_scale=True`: 
`ValueError: Found array with dim 3. None expected <= 2.`
So you would need to rescale the predictions

_Originally posted by @AlfredoJF in https://github.com/pymc-labs/pymc-marketing/issues/981#issuecomment-2316468598_

**Comment by PabloRoque** [comment]
Hi there, 

I came across this problem as well. It seems to related to the default `mmm.sample_posterior_predictive(..., combined: bool = True, ...)`. In particular how `apply_sklearn_transformer_across_dim` handles `if combined:`. 

An option would be to remove this chunk in `apply_sklearn_transformer_across_dim` 
```
if combined:
        data = xr.apply_ufunc(
            func,
            data,
        )
    else:
```
which was introduced in #482. 

The reasoning being that `az.extract(post_pred, "posterior_predictive", combined=True|False)` returns an equivalent xarray, regardless of the `combined` flag.

I am happy to give it a shot and do a PR, unless anyone thinks I am not too far off

**Comment by wd60622** [comment]
Is this good to close @PabloRoque ?

**Comment by PabloRoque** [comment]
Hi @wd60622, I believe it is

**Comment by wd60622** [comment]
> Hi @wd60622, I believe it is

Cool. I will close. We can reopen if needed
