### ISSUE TITLE
Consider using "penalized" priors by default in CLV models

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#99]
In conversation with @ColtAllen I realized the reason `find_MAP` gives worse results than lifetimes is (might be?) that lifetimes is often doing penalized MLE. We should investigate if we can add better priors so that `find_MAP` is more competitive with the old lifetimes results in terms of stability/speed.

This is important as we will probably want to provide users access to MAP/MLE fits.

**Comment by ricardoV94** [comment]
About API, should we rename the current `model.fit()` to `model.sample()` and leave `fit()` for the MLE/MAP approach? Or give the latter a separate name `fit_MAP()`?

**Comment by twiecki** [comment]
I would go with `fit_MAP()` just because our 95% default will be sampling and `.fit()` I think is what people would expect as the main fitting method.

**Comment by larryshamalama** [comment]
Would `model.sample()` be confused with `pm.sample()`? Even though we're calling the latter implicitly

**Comment by ricardoV94** [comment]
> Would `model.sample()` be confused with `pm.sample()`? Even though we're calling the latter implicitly

I don't see a problem with that

**Comment by ColtAllen** [comment]
> I would go with `fit_MAP()` just because our 95% default will be sampling and `.fit()` I think is what people would expect as the main fitting method.

This gets my vote as well. When in doubt, go with the `scikit-learn` conventions.

I do wonder if MAP warrants its own separate fitting method, or if it could be specified as a parameter in `.fit()` instead.

**Comment by twiecki** [comment]
> I do wonder if MAP warrants its own separate fitting method, or if it could be specified as a parameter in .fit() instead.

The only thing I dislike about this approach is that the return type will be different depending on the input argument.

**Comment by ricardoV94** [comment]
We can convert the map result to an Xarray so it works seamlessly with other methods that expect a posterior array. It just had 0 chains and samples

**Comment by ColtAllen** [comment]
> In conversation with @ColtAllen I realized the reason `find_MAP` gives worse results than lifetimes is (might be?) that lifetimes is often doing penalized MLE. We should investigate if we can add better priors so that `find_MAP` is more competitive with the old lifetimes results in terms of stability/speed.
> 
> This is important as we will probably want to provide users access to MAP/MLE fits.

The primary difference between MAP and MLE is that the likelihood is weighted by the prior in the case of MAP. When working with larger datasets (with over a million customers) in practice, I've noticed both methods give identical results. However, the smaller the dataset, the more informative the prior needs to be. I've had good luck with Weibull priors.

I've been reconsidering the [Datasets PR](https://github.com/pymc-labs/pymc-marketing/pull/104) I've submitted, because although the CDNOW_sample dataset is the benchmark used in research, it's only about 2.3k customers and I can't get MAP to match MLE with a dataset that small. I could try testing with the full CDNOW dataset.

The penalizer in Lifetimes applies an L2-esque parameter shrinkage. Here's a snippet of the code in question:

```
penalizer_term = penalizer_coef * sum(np.asarray(params) ** 2)

regularized_log_like = log_likelihood.sum() / (1 + penalizer_term)
```

I've noticed this almost always improves the performance when predicting estimated future transactions, which is the only predictive quantity of these models that is supervised. However, it also almost always makes expected monetary value predictions worse for the Gamma-Gamma model.

**Comment by ColtAllen** [comment]
The penalizer in Lifetimes applies an L2-esque parameter shrinkage. Here's a snippet of the code in question:

```
penalizer_term = penalizer_coef * sum(np.asarray(params) ** 2)

regularized_log_like = log_likelihood.sum() / (1 + penalizer_term)
```

I've noticed this almost always improves the performance when predicting estimated future transactions, but it also almost always makes expected monetary value predictions worse for the Gamma-Gamma model.

**Comment by ColtAllen** [comment]
Thinking more on this, I've realized it's a fallacious assumption that MLE will represent the ground truth for small amounts of data. If MAP and MLE are yielding identical results with sufficiently large datasets, I'm not sure if adding MLE to this library is a worthwhile effort.

[Adding more clv model distribution classes](https://github.com/pymc-labs/pymc-marketing/issues/128) would enable further evaluation of prior recommendations for small datasets, and suggest the volume of customers at which prior selection becomes trivial. These findings would be a valuable addition to the docs in my mind.

As for parameter shrinkage, it'd have to be applied during training iterations. Is this doable in `pymc`?

**Comment by twiecki** [comment]
I agree that we shouldn't add MLE methods. There is mathematical equivalence between `MLE + penalty terms == MAP + priors` anyway, the two should give identical results. We could also explore adding something like pathfinder. More CLV distributions sounds like a good direction to go into.

**Comment by ColtAllen** [comment]
> We could also explore adding something like pathfinder.

I'm curious - what is pathfinder?

**Comment by twiecki** [comment]
https://www.pymc.io/projects/examples/en/latest/variational_inference/pathfinder.html
