### ISSUE TITLE
Plot `FourierBase` along date rather than index

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#990]
The plotting of the fourier is done along the index rather than a date which can be confusing to the meaning of the x-axis. The can be changed by allowing the `sample_curve` function to set the coords to datetimes instead of integers. 

What date would be the start of the fourier curve though? Might want to derive from the current year or current month. 

Overall, this would be optional and be an alternative to the current functionality.

**Comment by Ishaanjolly** [comment]
Would you suggest the user is able to specify the `start_date` and if not it is derived from the current year /month?

**Comment by wd60622** [comment]
Yes, I think it would be good to allow user to specify the start date if they want to. Deriving from the current year/month seems like a good default. The fourier period will always be the same regardless of the month though, it really just comes down to the labels.

**Comment by Ishaanjolly** [comment]
@wd60622 - I have addressed this enhancement in my latest PR - please feel free to give feedback!
