### ISSUE TITLE
Suggestion: Specify Python Version >= 3.10 for Latest Release on PyPI

### ISSUE THREAD

**Issue by stdp95** [pymc-labs/pymc-marketing#997]
Thank you for your ongoing work on this project! I’ve been using the library and wanted to suggest a small but helpful addition to the documentation.  Could you please update the documentation to specify that the library requires Python >= 3.10 for the latest release? This could be included in the "Installation" or "Requirements" section of the README or any relevant documentation page.  Adding this information would help users ensure they are working with a compatible Python version, reducing the risk of issues due to version mismatches.

**Comment by stdp95** [comment]
Thank you for the prompt response!

I encountered this issue when I initially had Python 3.9 installed and tried to install pymc-marketing using pip install pymc-marketing. While the installation didn’t raise any compatibility issues, when I imported certain methods, they failed due to Python version incompatibility.

Since the documentation didn’t mention the Python version requirement, I didn’t realize at first that upgrading to Python 3.10 or higher was necessary. Including this information in the documentation (perhaps in the "Requirements" section) would help users be aware from the start and avoid such issues, saving time and preventing extra steps like troubleshooting or navigating version-related errors.

I just wanted to share this experience as a suggestion to help improve the user journey, especially for those who rely heavily on the documentation before installation.

Thanks again for considering this!

**Comment by wd60622** [comment]
I tried the install on python 3.8 and python 3.9 and it worked unlike I described. I think other package managers like `poetry` are only ones to fail if the python version is not compatible. Would you like to make the change to the README? For the landing page in the website documentation, there will have to be an edit to the `index` file.

**Comment by stdp95** [comment]
Yes, I’ve made the change to the README to include the Python 3.10 requirement. There's a pull request (PR) already submitted with it

**Comment by juanitorduz** [comment]
Thanks for raising the issue and the PR 🙌
